import { a1LexiconEntries } from './lexicon-a1.js';
import { a2LexiconEntries } from './lexicon-a2.js';

// V19.4: centraal lexicon. Dit bestand is de enige bron voor nagekeken
// definities en voorbeelden die door meerdere cursuskaarten worden gedeeld.

export function normalizeLexeme(value) {
  return String(value || '')
    .trim()
    .toLocaleLowerCase('nl-NL')
    .replace(/[“”„'‘’.,!?;:()]/gu, '')
    .replace(/\s+/gu, ' ');
}

function lexeme(term, definition, example, kind = 'woord', level = 'A0', extra = {}) {
  return {
    term,
    definition,
    example,
    kind,
    level,
    status: 'editorially-reviewed',
    source: 'V19.4 centrale lexiconredactie',
    ...extra,
  };
}

export const centralLexiconEntries = [
  // Begroeten, antwoorden, bedanken en afscheid nemen.
  lexeme('hallo', 'Een gewone, informele begroeting die op bijna elk moment van de dag past.', 'Hallo, ik ben Mina. Hoe heet jij?', 'begroeting'),
  lexeme('hoi', 'Een informele begroeting voor iemand die je kent of op een ontspannen manier aanspreekt.', 'Hoi Karim, fijn dat je er bent.', 'begroeting'),
  lexeme('goedemorgen', 'Een beleefde begroeting die je vanaf de ochtend tot ongeveer het middaguur gebruikt.', 'Goedemorgen, mevrouw De Vries.', 'begroeting'),
  lexeme('goedemiddag', 'Een beleefde begroeting die je in de middag gebruikt.', 'Goedemiddag, welkom bij de afspraak.', 'begroeting'),
  lexeme('goedenavond', 'Een beleefde begroeting die je in de avond gebruikt.', 'Goedenavond, alles goed met u?', 'begroeting'),
  lexeme('welkom', 'Een vriendelijke begroeting waarmee je laat merken dat iemand naar binnen mag of verwacht werd.', 'Welkom in onze nieuwe woning.', 'begroeting'),
  lexeme('hé', 'Een zeer informele begroeting of uitroep om iemands aandacht te krijgen.', 'Hé Noor, wacht even op mij.', 'begroeting'),
  lexeme('dag', 'Een korte begroeting of afscheidsgroet die zowel formeel als informeel kan klinken.', 'Dag meneer, tot de volgende afspraak.', 'begroeting'),
  lexeme('aangenaam', 'Een beleefde reactie wanneer je iemand voor het eerst ontmoet.', 'Aangenaam, ik ben Fatima.', 'uitdrukking'),
  lexeme('fijn je te zien', 'Een vriendelijke zin waarmee je zegt dat je blij bent iemand weer te ontmoeten.', 'Fijn je te zien, hoe gaat het?', 'uitdrukking'),
  lexeme('alles goed?', 'Een informele vraag of het goed met iemand gaat.', 'Hoi Sam, alles goed?', 'vraag'),
  lexeme('hoe gaat het?', 'Een vraag naar hoe iemand zich voelt of hoe het met iemand gaat.', 'Goedemorgen, hoe gaat het met u?', 'vraag'),
  lexeme('goed', 'Positief, in orde of van voldoende kwaliteit.', 'Het gaat goed met mij.', 'bijvoeglijk woord'),
  lexeme('heel goed', 'Een sterk positief antwoord waarmee je zegt dat iets bijzonder goed gaat.', 'Dank je, het gaat heel goed.', 'uitdrukking'),
  lexeme('prima', 'Een informeel positief antwoord met de betekenis dat alles goed of in orde is.', 'Prima, dan zie ik je om drie uur.', 'antwoord'),
  lexeme('best goed', 'Een gematigd positief antwoord: niet perfect, maar duidelijk beter dan slecht.', 'Na een drukke week gaat het best goed.', 'uitdrukking'),
  lexeme('het gaat', 'Een terughoudend antwoord waarmee je zegt dat het niet slecht, maar ook niet bijzonder goed gaat.', 'Hoe gaat het? Het gaat, ik ben alleen moe.', 'uitdrukking'),
  lexeme('niet zo goed', 'Een antwoord waarmee je aangeeft dat je je niet goed voelt of dat iets minder goed verloopt.', 'Vandaag gaat het niet zo goed met mij.', 'uitdrukking'),
  lexeme('ook goed', 'Een kort antwoord waarmee je zegt dat het met jou eveneens goed gaat.', 'Met mij gaat het ook goed, dank je.', 'uitdrukking'),
  lexeme('dank je', 'Een informele uitdrukking waarmee je één persoon bedankt.', 'Dank je voor de koffie.', 'bedanking'),
  lexeme('dank u', 'Een beleefde of formele uitdrukking waarmee je iemand bedankt.', 'Dank u voor uw duidelijke uitleg.', 'bedanking'),
  lexeme('en met jou?', 'Een informele tegenvraag nadat iemand heeft gevraagd hoe het met je gaat.', 'Met mij gaat het goed. En met jou?', 'vraag'),
  lexeme('en met u?', 'Een beleefde tegenvraag nadat iemand heeft gevraagd hoe het met je gaat.', 'Dank u, het gaat goed. En met u?', 'vraag'),
  lexeme('ja, hoor', 'Een geruststellend bevestigend antwoord waarmee je laat merken dat iets werkelijk in orde is.', 'Is deze stoel vrij? Ja, hoor.', 'antwoord'),
  lexeme('bedankt', 'Een veelgebruikte informele uitdrukking waarmee je waardering voor hulp of iets ontvangen uitspreekt.', 'Bedankt voor het bericht.', 'bedanking'),
  lexeme('dank je wel', 'Een informele uitdrukking waarmee je iemand nadrukkelijk bedankt.', 'Dank je wel voor je hulp.', 'bedanking'),
  lexeme('dank u wel', 'Een beleefde uitdrukking waarmee je iemand nadrukkelijk bedankt.', 'Dank u wel voor uw tijd.', 'bedanking'),
  lexeme('heel erg bedankt', 'Een sterke bedanking waarmee je veel waardering uitspreekt.', 'Heel erg bedankt voor alle hulp bij de verhuizing.', 'bedanking'),
  lexeme('graag gedaan', 'Een vriendelijk antwoord op een bedanking waarmee je zegt dat helpen geen bezwaar was.', 'Graag gedaan, ik help je met plezier.', 'antwoord'),
  lexeme('geen dank', 'Een bescheiden antwoord op een bedanking waarmee je zegt dat bedanken niet nodig is.', 'Geen dank, het was maar een kleine moeite.', 'antwoord'),
  lexeme('alsjeblieft', 'Een informeel woord bij een verzoek of wanneer je iets aan iemand geeft.', 'Hier is je sleutel, alsjeblieft.', 'beleefdheidswoord'),
  lexeme('alstublieft', 'Een beleefd woord bij een verzoek of wanneer je iets aan iemand geeft.', 'Een glas water, alstublieft.', 'beleefdheidswoord'),
  lexeme('dat is aardig', 'Een reactie waarmee je zegt dat je iemands gebaar vriendelijk of attent vindt.', 'U brengt de tas voor mij? Dat is aardig.', 'uitdrukking'),
  lexeme('fijn, bedankt', 'Een kort positief antwoord waarmee je bevestigt dat iets goed is en meteen bedankt.', 'De afspraak is verzet naar vrijdag. Fijn, bedankt.', 'uitdrukking'),
  lexeme('tot ziens', 'Een neutrale of beleefde manier om afscheid te nemen wanneer je verwacht iemand later weer te zien.', 'Bedankt voor uw bezoek. Tot ziens!', 'afscheid'),
  lexeme('doei', 'Een informele afscheidsgroet voor vrienden, familie of bekenden.', 'Doei, tot morgen op school!', 'afscheid'),
  lexeme('tot morgen', 'Een afscheid waarmee je zegt dat je iemand de volgende dag weer ziet.', 'Tot morgen bij de taalles.', 'afscheid'),
  lexeme('tot straks', 'Een afscheid waarmee je zegt dat je iemand later op dezelfde dag weer ziet.', 'Ik ga nu naar de winkel. Tot straks!', 'afscheid'),
  lexeme('tot later', 'Een informeel afscheid zonder precies te zeggen wanneer je elkaar weer ziet.', 'Ik moet nu werken. Tot later!', 'afscheid'),
  lexeme('tot snel', 'Een afscheid waarmee je de wens uitspreekt iemand binnen korte tijd terug te zien.', 'Bedankt voor het bezoek en tot snel.', 'afscheid'),
  lexeme('fijne dag', 'Een vriendelijke wens waarmee je iemand een prettige rest van de dag wenst.', 'Tot ziens en een fijne dag!', 'wens'),
  lexeme('fijne avond', 'Een vriendelijke wens waarmee je iemand een prettige avond wenst.', 'Dank u voor het eten. Fijne avond!', 'wens'),
  lexeme('welterusten', 'Een wens die je uitspreekt wanneer iemand gaat slapen.', 'Welterusten, slaap lekker.', 'wens'),
  lexeme('goede reis', 'Een wens waarmee je iemand een veilige en prettige reis toewenst.', 'Goede reis naar Duitsland!', 'wens'),
  lexeme('veel plezier', 'Een wens waarmee je hoopt dat iemand van een activiteit of gebeurtenis geniet.', 'Veel plezier op het feest vanavond.', 'wens'),

  // Jezelf voorstellen, herkomst, wonen en talen.
  lexeme('de naam', 'Het woord of de combinatie van woorden waarmee een persoon, plaats of zaak wordt aangeduid.', 'Mijn naam is Noor El Amrani.', 'zelfstandig naamwoord'),
  lexeme('de voornaam', 'De persoonlijke naam die vóór de achternaam staat.', 'Mijn voornaam is Bernardo.', 'zelfstandig naamwoord'),
  lexeme('de achternaam', 'De familienaam die je vaak met andere familieleden deelt.', 'Kunt u uw achternaam spellen?', 'zelfstandig naamwoord'),
  lexeme('ik heet', 'Een korte vaste zin waarmee je je naam noemt.', 'Ik heet Amir en dit is mijn zus.', 'uitdrukking'),
  lexeme('mijn naam is', 'Een vaste zin waarmee je op een neutrale manier je naam noemt.', 'Mijn naam is Sara Jansen.', 'uitdrukking'),
  lexeme('hoe heet je?', 'Een informele vraag naar de naam van één persoon.', 'Hallo, hoe heet je?', 'vraag'),
  lexeme('hoe heet u?', 'Een beleefde of formele vraag naar de naam van één persoon.', 'Goedemiddag, hoe heet u?', 'vraag'),
  lexeme('dit is', 'Een vaste combinatie waarmee je een persoon of zaak aanwijst en voorstelt.', 'Dit is mijn collega Peter.', 'uitdrukking'),
  lexeme('ik ben', 'Een combinatie waarmee je vertelt wie je bent, hoe je bent of waar je bent.', 'Ik ben Lina en ik ben nieuw hier.', 'uitdrukking'),
  lexeme('wie ben jij?', 'Een informele vraag naar de identiteit van één persoon.', 'Ik ben Omar. Wie ben jij?', 'vraag'),
  lexeme('leuk je te ontmoeten', 'Een informele vriendelijke reactie wanneer je iemand voor het eerst ontmoet.', 'Leuk je te ontmoeten, Eva.', 'uitdrukking'),
  lexeme('het land', 'Een gebied met eigen grenzen en meestal een eigen regering.', 'Nederland is het land waar ik nu woon.', 'zelfstandig naamwoord'),
  lexeme('de stad', 'Een grote woonplaats met veel inwoners, straten en voorzieningen.', 'Eindhoven is een stad in Noord-Brabant.', 'zelfstandig naamwoord'),
  lexeme('het dorp', 'Een kleinere woonplaats met minder inwoners dan een stad.', 'Mijn ouders wonen in een rustig dorp.', 'zelfstandig naamwoord'),
  lexeme('ik kom uit', 'Een vaste zin waarmee je je land, stad of plaats van herkomst noemt.', 'Ik kom uit Colombia.', 'uitdrukking'),
  lexeme('waar kom je vandaan?', 'Een informele vraag naar het land, de stad of plaats van herkomst.', 'Waar kom je vandaan? Ik kom uit Spanje.', 'vraag'),
  lexeme('waar komt u vandaan?', 'Een beleefde vraag naar het land, de stad of plaats van herkomst.', 'Waar komt u vandaan, meneer Kaya?', 'vraag'),
  lexeme('Nederland', 'Het land in West-Europa waar Nederlands de belangrijkste officiële taal is.', 'Ik woon en werk in Nederland.', 'landnaam'),
  lexeme('België', 'Het buurland ten zuiden van Nederland met Nederlands, Frans en Duits als officiële talen.', 'Brussel ligt in België.', 'landnaam'),
  lexeme('Duitsland', 'Het buurland ten oosten van Nederland waar vooral Duits wordt gesproken.', 'Wij rijden morgen naar Duitsland.', 'landnaam'),
  lexeme('Colombia', 'Een land in het noordwesten van Zuid-Amerika met Spaans als officiële taal.', 'Mijn familie woont in Colombia.', 'landnaam'),
  lexeme('Spanje', 'Een land in Zuidwest-Europa waar vooral Spaans wordt gesproken.', 'Deze zomer reizen we naar Spanje.', 'landnaam'),
  lexeme('Turkije', 'Een land dat deels in Europa en deels in Azië ligt en waar vooral Turks wordt gesproken.', 'Mijn buurman komt uit Turkije.', 'landnaam'),
  lexeme('wonen', 'Op een bepaalde plaats je vaste huis of verblijf hebben.', 'Wij wonen dicht bij een park.', 'werkwoord'),
  lexeme('ik woon in', 'Een vaste zin waarmee je je woonplaats of het land waar je woont noemt.', 'Ik woon in Eindhoven.', 'uitdrukking'),
  lexeme('waar woon je?', 'Een informele vraag naar de plaats waar iemand woont.', 'Waar woon je? Ik woon in Utrecht.', 'vraag'),
  lexeme('waar woont u?', 'Een beleefde vraag naar de plaats waar iemand woont.', 'Waar woont u, mevrouw Bakker?', 'vraag'),
  lexeme('hier', 'Op deze plaats, dicht bij de spreker.', 'Ik woon hier sinds januari.', 'plaatswoord'),
  lexeme('daar', 'Op die plaats, op enige afstand van de spreker.', 'De bushalte is daar, naast de supermarkt.', 'plaatswoord'),
  lexeme('de straat', 'Een openbare weg met huizen, winkels of andere gebouwen erlangs.', 'Wij wonen in een rustige straat.', 'zelfstandig naamwoord'),
  lexeme('het huis', 'Een gebouw dat bedoeld is om in te wonen.', 'Ons huis heeft een kleine tuin.', 'zelfstandig naamwoord'),
  lexeme('de flat', 'Een woning die deel uitmaakt van een gebouw met meerdere woningen boven of naast elkaar.', 'Zij woont op de derde verdieping van een flat.', 'zelfstandig naamwoord'),
  lexeme('de buurt', 'Het gebied met straten en woningen rondom de plaats waar iemand woont.', 'Onze buurt heeft een school en twee winkels.', 'zelfstandig naamwoord'),
  lexeme('de plaats', 'Een bepaalde locatie of een woonplaats zoals een stad of dorp.', 'Vul hier de datum en de plaats in.', 'zelfstandig naamwoord'),
  lexeme('het adres', 'De straat, het huisnummer, de postcode en de woonplaats van een locatie.', 'Mijn adres is Marktstraat 12 in Breda.', 'zelfstandig naamwoord'),
  lexeme('de taal', 'Een systeem van woorden en regels waarmee mensen mondeling of schriftelijk communiceren.', 'Nederlands is de taal die ik leer.', 'zelfstandig naamwoord'),
  lexeme('Nederlands', 'De taal die in Nederland en een deel van België wordt gesproken.', 'Ik leer Nederlands op school.', 'taalnaam'),
  lexeme('Engels', 'De taal die onder meer in het Verenigd Koninkrijk en veel andere landen wordt gebruikt.', 'Op mijn werk spreek ik vaak Engels.', 'taalnaam'),
  lexeme('Spaans', 'De taal die in Spanje en in veel landen van Latijns-Amerika wordt gesproken.', 'Thuis spreken wij Spaans.', 'taalnaam'),
  lexeme('Duits', 'De taal die vooral in Duitsland, Oostenrijk en een deel van Zwitserland wordt gesproken.', 'Mijn collega spreekt vloeiend Duits.', 'taalnaam'),
  lexeme('Frans', 'De taal die onder meer in Frankrijk, Wallonië en delen van Canada wordt gesproken.', 'Zij leert Frans voor haar werk.', 'taalnaam'),
  lexeme('spreken', 'Met je stem woorden en zinnen uitspreken om met anderen te communiceren.', 'Spreekt u Nederlands?', 'werkwoord'),
  lexeme('begrijpen', 'De betekenis van woorden, een uitleg of een situatie kunnen volgen.', 'Ik begrijp de vraag nu.', 'werkwoord'),
  lexeme('een beetje', 'Een kleine hoeveelheid of in beperkte mate.', 'Ik spreek een beetje Nederlands.', 'hoeveelheidsuitdrukking'),
  lexeme('niet goed', 'Een negatieve beoordeling waarmee je zegt dat iets onvoldoende of verkeerd is.', 'Ik hoor u niet goed door het lawaai.', 'uitdrukking'),
  lexeme('welke taal spreek je?', 'Een informele vraag naar de taal of talen die iemand kan spreken.', 'Welke taal spreek je thuis?', 'vraag'),

  // Begrijpen, herhalen, hulp en richting.
  lexeme('ik begrijp het niet', 'Een vaste zin waarmee je zegt dat de betekenis of uitleg niet duidelijk voor je is.', 'Sorry, ik begrijp het niet.', 'uitdrukking'),
  lexeme('ik weet het niet', 'Een vaste zin waarmee je zegt dat je het antwoord of de informatie niet kent.', 'Hoe laat vertrekt de trein? Ik weet het niet.', 'uitdrukking'),
  lexeme('wat betekent dat?', 'Een vraag naar de betekenis van een woord, zin, teken of handeling.', 'Ik ken dit woord niet. Wat betekent dat?', 'vraag'),
  lexeme('wat is dat?', 'Een vraag waarmee je wilt weten welk voorwerp, begrip of geluid wordt bedoeld.', 'Wat is dat op de tafel?', 'vraag'),
  lexeme('hoe zeg je dat?', 'Een informele vraag naar het juiste woord of de juiste formulering.', 'Hoe zeg je dat in het Nederlands?', 'vraag'),
  lexeme('hoe schrijf je dat?', 'Een informele vraag naar de juiste spelling van een woord of naam.', 'Hoe schrijf je dat: met een d of een t?', 'vraag'),
  lexeme('ik spreek nog weinig Nederlands', 'Een zin waarmee je uitlegt dat je het Nederlands nog maar beperkt kunt gebruiken.', 'Kunt u langzaam spreken? Ik spreek nog weinig Nederlands.', 'uitdrukking'),
  lexeme('dat is moeilijk', 'Een reactie waarmee je aangeeft dat iets veel inspanning vraagt of niet gemakkelijk te begrijpen is.', 'Deze oefening is nieuw voor mij; dat is moeilijk.', 'uitdrukking'),
  lexeme('is dit goed?', 'Een vraag waarmee je controleert of iets juist, geschikt of correct uitgevoerd is.', 'Ik schrijf mijn naam hier. Is dit goed?', 'vraag'),
  lexeme('klopt dat?', 'Een vraag waarmee je controleert of informatie of een antwoord juist is.', 'De afspraak is om tien uur, klopt dat?', 'vraag'),
  lexeme('ik ben nieuw hier', 'Een zin waarmee je zegt dat je pas kort op deze plaats, school of werkplek bent.', 'Kunt u mij de ingang wijzen? Ik ben nieuw hier.', 'uitdrukking'),
  lexeme('sorry', 'Een beleefdheidswoord om je te verontschuldigen of iemands aandacht te vragen.', 'Sorry, waar is de bushalte?', 'beleefdheidswoord'),
  lexeme('nog een keer', 'Een verzoek of aanduiding dat iets opnieuw moet gebeuren.', 'Kunt u dat nog een keer zeggen?', 'uitdrukking'),
  lexeme('kunt u dat herhalen?', 'Een beleefde vraag waarmee je iemand vraagt hetzelfde opnieuw te zeggen.', 'Ik verstond het adres niet. Kunt u dat herhalen?', 'vraag'),
  lexeme('kun je dat herhalen?', 'Een informele vraag waarmee je iemand vraagt hetzelfde opnieuw te zeggen.', 'Kun je dat herhalen? De verbinding viel weg.', 'vraag'),
  lexeme('zeg dat nog eens', 'Een informele opdracht waarmee je vraagt dezelfde woorden opnieuw uit te spreken.', 'Zeg dat nog eens, maar iets langzamer.', 'uitdrukking'),
  lexeme('langzamer, alstublieft', 'Een beleefd verzoek om met een lager spreektempo verder te praten.', 'Ik leer nog Nederlands: langzamer, alstublieft.', 'verzoek'),
  lexeme('spreek langzaam', 'Een directe opdracht om niet snel maar in een laag tempo te spreken.', 'Spreek langzaam, dan kan iedereen je volgen.', 'verzoek'),
  lexeme('iets harder', 'Een verzoek om met meer stemvolume te spreken.', 'Kunt u iets harder spreken? Ik hoor u niet.', 'verzoek'),
  lexeme('iets zachter', 'Een verzoek om met minder stemvolume te spreken.', 'Praat iets zachter, de baby slaapt.', 'verzoek'),
  lexeme('welk woord?', 'Een korte vraag waarmee je wilt weten over welk specifiek woord iemand spreekt.', 'Ik begrijp één woord niet. Welk woord?', 'vraag'),
  lexeme('kunt u het opschrijven?', 'Een beleefde vraag waarmee je iemand vraagt informatie schriftelijk te noteren.', 'Ik versta de straatnaam niet. Kunt u het opschrijven?', 'vraag'),
  lexeme('kunt u het aanwijzen?', 'Een beleefde vraag waarmee je iemand vraagt met een hand of vinger te tonen waar iets is.', 'Welke knop moet ik gebruiken? Kunt u het aanwijzen?', 'vraag'),
  lexeme('laat het zien', 'Een directe opdracht om iets zichtbaar te maken of te tonen.', 'Ik weet niet welke kaart u bedoelt; laat het zien.', 'verzoek'),
  lexeme('helpen', 'Iets doen waardoor een ander een taak kan uitvoeren of een probleem kan oplossen.', 'De medewerker helpt mij met het formulier.', 'werkwoord'),
  lexeme('hulp', 'Ondersteuning die iemand krijgt om een probleem op te lossen of iets te kunnen doen.', 'Ik heb hulp nodig bij de automaat.', 'zelfstandig naamwoord'),
  lexeme('kunt u mij helpen?', 'Een beleefde vraag waarmee je om ondersteuning vraagt.', 'Kunt u mij helpen met dit formulier?', 'vraag'),
  lexeme('kun je mij helpen?', 'Een informele vraag waarmee je om ondersteuning vraagt.', 'Kun je mij helpen met deze tas?', 'vraag'),
  lexeme('ik heb hulp nodig', 'Een duidelijke zin waarmee je zegt dat je ondersteuning nodig hebt.', 'Ik heb hulp nodig bij het invullen van dit formulier.', 'uitdrukking'),
  lexeme('wacht even', 'Een verzoek om korte tijd niet verder te gaan of op dezelfde plaats te blijven.', 'Wacht even, ik pak mijn jas.', 'verzoek'),
  lexeme('kom mee', 'Een uitnodiging of opdracht om samen met de spreker naar een andere plaats te gaan.', 'Kom mee, dan laat ik de kamer zien.', 'verzoek'),
  lexeme('geen probleem', 'Een geruststellende reactie waarmee je zegt dat iets geen bezwaar of moeilijkheid vormt.', 'Kun je morgen komen? Geen probleem.', 'antwoord'),
  lexeme('waar?', 'Een kort vraagwoord waarmee je naar een plaats of locatie vraagt.', 'De afspraak is verplaatst. Waar?', 'vraagwoord'),
  lexeme('links', 'Aan de kant die tegenover rechts ligt.', 'De apotheek is links van de supermarkt.', 'richtingswoord'),
  lexeme('rechts', 'Aan de kant die tegenover links ligt.', 'Sla bij het stoplicht rechts af.', 'richtingswoord'),
  lexeme('rechtdoor', 'Zonder naar links of rechts af te slaan, in dezelfde richting verder.', 'Loop honderd meter rechtdoor.', 'richtingswoord'),
  lexeme('dichtbij', 'Op een kleine afstand van een persoon of plaats.', 'De huisarts is dichtbij; we kunnen lopen.', 'plaatswoord'),
  lexeme('ver weg', 'Op een grote afstand van een persoon of plaats.', 'Het vliegveld ligt ver weg van het centrum.', 'plaatsuitdrukking'),
  lexeme('de ingang', 'De deur, opening of route waardoor je een gebouw of terrein binnengaat.', 'De ingang van het ziekenhuis is aan de voorkant.', 'zelfstandig naamwoord'),
  lexeme('de uitgang', 'De deur, opening of route waardoor je een gebouw of terrein verlaat.', 'De nooduitgang moet vrij blijven.', 'zelfstandig naamwoord'),
  lexeme('het station', 'Een plaats waar treinen stoppen en reizigers kunnen in- of uitstappen.', 'We ontmoeten elkaar bij het station.', 'zelfstandig naamwoord'),
  lexeme('de bushalte', 'Een vaste plaats waar een bus stopt om passagiers te laten in- en uitstappen.', 'De bushalte is tegenover de school.', 'zelfstandig naamwoord'),

  // Dagelijkse basis, cijfers, tijd en behoeften.
  lexeme('ja', 'Een bevestigend antwoord waarmee je instemt of zegt dat iets waar is.', 'Ja, ik wil graag koffie.', 'antwoord'),
  lexeme('nee', 'Een ontkennend antwoord waarmee je weigert of zegt dat iets niet waar is.', 'Nee, dank u, ik heb al gegeten.', 'antwoord'),
  lexeme('misschien', 'Geeft aan dat iets mogelijk is, maar nog niet zeker vaststaat.', 'Misschien kom ik morgen naar de les.', 'bijwoord'),
  lexeme('graag', 'Met plezier of als beleefde manier om te zeggen dat je iets wilt.', 'Ja, graag, ik neem een kop thee.', 'bijwoord'),
  lexeme('nee, dank u', 'Een beleefde manier om een aanbod of verzoek af te wijzen.', 'Wilt u nog koffie? Nee, dank u.', 'antwoord'),
  lexeme('ja, graag', 'Een beleefde manier om een aanbod te accepteren.', 'Wilt u een stoel? Ja, graag.', 'antwoord'),
  lexeme('oké', 'Een informeel woord waarmee je instemming of begrip aangeeft.', 'Oké, ik kom om half negen.', 'antwoord'),
  lexeme('natuurlijk', 'Een bevestigend antwoord waarmee je zegt dat iets vanzelfsprekend of zonder bezwaar mogelijk is.', 'Mag ik hier zitten? Natuurlijk.', 'antwoord'),
  lexeme('even wachten', 'Een kort verzoek om gedurende een kleine hoeveelheid tijd te wachten.', 'Even wachten, de medewerker komt zo.', 'verzoek'),
  lexeme('klaar', 'Voltooid of gereed om te beginnen, vertrekken of gebruikt te worden.', 'Het formulier is klaar om te versturen.', 'bijvoeglijk woord'),
  lexeme('nul', 'Het getal dat geen hoeveelheid aanduidt en vóór één staat.', 'Mijn telefoonnummer begint met nul zes.', 'getal'),
  lexeme('één', 'Het getal dat na nul en vóór twee komt.', 'Ik wil één kaartje naar Utrecht.', 'getal'),
  lexeme('twee', 'Het getal dat na één en vóór drie komt.', 'Wij hebben twee kinderen.', 'getal'),
  lexeme('drie', 'Het getal dat na twee en vóór vier komt.', 'De trein vertrekt van spoor drie.', 'getal'),
  lexeme('vier', 'Het getal dat na drie en vóór vijf komt.', 'De afspraak duurt vier uur.', 'getal'),
  lexeme('vijf', 'Het getal dat na vier en vóór zes komt.', 'De winkel sluit om vijf uur.', 'getal'),
  lexeme('zes', 'Het getal dat na vijf en vóór zeven komt.', 'Ik sta elke ochtend om zes uur op.', 'getal'),
  lexeme('zeven', 'Het getal dat na zes en vóór acht komt.', 'De bus komt over zeven minuten.', 'getal'),
  lexeme('acht', 'Het getal dat na zeven en vóór negen komt.', 'De les begint om acht uur.', 'getal'),
  lexeme('negen', 'Het getal dat na acht en vóór tien komt.', 'Mijn dochter is negen jaar oud.', 'getal'),
  lexeme('tien', 'Het getal dat na negen en vóór elf komt.', 'Een strippenkaart kost tien euro.', 'getal'),
  lexeme('honderd', 'Het getal dat gelijk is aan tien keer tien.', 'De fiets kost honderd euro.', 'getal'),
  lexeme('nu', 'Op dit moment, niet eerder en niet later.', 'De dokter kan u nu ontvangen.', 'tijdwoord'),
  lexeme('vandaag', 'De dag waarop je nu leeft of spreekt.', 'Vandaag werk ik thuis.', 'tijdwoord'),
  lexeme('morgen', 'De dag na vandaag.', 'Morgen ga ik naar de gemeente.', 'tijdwoord'),
  lexeme('gisteren', 'De dag vóór vandaag.', 'Gisteren was de winkel gesloten.', 'tijdwoord'),
  lexeme('vroeg', 'Aan het begin van de dag of eerder dan gebruikelijk.', 'Ik vertrek morgen vroeg naar mijn werk.', 'tijdwoord'),
  lexeme('laat', 'Dicht bij het einde van een periode of later dan verwacht.', 'De trein is vanavond tien minuten laat.', 'tijdwoord'),
  lexeme('hoe laat?', 'Een korte vraag naar een tijdstip.', 'De afspraak is morgen, maar hoe laat?', 'vraag'),
  lexeme('om één uur', 'Een tijdsaanduiding voor precies 13.00 uur of 01.00 uur, afhankelijk van de context.', 'De vergadering begint om één uur.', 'tijduitdrukking'),
  lexeme('een minuut', 'Een tijdseenheid van zestig seconden.', 'Wacht een minuut, ik zoek het adres op.', 'tijdseenheid'),
  lexeme('een uur', 'Een tijdseenheid van zestig minuten.', 'De taalles duurt een uur.', 'tijdseenheid'),
  lexeme('open', 'Toegankelijk voor bezoekers of klanten en niet gesloten.', 'De supermarkt is tot acht uur open.', 'bijvoeglijk woord'),
  lexeme('gesloten', 'Niet toegankelijk voor bezoekers of klanten.', 'De apotheek is op zondag gesloten.', 'bijvoeglijk woord'),
  lexeme('water', 'Een doorzichtige vloeistof die mensen drinken en dagelijks gebruiken.', 'Mag ik een glas water?', 'zelfstandig naamwoord'),
  lexeme('eten', 'Voedsel dat je gebruikt of de handeling waarbij je voedsel inneemt.', 'We kopen eten voor vanavond.', 'zelfstandig naamwoord'),
  lexeme('het toilet', 'Een sanitaire ruimte waar iemand kan plassen of zich kan ontlasten.', 'Pardon, waar is het toilet?', 'zelfstandig naamwoord'),
  lexeme('de telefoon', 'Een apparaat waarmee je kunt bellen, berichten sturen en digitale informatie gebruiken.', 'Mijn telefoon ligt in mijn tas.', 'zelfstandig naamwoord'),
  lexeme('de kaart', 'Een plat document of digitaal middel met informatie, bijvoorbeeld voor betalen, reizen of een route.', 'Ik betaal de treinreis met mijn ov-kaart.', 'zelfstandig naamwoord'),
  lexeme('contant', 'Met munten en bankbiljetten in plaats van elektronisch betalen.', 'Kan ik hier contant betalen?', 'bijwoord'),
  lexeme('pinnen', 'Elektronisch betalen met een bankpas of telefoon via een betaalautomaat.', 'U kunt bij deze kassa pinnen.', 'werkwoord'),
  lexeme('betalen', 'Geld geven of overmaken voor een product, dienst of rekening.', 'Ik betaal de boodschappen met mijn bankpas.', 'werkwoord'),
  lexeme('de dokter', 'Een medisch deskundige die patiënten onderzoekt en behandelt.', 'Ik heb morgen een afspraak bij de dokter.', 'zelfstandig naamwoord'),
  lexeme('de politie', 'De overheidsdienst die toezicht houdt op veiligheid en optreedt bij strafbare feiten of noodsituaties.', 'Bel de politie wanneer u direct gevaar ziet.', 'zelfstandig naamwoord'),
  lexeme('112', 'Het Europese alarmnummer voor direct gevaar en dringende hulp van ambulance, brandweer of politie.', 'Bel 112 bij een ernstige noodsituatie.', 'alarmnummer'),

  // A1 · Thema Hallo: persoonsgegevens, relaties, vraagwoorden en taalhandelingen.
  lexeme('de geboortedatum', 'De kalenderdatum waarop iemand is geboren, meestal genoteerd met dag, maand en jaar.', 'Mijn geboortedatum is 14 mei 1985.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de geboorteplaats', 'De stad of het dorp waar iemand is geboren.', 'Op het formulier schrijf ik Bogotá als geboorteplaats.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de burgerlijke staat', 'De officiële persoonlijke situatie, bijvoorbeeld ongehuwd, getrouwd, gescheiden of weduwe.', 'Bij burgerlijke staat vul ik getrouwd in.', 'zelfstandig naamwoord', 'A1'),
  lexeme('het telefoonnummer', 'Een reeks cijfers waarmee iemand telefonisch bereikbaar is.', 'Kunt u uw telefoonnummer langzaam zeggen?', 'zelfstandig naamwoord', 'A1'),
  lexeme('het e-mailadres', 'Het digitale adres waarnaar elektronische berichten kunnen worden gestuurd.', 'Ik stuur de bevestiging naar uw e-mailadres.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de handtekening', 'De persoonlijke naam of het teken dat iemand schrijft om een document te bevestigen.', 'Zet hier alstublieft uw handtekening.', 'zelfstandig naamwoord', 'A1'),
  lexeme('het formulier', 'Een document met vaste vakken waarin iemand gevraagde informatie invult.', 'Ik vul het formulier voor de gemeente in.', 'zelfstandig naamwoord', 'A1'),
  lexeme('het identiteitsbewijs', 'Een officieel document waarmee iemand zijn of haar identiteit kan aantonen.', 'Neem een geldig identiteitsbewijs mee naar de afspraak.', 'zelfstandig naamwoord', 'A1'),
  lexeme('het paspoort', 'Een officieel reisdocument met persoonsgegevens en nationaliteit van de houder.', 'Mijn paspoort is nog twee jaar geldig.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de voorletters', 'De eerste letters van iemands officiële voornamen.', 'Mijn voorletters zijn B.H.O.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de roepnaam', 'De voornaam die mensen in het dagelijks leven voor iemand gebruiken.', 'Mijn officiële naam is Bernardus, maar mijn roepnaam is Ben.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de contactpersoon', 'De aangewezen persoon met wie je over een zaak, organisatie of afspraak communiceert.', 'Mevrouw De Jong is mijn contactpersoon bij de gemeente.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de inwoner', 'Iemand die in een bepaalde stad, gemeente of land woont.', 'Elke inwoner van de gemeente ontvangt deze brief.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de buitenlander', 'Iemand die uit een ander land afkomstig is of niet de nationaliteit van het betreffende land heeft.', 'Als buitenlander moest hij eerst de lokale regels leren kennen.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de moedertaal', 'De eerste taal die iemand als kind thuis leert.', 'Spaans is mijn moedertaal.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de buurman', 'Een man die naast of dicht bij je woont.', 'Mijn buurman helpt mij met de fiets.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de buurvrouw', 'Een vrouw die naast of dicht bij je woont.', 'De buurvrouw brengt een pakketje langs.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de vriend', 'Een man of jongen met wie iemand een persoonlijke vriendschap heeft; soms ook een mannelijke partner.', 'Mijn vriend woont in dezelfde straat.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de vriendin', 'Een vrouw of meisje met wie iemand een persoonlijke vriendschap heeft; soms ook een vrouwelijke partner.', 'Mijn vriendin en ik volgen samen Nederlandse les.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de collega', 'Iemand met wie je bij dezelfde organisatie of in hetzelfde beroep werkt.', 'Mijn collega legt het nieuwe systeem uit.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de kennis', 'Iemand die je kent, maar met wie je meestal geen hechte vriendschap hebt.', 'Een kennis van mij woont in Rotterdam.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de partner', 'Iemand met wie je een vaste persoonlijke, romantische of zakelijke relatie hebt.', 'Mijn partner haalt de kinderen van school.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de echtgenoot', 'De man met wie iemand officieel getrouwd is.', 'Haar echtgenoot werkt in Amsterdam.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de echtgenote', 'De vrouw met wie iemand officieel getrouwd is.', 'Zijn echtgenote spreekt Nederlands en Duits.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de opa', 'De vader van je vader of moeder.', 'Mijn opa vertelt graag verhalen over vroeger.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de oma', 'De moeder van je vader of moeder.', 'Mijn oma belt elke zondag.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de oom', 'Een broer van je vader of moeder, of de mannelijke partner van een tante.', 'Mijn oom woont met zijn gezin in België.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de tante', 'Een zus van je vader of moeder, of de vrouwelijke partner van een oom.', 'Mijn tante komt morgen op bezoek.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de neef', 'Een zoon van je broer, zus, oom of tante; de precieze familieband blijkt uit de context.', 'Mijn neef van tien speelt graag voetbal.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de nicht', 'Een dochter van je broer, zus, oom of tante; de precieze familieband blijkt uit de context.', 'Mijn nicht studeert in Utrecht.', 'zelfstandig naamwoord', 'A1'),
  lexeme('welke', 'Een vraagwoord waarmee je uit meerdere personen of zaken een specifieke keuze vraagt.', 'Welke taal spreek je thuis?', 'vraagwoord', 'A1'),
  lexeme('wiens', 'Een vraagwoord waarmee je vraagt van wie iets is.', 'Wiens jas hangt aan de stoel?', 'vraagwoord', 'A1'),
  lexeme('waarvandaan', 'Een vraagwoord waarmee je naar de herkomst of het vertrekpunt vraagt.', 'Waarvandaan komt deze trein?', 'vraagwoord', 'A1'),
  lexeme('waarheen', 'Een vraagwoord waarmee je naar de bestemming of richting vraagt.', 'Waarheen reist u volgende week?', 'vraagwoord', 'A1'),
  lexeme('hoe oud', 'Een vraagcombinatie waarmee je naar de leeftijd van een persoon, dier of zaak vraagt.', 'Hoe oud is uw dochter?', 'vraaguitdrukking', 'A1'),
  lexeme('hoe lang', 'Een vraagcombinatie waarmee je naar duur, lengte of afstand vraagt.', 'Hoe lang woont u al in Nederland?', 'vraaguitdrukking', 'A1'),
  lexeme('hoe vaak', 'Een vraagcombinatie waarmee je naar de frequentie van een handeling vraagt.', 'Hoe vaak belt u uw familie?', 'vraaguitdrukking', 'A1'),
  lexeme('al', 'Geeft aan dat iets eerder dan verwacht is begonnen of op dit moment reeds het geval is.', 'Ik woon al drie jaar in Eindhoven.', 'bijwoord', 'A1'),
  lexeme('nog', 'Geeft aan dat een situatie voortduurt of dat iets extra of later mogelijk blijft.', 'Ik spreek nog niet vloeiend Nederlands.', 'bijwoord', 'A1'),
  lexeme('ook', 'Geeft aan dat dezelfde informatie eveneens voor iemand of iets anders geldt.', 'Mijn zus spreekt ook Engels.', 'bijwoord', 'A1'),
  lexeme('precies', 'Volledig juist, zonder afwijking of op exact dezelfde plaats of tijd.', 'De afspraak begint precies om negen uur.', 'bijwoord', 'A1'),
  lexeme('ongeveer', 'Niet exact, maar dicht bij een genoemde hoeveelheid, tijd of afstand.', 'De cursus duurt ongeveer zes maanden.', 'bijwoord', 'A1'),
  lexeme('invullen', 'Gevraagde gegevens in lege vakken van een formulier schrijven of typen.', 'Vul uw naam en adres bovenaan in.', 'werkwoord', 'A1'),
  lexeme('ondertekenen', 'Een document van je handtekening voorzien om akkoord of ontvangst te bevestigen.', 'U moet het contract onderaan ondertekenen.', 'werkwoord', 'A1'),
  lexeme('uitleggen', 'Informatie zo vertellen dat iemand de betekenis, reden of werkwijze kan begrijpen.', 'De docent legt de grammaticale regel rustig uit.', 'werkwoord', 'A1'),
  lexeme('vertellen', 'Mondeling informatie, een ervaring of een verhaal aan iemand geven.', 'Kun je iets over je familie vertellen?', 'werkwoord', 'A1'),
  lexeme('herhalen', 'Dezelfde woorden of handeling opnieuw zeggen of uitvoeren.', 'Wilt u de postcode nog een keer herhalen?', 'werkwoord', 'A1'),
  lexeme('bevestigen', 'Aangeven dat informatie, een afspraak of een keuze juist en definitief is.', 'Ik bevestig de afspraak per e-mail.', 'werkwoord', 'A1'),
  lexeme('controleren', 'Nauwkeurig nagaan of iets juist, volledig of in goede staat is.', 'Controleer uw adres voordat u het formulier verstuurt.', 'werkwoord', 'A1'),
  lexeme('verbeteren', 'Iets aanpassen zodat een fout verdwijnt of de kwaliteit hoger wordt.', 'De docent verbetert mijn uitspraak.', 'werkwoord', 'A1'),
  lexeme('vertalen', 'De betekenis van woorden of tekst in een andere taal weergeven.', 'Kun je deze zin naar het Nederlands vertalen?', 'werkwoord', 'A1'),
  lexeme('bedoelen', 'De betekenis of bedoeling hebben die je met woorden probeert over te brengen.', 'Wat bedoelt u met dit woord?', 'werkwoord', 'A1'),
  lexeme('herkennen', 'Weten wie of wat iemand of iets is doordat je het eerder hebt gezien, gehoord of geleerd.', 'Ik herken haar stem meteen.', 'werkwoord', 'A1'),
  lexeme('onthouden', 'Informatie in je geheugen bewaren zodat je die later nog weet.', 'Ik kan zijn telefoonnummer moeilijk onthouden.', 'werkwoord', 'A1'),
  lexeme('vergeten', 'Informatie niet meer weten of nalaten iets mee te nemen of te doen.', 'Ik ben mijn identiteitsbewijs vergeten.', 'werkwoord', 'A1'),
  lexeme('uitspreken', 'Een woord of klank met de stem vormen en hoorbaar zeggen.', 'Hoe moet ik deze achternaam uitspreken?', 'werkwoord', 'A1'),
  lexeme('noteren', 'Informatie kort opschrijven of digitaal vastleggen om die te bewaren.', 'Ik noteer uw naam en telefoonnummer.', 'werkwoord', 'A1'),
  lexeme('formeel aanspreken', 'Iemand beleefd benaderen met bijvoorbeeld u, meneer of mevrouw.', 'Bij een officiële afspraak spreek ik de medewerker formeel aan.', 'taalhandeling', 'A1'),
  lexeme('informeel aanspreken', 'Iemand op een vertrouwde manier benaderen met bijvoorbeeld jij of je.', 'Mijn collega en ik spreken elkaar informeel aan.', 'taalhandeling', 'A1'),
  lexeme('zich identificeren', 'Met naam of officieel document aantonen wie je bent.', 'Bij de balie moet u zich met uw paspoort identificeren.', 'taalhandeling', 'A1'),
  lexeme('persoonlijke informatie geven', 'Gegevens over jezelf noemen, zoals naam, adres, geboortedatum of telefoonnummer.', 'Aan de balie moet ik persoonlijke informatie geven.', 'taalhandeling', 'A1'),
  lexeme('een gesprek beginnen', 'De eerste begroeting, vraag of opmerking gebruiken om contact met iemand te starten.', 'Met Goedemorgen kan ik een gesprek beleefd beginnen.', 'taalhandeling', 'A1'),
  lexeme('een gesprek afsluiten', 'Met een passende zin duidelijk maken dat een gesprek eindigt.', 'Ik sluit het gesprek af met Tot ziens.', 'taalhandeling', 'A1'),
  lexeme('iemand welkom heten', 'Een persoon vriendelijk ontvangen en laten merken dat zijn of haar komst gewenst is.', 'De directeur heet de nieuwe cursisten welkom.', 'taalhandeling', 'A1'),
  lexeme('iemand feliciteren', 'Iemand gelukwensen met een verjaardag, succes of bijzondere gebeurtenis.', 'Wij feliciteren haar met haar nieuwe baan.', 'taalhandeling', 'A1'),
  lexeme('iemand bedanken', 'Waardering uitspreken voor hulp, tijd, aandacht of iets dat je hebt gekregen.', 'Ik bedank mijn buurvrouw voor het pakketje.', 'taalhandeling', 'A1'),
  lexeme('excuses aanbieden', 'Zeggen dat je spijt hebt van een fout, vertraging of ongemak.', 'Ik bied mijn excuses aan voor de late reactie.', 'taalhandeling', 'A1'),
  lexeme('om herhaling vragen', 'Iemand verzoeken dezelfde woorden opnieuw te zeggen.', 'Als ik iets niet versta, vraag ik om herhaling.', 'taalhandeling', 'A1'),
  lexeme('langzamer laten spreken', 'Iemand verzoeken het spreektempo te verlagen zodat je hem of haar beter kunt volgen.', 'Met Langzamer, alstublieft laat ik de medewerker langzamer spreken.', 'taalhandeling', 'A1'),
  lexeme('een woord laten spellen', 'Iemand vragen de letters van een woord één voor één te noemen.', 'Aan de telefoon laat ik de medewerker de straatnaam spellen.', 'taalhandeling', 'A1'),
  lexeme('een misverstand uitleggen', 'Duidelijk maken welke informatie verkeerd is begrepen en wat eigenlijk werd bedoeld.', 'Ik leg uit dat er een misverstand over de datum is.', 'taalhandeling', 'A1'),
  lexeme('een naam verkeerd uitspreken', 'De klanken van iemands naam niet op de juiste manier zeggen.', 'De receptionist spreekt mijn achternaam verkeerd uit.', 'taalhandeling', 'A1'),
  lexeme('een telefoonnummer doorgeven', 'De cijfers van een telefoonnummer aan iemand noemen of sturen.', 'Ik geef mijn nieuwe telefoonnummer aan de school door.', 'taalhandeling', 'A1'),
  lexeme('een bericht achterlaten', 'Informatie voor iemand noteren of inspreken wanneer die persoon niet direct bereikbaar is.', 'Ik laat een bericht achter voor de contactpersoon.', 'taalhandeling', 'A1'),
  lexeme('beschikbaar zijn', 'Vrij of aanwezig zijn om iets te doen, te gebruiken of af te spreken.', 'Ik ben vrijdagmiddag beschikbaar voor een afspraak.', 'vaste combinatie', 'A1'),
  lexeme('bereikbaar zijn', 'Via telefoon, e-mail of een andere route contact kunnen ontvangen.', 'De huisarts is buiten kantooruren alleen voor spoed bereikbaar.', 'vaste combinatie', 'A1'),
  lexeme('contact houden met', 'Regelmatig blijven communiceren met een persoon of organisatie.', 'Ik houd via videobellen contact met mijn familie.', 'vaste combinatie', 'A1'),
  lexeme('elkaar leren kennen', 'Door gesprekken en gezamenlijke ervaringen geleidelijk meer over elkaar te weten komen.', 'Tijdens de cursus leren de deelnemers elkaar kennen.', 'vaste combinatie', 'A1'),
  lexeme('uit hetzelfde land komen', 'Dezelfde nationale of geografische herkomst hebben.', 'Wij komen allebei uit hetzelfde land.', 'vaste combinatie', 'A1'),
  lexeme('een taal vloeiend spreken', 'Een taal gemakkelijk, vlot en met weinig onderbrekingen mondeling gebruiken.', 'Na jaren oefenen spreekt zij Nederlands vloeiend.', 'vaste combinatie', 'A1'),
  lexeme('een beetje Nederlands spreken', 'Het Nederlands beperkt kunnen gebruiken voor eenvoudige woorden en korte zinnen.', 'Ik spreek een beetje Nederlands, maar nog niet genoeg voor een vergadering.', 'vaste combinatie', 'A1'),
  lexeme('iets niet verstaan', 'De gesproken woorden niet goed kunnen horen of herkennen.', 'Door het lawaai versta ik de omroep niet.', 'vaste combinatie', 'A1'),

  // Reeds gevalideerde A1- en A2-kernwoorden uit eerdere versies, nu eveneens
  // ondergebracht in dezelfde centrale bron zodat er geen lexicale regressie ontstaat.
  lexeme('de opslag', 'Een ruimte of voorziening waar spullen tijdelijk worden bewaard.', 'Tijdens de verhuizing bewaren we onze meubels in de opslag.', 'zelfstandig naamwoord', 'A2'),
  lexeme('de schade', 'Nadeel of beschadiging waardoor iets minder goed of minder waardevol is.', 'De storm heeft veel schade aan het dak veroorzaakt.', 'zelfstandig naamwoord', 'A2'),
  lexeme('het huisnummer', 'Het nummer waarmee een huis in een straat wordt aangeduid.', 'Ons huisnummer is 24.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de postcode', 'Een combinatie van cijfers en letters die bij een gebied of adres hoort.', 'Wat is uw postcode?', 'zelfstandig naamwoord', 'A1'),
  lexeme('de woonplaats', 'De stad of het dorp waar iemand woont.', 'Mijn woonplaats is Waalre.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de nationaliteit', 'De officiële verbondenheid van een persoon met een land.', 'Wat is uw nationaliteit?', 'zelfstandig naamwoord', 'A1'),
  lexeme('de familie', 'Alle verwanten samen, ook buiten het huishouden, zoals ooms, tantes en grootouders.', 'Mijn familie woont in verschillende landen.', 'zelfstandig naamwoord', 'A1'),
  lexeme('het gezin', 'Ouders of verzorgers en kinderen die samen een huishouden vormen.', 'Ons gezin bestaat uit vier personen.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de ouder', 'Een vader, moeder of verzorger van een kind.', 'Elke ouder krijgt informatie van de school.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de vader', 'Een man die een kind heeft of verzorgt.', 'Mijn vader woont in Colombia.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de moeder', 'Een vrouw die een kind heeft of verzorgt.', 'Haar moeder werkt in een ziekenhuis.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de broer', 'Een jongen of man met dezelfde ouder of ouders als jij.', 'Mijn broer is ouder dan ik.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de zus', 'Een meisje of vrouw met dezelfde ouder of ouders als jij.', 'Mijn zus spreekt drie talen.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de man', 'Een volwassen persoon van het mannelijke geslacht; ook een huwelijkspartner.', 'De man wacht bij de ingang.', 'zelfstandig naamwoord', 'A1'),
  lexeme('de vrouw', 'Een volwassen persoon van het vrouwelijke geslacht; ook een huwelijkspartner.', 'De vrouw fietst naar haar werk.', 'zelfstandig naamwoord', 'A1'),
  lexeme('het kind', 'Een jonge persoon; ook een zoon of dochter van iemand.', 'Het kind speelt buiten.', 'zelfstandig naamwoord', 'A1'),
  lexeme('heten', 'Een bepaalde naam hebben.', 'Ik heet Sofia.', 'werkwoord', 'A1'),
  lexeme('zijn', 'Een identiteit, eigenschap, plaats of toestand uitdrukken.', 'Wij zijn vandaag thuis.', 'werkwoord', 'A1'),
  lexeme('hebben', 'Iets bezitten, ontvangen of ervaren.', 'Ik heb een afspraak.', 'werkwoord', 'A1'),
  lexeme('komen', 'Zich naar een plaats bewegen of uit een plaats afkomstig zijn.', 'Ik kom uit Colombia.', 'werkwoord', 'A1'),
  lexeme('spellen', 'De letters van een woord één voor één noemen.', 'Kunt u uw naam spellen?', 'werkwoord', 'A1'),
  lexeme('vragen', 'Iets zeggen om informatie, hulp of toestemming te krijgen.', 'Ik vraag de docent om hulp.', 'werkwoord', 'A1'),
  lexeme('antwoorden', 'Reageren op een vraag of bericht.', 'Zij antwoordt rustig.', 'werkwoord', 'A1'),
  lexeme('begroeten', 'Iemand vriendelijk aanspreken wanneer je die persoon ontmoet.', 'Wij begroeten de nieuwe buren.', 'werkwoord', 'A1'),
  lexeme('voorstellen', 'Vertellen wie jezelf of een andere persoon is.', 'Ik stel mezelf aan de groep voor.', 'werkwoord', 'A1'),
  lexeme('kennismaken', 'Iemand voor het eerst ontmoeten en informatie uitwisselen.', 'Morgen maken we kennis met het team.', 'werkwoord', 'A1'),
  lexeme('ontmoeten', 'Bij iemand komen en die persoon zien of spreken.', 'Ik ontmoet mijn collega bij het station.', 'werkwoord', 'A1'),
  lexeme('bellen', 'Telefonisch contact met iemand opnemen.', 'Ik bel vanmiddag de huisarts.', 'werkwoord', 'A1'),
  lexeme('kennen', 'Weten wie of wat iemand of iets is door eerdere ervaring.', 'Ken je onze nieuwe docent?', 'werkwoord', 'A1'),
  lexeme('buitenlands', 'Afkomstig uit of verbonden met een ander land.', 'Zij heeft een buitenlands diploma.', 'bijvoeglijk woord', 'A1'),
  lexeme('getrouwd', 'Door een huwelijk officieel met iemand verbonden.', 'Mijn zus is getrouwd.', 'bijvoeglijk woord', 'A1'),
  lexeme('alleenstaand', 'Niet getrouwd en zonder vaste partner in het huishouden.', 'Hij is alleenstaand.', 'bijvoeglijk woord', 'A1'),
  lexeme('jong', 'Nog niet oud; met een lage leeftijd.', 'De kinderen zijn nog jong.', 'bijvoeglijk woord', 'A1'),
  lexeme('oud', 'Al lang bestaand of met een hoge leeftijd.', 'Hoe oud ben je?', 'bijvoeglijk woord', 'A1'),
  lexeme('vriendelijk', 'Aardig, beleefd en prettig tegenover andere mensen.', 'De buurvrouw is erg vriendelijk.', 'bijvoeglijk woord', 'A1'),
  lexeme('nieuw', 'Nog niet lang bestaand, gekocht of bekend.', 'Wij hebben een nieuwe buurman.', 'bijvoeglijk woord', 'A1'),
  lexeme('hetzelfde', 'Niet verschillend; precies gelijk aan iets anders.', 'Wij hebben hetzelfde adres.', 'bijvoeglijk woord', 'A1'),
  lexeme('anders', 'Niet hetzelfde of op een andere manier.', 'Vandaag gaat het anders.', 'bijwoord', 'A1'),
  lexeme('samen', 'Met één of meer andere mensen.', 'Wij leren samen Nederlands.', 'bijwoord', 'A1'),
  lexeme('alleen', 'Zonder andere mensen of zonder hulp.', 'Ik woon niet alleen.', 'bijwoord', 'A1'),
  lexeme('aangenaam kennis te maken', 'Een beleefde reactie wanneer je iemand voor het eerst ontmoet.', 'Aangenaam kennis te maken, ik ben Lina.', 'uitdrukking', 'A1'),
  lexeme('het gaat goed', 'Een positief antwoord op de vraag hoe het gaat.', 'Dank je, het gaat goed.', 'uitdrukking', 'A1'),

  ...a1LexiconEntries,
  ...a2LexiconEntries,
];

const lexiconByKey = new Map();
for (const entry of centralLexiconEntries) {
  const key = normalizeLexeme(entry.term);
  if (!key) throw new Error('Lege lexiconterm gevonden.');
  if (lexiconByKey.has(key)) throw new Error(`Dubbele lexiconterm: ${entry.term}`);
  lexiconByKey.set(key, Object.freeze({ ...entry, key }));
}

export const centralLexicon = lexiconByKey;

export function findLexiconEntry(term) {
  return centralLexicon.get(normalizeLexeme(term)) || null;
}
