// Original question-system content for the Dutch-learning application.
// The examples are written for this project and organised from A1 to B2; C1-C2 extensions live in c1-c2-language-systems.js.

export const questionTopics = [
  {
    id: 'ja-nee-vragen', level: 'A1', title: 'Ja/nee-vragen',
    summary: 'Een ja/nee-vraag begint meestal met de persoonsvorm. Het onderwerp komt direct daarna.',
    rule: 'persoonsvorm + onderwerp + rest + ?',
    examples: ['Woon je in Nederland?', 'Heeft zij kinderen?', 'Kunnen jullie morgen komen?', 'Is de winkel nog open?'],
    connections: ['Inversie', 'Persoonsvorm', 'Tegenwoordige tijd'],
    sections: [
      { title: 'Eenvoudige vragen', items: ['Werk je vandaag?', 'Komt de bus op tijd?', 'Hebben jullie een afspraak?'] },
      { title: 'Met een modaal werkwoord', items: ['Kun je me helpen?', 'Mag ik hier zitten?', 'Moeten we reserveren?'] },
      { title: 'Korte antwoorden', items: ['Ja, dat klopt. · Nee, helaas niet.', 'Ja, ik werk vandaag. · Nee, ik ben vrij.'] },
    ],
    contrasts: ['Je woont in Eindhoven. ↔ Woon je in Eindhoven?', 'Zij kan komen. ↔ Kan zij komen?'],
    mistakes: ['Niet: Je woont in Eindhoven? als neutrale leervorm. Gebruik: Woon je in Eindhoven?', 'Vergeet het vraagteken niet.'],
  },
  {
    id: 'basis-vraagwoorden', level: 'A1', title: 'Wie, wat, waar, wanneer, waarom en hoe',
    summary: 'Een open vraag begint met een vraagwoord. Daarna volgt meestal de persoonsvorm en vervolgens het onderwerp.',
    rule: 'vraagwoord + persoonsvorm + onderwerp + rest + ?',
    examples: ['Wie is dat?', 'Wat eet je graag?', 'Waar woon je?', 'Wanneer begint de les?', 'Waarom leer je Nederlands?', 'Hoe gaat het?'],
    connections: ['Woordvolgorde', 'Informatie vragen', 'Gesprekken'],
    sections: [
      { title: 'Persoon en zaak', items: ['wie = persoon', 'wat = ding, activiteit of idee', 'Wie belt de dokter? · Wat bestel je?'] },
      { title: 'Plaats en tijd', items: ['waar = plaats', 'wanneer = tijdstip of periode', 'Waar is de ingang? · Wanneer vertrek je?'] },
      { title: 'Reden en manier', items: ['waarom = reden', 'hoe = manier of toestand', 'Waarom ben je laat? · Hoe kom je naar school?'] },
    ],
    contrasts: ['Wie helpt jou? ↔ Wie help jij?', 'Wat gebeurt er? ↔ Wat doe je?'],
    mistakes: ['Niet: Waar je woont? als directe hoofdvraag. Gebruik: Waar woon je?'],
  },
  {
    id: 'hoe-combinaties', level: 'A1', title: 'Hoe oud, hoe laat, hoe lang, hoe vaak en hoeveel',
    summary: 'Met hoe vorm je precieze vragen over leeftijd, tijd, duur, frequentie, afstand, hoeveelheid en manier.',
    rule: 'hoe + eigenschap/maat + persoonsvorm + onderwerp + rest?',
    examples: ['Hoe oud ben je?', 'Hoe laat begint de film?', 'Hoe lang duurt de reis?', 'Hoe vaak sport je?', 'Hoeveel appels wilt u?'],
    connections: ['Getallen', 'Tijd', 'Hoeveelheid'],
    sections: [
      { title: 'Tijd en duur', items: ['Hoe laat? = kloktijd', 'Hoe lang? = duur of lengte', 'Hoe lang woon je hier?'] },
      { title: 'Frequentie en afstand', items: ['Hoe vaak? = frequentie', 'Hoe ver? = afstand', 'Hoe vaak gaat de trein? · Hoe ver is het lopen?'] },
      { title: 'Hoeveelheid', items: ['hoeveel + niet-telbaar of meervoud', 'Hoeveel water drink je? · Hoeveel kinderen zijn er?'] },
    ],
    contrasts: ['Hoe lang is de tafel? ↔ Hoe lang duurt de les?', 'Hoeveel brood? ↔ Hoeveel broden?'],
    mistakes: ['Niet: Hoe veel kost het? in de gewone betekenis. Schrijf: Hoeveel kost het?'],
  },
  {
    id: 'welk-welke-wat-voor', level: 'A2', title: 'Welk, welke en wat voor',
    summary: 'Welk en welke vragen naar een keuze binnen een bekende groep. Wat voor vraagt naar soort of karakter.',
    rule: 'welk + het-woord · welke + de-woord/meervoud · wat voor + zelfstandig naamwoord',
    examples: ['Welk boek lees je?', 'Welke jas wil je passen?', 'Welke schoenen zijn van jou?', 'Wat voor werk doe je?'],
    connections: ['De en het', 'Bijvoeglijk naamwoord', 'Kiezen'],
    sections: [
      { title: 'Welk of welke', items: ['het huis → welk huis?', 'de winkel → welke winkel?', 'de kinderen → welke kinderen?'] },
      { title: 'Wat voor', items: ['Wat voor muziek luister je?', 'Wat voor woning zoek je?', 'Wat voor persoon is zij?'] },
      { title: 'Zelfstandig gebruikt', items: ['Welke wil je? · Welke bedoel je?', 'Welk exemplaar is goedkoper?'] },
    ],
    contrasts: ['Welke auto koop je? = keuze ↔ Wat voor auto zoek je? = soort', 'Wat is je werk? ↔ Wat voor werk doe je?'],
    mistakes: ['Niet: Welke boek? Gebruik: Welk boek?', 'Na wat voor komt geen een: Wat voor fiets heb je?'],
  },
  {
    id: 'scheidbare-vragen', level: 'A2', title: 'Vragen met scheidbare werkwoorden',
    summary: 'In een directe hoofdvraag staat de persoonsvorm vooraan of na het vraagwoord. Het losse deel staat meestal achteraan.',
    rule: 'vraagwoord + werkwoordstam + onderwerp + rest + los deel?',
    examples: ['Hoe laat sta je op?', 'Wanneer komt de trein aan?', 'Wie haalt de kinderen op?', 'Bel je mij vanavond terug?'],
    connections: ['Scheidbare werkwoorden', 'Inversie', 'Zinspositie'],
    sections: [
      { title: 'Open vraag', items: ['Wanneer vul je het formulier in?', 'Waar stap je uit?', 'Waarom zet je de verwarming aan?'] },
      { title: 'Ja/nee-vraag', items: ['Ruim je de kamer op?', 'Neem je je paspoort mee?', 'Schrijf je het adres op?'] },
      { title: 'Met modaal werkwoord', items: ['Wanneer moet je opstaan?', 'Kun je mij terugbellen?', 'Waar wil je uitstappen?'] },
    ],
    contrasts: ['Wanneer bel je hem op? ↔ Wanneer moet je hem opbellen?', 'Waar stap je uit? ↔ Waar ben je uitgestapt?'],
    mistakes: ['Niet: Wanneer opbel je hem? Gebruik: Wanneer bel je hem op?'],
  },
  {
    id: 'vragen-verleden', level: 'A2', title: 'Vragen in verleden tijd en perfectum',
    summary: 'Gebruik de verleden tijd voor een afgeronde periode of verhaalcontext en het perfectum vaak voor een gebeurtenis met relevantie nu.',
    rule: 'vraagwoord + persoonsvorm verleden + onderwerp …? · heb/ben + onderwerp + voltooid deelwoord?',
    examples: ['Waar woonde je vroeger?', 'Wanneer begon de cursus?', 'Wat heb je gisteren gedaan?', 'Waarom ben je verhuisd?'],
    connections: ['Imperfectum', 'Perfectum', 'Hebben of zijn'],
    sections: [
      { title: 'Onvoltooid verleden tijd', items: ['Hoe was je vakantie?', 'Waar werkte je toen?', 'Wie belde je gisteren?'] },
      { title: 'Perfectum', items: ['Heb je al gegeten?', 'Welke film heb je gezien?', 'Wanneer is de trein vertrokken?'] },
      { title: 'Met een modaal werkwoord', items: ['Waarom moest je wachten?', 'Heb je het formulier kunnen invullen?'] },
    ],
    contrasts: ['Wat deed je toen? ↔ Wat heb je gedaan?', 'Wanneer vertrok hij? ↔ Is hij al vertrokken?'],
    mistakes: ['Niet: Waarom je bent verhuisd? Gebruik: Waarom ben je verhuisd?'],
  },
  {
    id: 'beleefde-vragen', level: 'A2', title: 'Beleefde en formele vragen',
    summary: 'Met kunt, zou, mag en wilt maakt de spreker een verzoek minder direct. De keuze hangt af van situatie en register.',
    rule: 'kunt/wilt/zou/mag + u/jij + rest + infinitief?',
    examples: ['Kunt u mij helpen?', 'Zou u dat kunnen herhalen?', 'Mag ik iets vragen?', 'Wilt u hier tekenen?'],
    connections: ['Register', 'Modale werkwoorden', 'Verzoeken'],
    sections: [
      { title: 'Neutraal beleefd', items: ['Kunt u mij vertellen waar de balie is?', 'Wilt u even wachten?', 'Mag ik uw naam noteren?'] },
      { title: 'Zachter en voorzichtiger', items: ['Zou u het formulier willen controleren?', 'Zou ik een andere afspraak kunnen maken?'] },
      { title: 'Informeel', items: ['Kun je me even helpen?', 'Wil je de deur dichtdoen?', 'Mag ik je iets vragen?'] },
    ],
    contrasts: ['Geef me de rekening. ↔ Kunt u de rekening brengen?', 'Kun je…? ↔ Zou je misschien… kunnen?'],
    mistakes: ['Kunt u…? is breed bruikbaar en klinkt in Nederlandse schrijftaal vaak verzorgder; Kan u…? is ook correct en klinkt in Nederland informeler.'],
  },
  {
    id: 'indirecte-vragen', level: 'B1', title: 'Indirecte vragen met of en een vraagwoord',
    summary: 'In een indirecte vraag staat de persoonsvorm niet direct na het vraagwoord. De werkwoorden staan zoals in een bijzin aan het einde.',
    rule: 'hoofdzin + vraagwoord/of + onderwerp + rest + werkwoord(en)',
    examples: ['Weet je waar de halte is?', 'Kun je zeggen wanneer de winkel sluit?', 'Ik vraag me af of hij komt.', 'Weet u waarom de trein vertraging heeft?'],
    connections: ['Bijzin', 'Of', 'Woordvolgorde'],
    sections: [
      { title: 'Open indirecte vraag', items: ['Weet je hoe laat het is?', 'Kunt u uitleggen waarom dit nodig is?', 'Ik weet niet waar zij woont.'] },
      { title: 'Indirecte ja/nee-vraag', items: ['Ik weet niet of de winkel open is.', 'Kun je controleren of het formulier compleet is?'] },
      { title: 'Meerdere werkwoorden', items: ['Weet je waar ik moet uitstappen?', 'Kun je zeggen wanneer ik teruggebeld word?'] },
    ],
    contrasts: ['Waar is de halte? ↔ Weet je waar de halte is?', 'Komt hij? ↔ Ik vraag me af of hij komt.'],
    mistakes: ['Niet: Weet je waar is de halte? Gebruik: Weet je waar de halte is?'],
  },
  {
    id: 'waar-voorzetsel', level: 'B1', title: 'Waar + voorzetsel',
    summary: 'Bij zaken en ideeën kan een vraagwoordelijk bijwoord het voorzetsel en wat combineren: waarmee, waarop, waarover, waarvoor enzovoort.',
    rule: 'waar + voorzetselbijwoord → waarmee, waarop, waarover, waarvoor…',
    examples: ['Waarmee schrijf je?', 'Waarop wacht je?', 'Waarover praten jullie?', 'Waarvoor gebruik je dit?'],
    connections: ['Er + voorzetsel', 'Vaste voorzetsels', 'Voornaamwoordelijk bijwoord'],
    sections: [
      { title: 'Vraag naar een zaak', items: ['met wat → waarmee?', 'op wat → waarop?', 'over wat → waarover?', 'voor wat → waarvoor?'] },
      { title: 'Antwoord met daar of er', items: ['Waarmee schrijf je? Daarmee / ermee.', 'Waarop wacht je? Daarop / erop.', 'Waarover gaat het? Daarover / erover.'] },
      { title: 'Splitsing', items: ['Waar denk je aan? = Waaraan denk je?', 'Waar werk je mee? = Waarmee werk je?', 'Waar hebben jullie het over? = Waarover hebben jullie het?'] },
    ],
    contrasts: ['Waarmee? ↔ met wie?', 'Waarover? ↔ over wie?', 'Waarop? ↔ op wie?'],
    mistakes: ['Niet: Met wat schrijf je? is mogelijk in spreektaal, maar waarmee is de compacte standaardvorm voor een zaak.'],
  },
  {
    id: 'waar-daar-er-hier', level: 'B1', title: 'Waar, daar, er en hier + voorzetsel',
    summary: 'Waar vraagt, daar wijst nadrukkelijk terug, er verwijst neutraal en hier verwijst naar iets dichtbij of naar de huidige tekst/situatie.',
    rule: 'waarop? → daarop / erop / hierop',
    examples: ['Waarop klik ik? Klik hierop.', 'Dat plan? Daarover praten we morgen.', 'De uitslag? Ik wacht erop.', 'Hiermee open je de deur.'],
    connections: ['Verwijzen', 'Nadruk', 'Woordvolgorde'],
    sections: [
      { title: 'Vier functies', items: ['waar- = vraag of relatief verband', 'daar- = nadrukkelijke verwijzing', 'er- = neutrale verwijzing', 'hier- = dichtbij of in deze context'] },
      { title: 'Aaneen of gesplitst', items: ['Ik wacht erop. · Ik wacht er al lang op.', 'Waarmee betaal je? · Waar betaal je mee?', 'Daarover heb ik niets gezegd. · Daar heb ik niets over gezegd.'] },
      { title: 'Met een bijzin', items: ['Ik reken erop dat je komt.', 'Zij zorgt ervoor dat alles klaarstaat.', 'Het hangt ervan af of hij tijd heeft.'] },
    ],
    contrasts: ['Daarmee = met dat specifieke ding ↔ ermee = neutrale terugverwijzing', 'Hierover = over dit onderwerp ↔ erover = over het genoemde onderwerp'],
    mistakes: ['Schrijf de delen aaneen als ze direct naast elkaar één zinsdeel vormen: waarmee, daarover, erop.'],
  },
  {
    id: 'personen-en-zaken', level: 'B1', title: 'Personen en zaken: met wie of waarmee?',
    summary: 'Bij personen zijn vormen met wie duidelijk en vooral in zakelijke schrijftaal vaak de beste keuze. In informele spreektaal komen waar-vormen voor personen ook voor.',
    rule: 'zaak: waarmee/waarover · persoon: met wie/over wie',
    examples: ['Waarmee open je de deur?', 'Met wie ga je op vakantie?', 'Waarover praten jullie?', 'Over wie praten jullie?'],
    connections: ['Register', 'Personen', 'Voorzetselvoorwerp'],
    sections: [
      { title: 'Duidelijk onderscheid', items: ['op wie = persoon', 'waarop = zaak of idee', 'aan wie = persoon', 'waaraan = zaak, taak of idee'] },
      { title: 'Informeel taalgebruik', items: ['De collega waarmee ik werk is algemeen in spreektaal.', 'De collega met wie ik werk is in verzorgde zakelijke tekst vaak duidelijker.'] },
      { title: 'Antwoorden', items: ['Ik ga met mijn broer. · Ik ga met hem.', 'Ik werk met dit programma. · Ik werk ermee.'] },
    ],
    contrasts: ['Met wie werk je? ↔ Waarmee werk je?', 'Aan wie denk je? ↔ Waaraan denk je?', 'Op wie wacht je? ↔ Waarop wacht je?'],
    mistakes: ['Gebruik niet er + persoonlijk voornaamwoord: niet erop hem, maar op hem.'],
  },
  {
    id: 'richting-en-oorsprong', level: 'B1', title: 'Waarheen, waarnaartoe en waarvandaan',
    summary: 'Richting en oorsprong hebben eigen vraagvormen. Waarheen en waarnaartoe vragen naar een bestemming; waarvandaan naar een oorsprong.',
    rule: 'waarheen / waarnaartoe = bestemming · waarvandaan = oorsprong',
    examples: ['Waar ga je naartoe?', 'Waarheen vertrekt de trein?', 'Waar kom je vandaan?', 'Waarvanaf kun je de stad zien?'],
    connections: ['Beweging', 'Richting', 'Plaatsvoorzetsels'],
    sections: [
      { title: 'Bestemming', items: ['Waar ga je heen?', 'Waar ga je naartoe?', 'Waarheen verhuist zij?'] },
      { title: 'Oorsprong', items: ['Waar kom je vandaan?', 'Waarvandaan vertrekt de bus?', 'Waaruit heb je dat afgeleid?'] },
      { title: 'Antwoorden', items: ['daarheen / daarnaartoe / ernaartoe', 'daarvandaan / ervandaan', 'daaruit / eruit'] },
    ],
    contrasts: ['Waar ben je? = positie ↔ Waar ga je naartoe? = richting', 'Waar kom je vandaan? = oorsprong ↔ Waar woon je? = locatie'],
    mistakes: ['Niet overal is naar waar de neutrale standaardvorm in Nederland; gebruik waarheen of waar … naartoe.'],
  },
  {
    id: 'relatieve-waarvormen', level: 'B2', title: 'Relatieve vormen: waarmee, waarin en waarop',
    summary: 'Waar-vormen kunnen ook een betrekkelijke bijzin verbinden met een eerder genoemd zelfstandig naamwoord.',
    rule: 'zelfstandig naamwoord + waar + voorzetsel + bijzin',
    examples: ['De pen waarmee ik schrijf ligt hier.', 'Het huis waarin zij woont is oud.', 'De dag waarop we vertrokken was zonnig.', 'Het onderwerp waarover hij sprak was ingewikkeld.'],
    connections: ['Betrekkelijke bijzin', 'Verwijzen', 'Tekstsamenhang'],
    sections: [
      { title: 'Zaak, plaats en tijd', items: ['het instrument waarmee…', 'de ruimte waarin…', 'het moment waarop…', 'het argument waarop…'] },
      { title: 'Met personen', items: ['de collega met wie ik werk', 'de docent aan wie ik de vraag stelde', 'in informele taal: de collega waarmee ik werk'] },
      { title: 'Complexere vormen', items: ['de basis van waaruit we werken', 'de plek waarvandaan de bus vertrekt', 'de afdeling waartoe hij toegang heeft'] },
    ],
    contrasts: ['de dag dat we vertrokken ↔ de dag waarop we vertrokken', 'de collega waarmee… ↔ de collega met wie…'],
    mistakes: ['Na toegang hebben tot wordt tot in een waar-vorm toe: de afdeling waar hij toegang toe heeft.'],
  },
  {
    id: 'vragen-nuanceren', level: 'B2', title: 'Vragen nuanceren in gesprek en tekst',
    summary: 'Op B2-niveau stuur je toon en bedoeling met inleidingen, modaliteit, intonatie en voorzichtig taalgebruik.',
    rule: 'inleiding + modale vorm + inhoudsvraag',
    examples: ['Zou je kunnen toelichten wat je precies bedoelt?', 'In hoeverre is deze oplossing haalbaar?', 'Wat zou er gebeuren als we niets veranderen?', 'Mag ik vragen waarop deze conclusie is gebaseerd?'],
    connections: ['Register', 'Argumentatie', 'Professionele communicatie'],
    sections: [
      { title: 'Voorzichtig informeren', items: ['Mag ik vragen…?', 'Zou u kunnen aangeven…?', 'Kunt u toelichten in hoeverre…?'] },
      { title: 'Aannames controleren', items: ['Begrijp ik goed dat…?', 'Klopt het dat…?', 'Bedoel je daarmee dat…?'] },
      { title: 'Kritisch en analytisch', items: ['Waaruit blijkt dat?', 'Waarop is die aanname gebaseerd?', 'Welke gevolgen zou dit kunnen hebben?'] },
    ],
    contrasts: ['Waarom heb je dat gedaan? ↔ Kun je toelichten waarom je daarvoor hebt gekozen?', 'Is dit fout? ↔ In hoeverre wijkt dit af van de afspraak?'],
    mistakes: ['Een lange beleefde inleiding helpt alleen als de kernvraag duidelijk blijft.'],
  },
];

export const pronominalAdverbs = [
  { preposition: 'aan', question: 'waaraan', demonstrative: 'daaraan', reference: 'eraan', near: 'hieraan', person: 'aan wie', meaning: 'doel, contact of gedachte', questionExample: 'Waaraan denk je?', answerExample: 'Ik denk eraan.', splitExample: 'Waar denk je vaak aan?', level: 'B1' },
  { preposition: 'achter', question: 'waarachter', demonstrative: 'daarachter', reference: 'erachter', near: 'hierachter', person: 'achter wie', meaning: 'positie achter iets', questionExample: 'Waarachter zit de kat?', answerExample: 'De kat zit erachter.', splitExample: 'Waar zit de kat achter?', level: 'B1' },
  { preposition: 'bij', question: 'waarbij', demonstrative: 'daarbij', reference: 'erbij', near: 'hierbij', person: 'bij wie', meaning: 'nabijheid, betrokkenheid of omstandigheid', questionExample: 'Waarbij heb je hulp nodig?', answerExample: 'Ik heb er hulp bij nodig.', splitExample: 'Waar heb je hulp bij nodig?', level: 'B1' },
  { preposition: 'boven', question: 'waarboven', demonstrative: 'daarboven', reference: 'erboven', near: 'hierboven', person: 'boven wie', meaning: 'positie hoger dan iets', questionExample: 'Waarboven hangt de lamp?', answerExample: 'De lamp hangt erboven.', splitExample: 'Waar hangt de lamp boven?', level: 'B1' },
  { preposition: 'door', question: 'waardoor', demonstrative: 'daardoor', reference: 'erdoor', near: 'hierdoor', person: 'door wie', meaning: 'oorzaak, middel of route', questionExample: 'Waardoor ontstond de vertraging?', answerExample: 'Daardoor kwam ik te laat.', splitExample: 'Waar is dat door gekomen?', level: 'B1' },
  { preposition: 'in', question: 'waarin', demonstrative: 'daarin', reference: 'erin', near: 'hierin', person: 'in wie', meaning: 'binnenruimte, inhoud of onderwerp', questionExample: 'Waarin zit het verschil?', answerExample: 'Daarin zit het verschil.', splitExample: 'Waar zit het verschil in?', level: 'B1' },
  { preposition: 'langs', question: 'waarlangs', demonstrative: 'daarlangs', reference: 'erlangs', near: 'hierlangs', person: 'langs wie', meaning: 'route langs iets', questionExample: 'Waarlangs loopt de route?', answerExample: 'De route loopt hierlangs.', splitExample: 'Waar loopt de route langs?', level: 'B1' },
  { preposition: 'met → mee', question: 'waarmee', demonstrative: 'daarmee', reference: 'ermee', near: 'hiermee', person: 'met wie', meaning: 'middel, instrument of gezelschap', questionExample: 'Waarmee betaal je?', answerExample: 'Ik betaal ermee.', splitExample: 'Waar betaal je mee?', level: 'B1' },
  { preposition: 'omheen', question: 'waaromheen', demonstrative: 'daaromheen', reference: 'eromheen', near: 'hieromheen', person: 'om wie heen', meaning: 'positie of beweging rond iets', questionExample: 'Waaromheen staat het hek?', answerExample: 'Het hek staat eromheen.', splitExample: 'Waar staat het hek omheen?', level: 'B2' },
  { preposition: 'naar', question: 'waarnaar', demonstrative: 'daarnaar', reference: 'ernaar', near: 'hiernaar', person: 'naar wie', meaning: 'richting, waarneming of streven', questionExample: 'Waarnaar zoek je?', answerExample: 'Ik zoek ernaar.', splitExample: 'Waar zoek je naar?', level: 'B1' },
  { preposition: 'onder', question: 'waaronder', demonstrative: 'daaronder', reference: 'eronder', near: 'hieronder', person: 'onder wie', meaning: 'positie of opgenomen categorie', questionExample: 'Waaronder valt deze regeling?', answerExample: 'Het valt daaronder.', splitExample: 'Waar valt deze regeling onder?', level: 'B1' },
  { preposition: 'op', question: 'waarop', demonstrative: 'daarop', reference: 'erop', near: 'hierop', person: 'op wie', meaning: 'oppervlak, doel, reactie of verwachting', questionExample: 'Waarop wacht je?', answerExample: 'Ik wacht erop.', splitExample: 'Waar wacht je op?', level: 'B1' },
  { preposition: 'over', question: 'waarover', demonstrative: 'daarover', reference: 'erover', near: 'hierover', person: 'over wie', meaning: 'onderwerp, beweging of overschrijding', questionExample: 'Waarover praten jullie?', answerExample: 'We praten erover.', splitExample: 'Waar praten jullie over?', level: 'B1' },
  { preposition: 'tegen', question: 'waartegen', demonstrative: 'daartegen', reference: 'ertegen', near: 'hiertegen', person: 'tegen wie', meaning: 'contact, verzet of bescherming', questionExample: 'Waartegen maak je bezwaar?', answerExample: 'Ik maak ertegen bezwaar.', splitExample: 'Waar maak je bezwaar tegen?', level: 'B1' },
  { preposition: 'tot → toe', question: 'waartoe', demonstrative: 'daartoe', reference: 'ertoe', near: 'hiertoe', person: 'tot wie', meaning: 'doel, gevolg of toegang', questionExample: 'Waartoe dient deze knop?', answerExample: 'Deze knop dient ertoe de machine te stoppen.', splitExample: 'Waar dient deze knop toe?', level: 'B2' },
  { preposition: 'tussen', question: 'waartussen', demonstrative: 'daartussen', reference: 'ertussen', near: 'hiertussen', person: 'tussen wie', meaning: 'positie of relatie tussen elementen', questionExample: 'Waartussen moet ik kiezen?', answerExample: 'Ik kan er moeilijk tussen kiezen.', splitExample: 'Waar moet ik tussen kiezen?', level: 'B1' },
  { preposition: 'uit', question: 'waaruit', demonstrative: 'daaruit', reference: 'eruit', near: 'hieruit', person: 'uit wie', meaning: 'oorsprong, materiaal of conclusie', questionExample: 'Waaruit blijkt dat?', answerExample: 'Dat blijkt hieruit.', splitExample: 'Waar blijkt dat uit?', level: 'B1' },
  { preposition: 'van', question: 'waarvan', demonstrative: 'daarvan', reference: 'ervan', near: 'hiervan', person: 'van wie', meaning: 'bezit, bron, oorzaak of onderwerp', questionExample: 'Waarvan hangt het af?', answerExample: 'Het hangt ervan af.', splitExample: 'Waar hangt het van af?', level: 'B1' },
  { preposition: 'voor', question: 'waarvoor', demonstrative: 'daarvoor', reference: 'ervoor', near: 'hiervoor', person: 'voor wie', meaning: 'doel, bestemming, reden of voordeel', questionExample: 'Waarvoor gebruik je dit?', answerExample: 'Ik gebruik het hiervoor.', splitExample: 'Waar gebruik je dit voor?', level: 'B1' },
  { preposition: 'vanaf', question: 'waarvanaf', demonstrative: 'daarvanaf', reference: 'ervanaf', near: 'hiervanaf', person: 'vanaf wie', meaning: 'beginpunt of vertrekpunt', questionExample: 'Waarvanaf heb je het beste uitzicht?', answerExample: 'Hiervanaf zie je de stad.', splitExample: 'Waar heb je het beste uitzicht vanaf?', level: 'B2' },
  { preposition: 'vandaan', question: 'waarvandaan', demonstrative: 'daarvandaan', reference: 'ervandaan', near: 'hiervandaan', person: 'van wie', meaning: 'oorsprong of vertrekplaats', questionExample: 'Waarvandaan vertrekt de bus?', answerExample: 'De bus vertrekt hiervandaan.', splitExample: 'Waar vertrekt de bus vandaan?', level: 'B1' },
  { preposition: 'naartoe / heen', question: 'waarnaartoe / waarheen', demonstrative: 'daarnaartoe / daarheen', reference: 'ernaartoe / erheen', near: 'hiernaartoe / hierheen', person: 'naar wie', meaning: 'bestemming of richting', questionExample: 'Waar ga je naartoe?', answerExample: 'Ik ga ernaartoe.', splitExample: 'Waar ga je heen?', level: 'B1' },
];

export const questionPractice = [
  { id: 'q1', topic: 'ja-nee-vragen', level: 'A1', prompt: 'Maak een ja/nee-vraag van: “Je woont in Waalre.”', options: ['Woon je in Waalre?', 'Waar je woont in Waalre?', 'Je woont waar in Waalre?'], answer: 0, explanation: 'Een ja/nee-vraag begint met de persoonsvorm: Woon + je.', audio: 'Woon je in Waalre?' },
  { id: 'q2', topic: 'hoe-combinaties', level: 'A1', prompt: 'Je wilt de kloktijd weten.', options: ['Hoe lang begint de les?', 'Hoe laat begint de les?', 'Wanneer lang begint de les?'], answer: 1, explanation: 'Hoe laat vraagt naar een kloktijd.', audio: 'Hoe laat begint de les?' },
  { id: 'q3', topic: 'welk-welke-wat-voor', level: 'A2', prompt: 'Kies de vraag bij “het boek”.', options: ['Welke boek lees je?', 'Welk boek lees je?', 'Wat voor een boek lees je?'], answer: 1, explanation: 'Boek is een het-woord, dus: welk boek.', audio: 'Welk boek lees je?' },
  { id: 'q4', topic: 'beleefde-vragen', level: 'A2', prompt: 'Vraag beleefd of iemand de zin kan herhalen.', options: ['Herhaal de zin.', 'Zou u de zin kunnen herhalen?', 'U herhaalt de zin?'], answer: 1, explanation: 'Zou u … kunnen is een zachte, beleefde vraag.', audio: 'Zou u de zin kunnen herhalen?' },
  { id: 'q5', topic: 'waar-voorzetsel', level: 'B1', prompt: 'Je vraagt naar het instrument waarmee iemand schrijft.', options: ['Met wie schrijf je?', 'Waarmee schrijf je?', 'Waar schrijf je?'], answer: 1, explanation: 'Voor een zaak combineer je waar + mee: waarmee.', audio: 'Waarmee schrijf je?' },
  { id: 'q6', topic: 'indirecte-vragen', level: 'B1', prompt: 'Maak de indirecte vraag correct.', options: ['Weet je waar is de halte?', 'Weet je waar de halte is?', 'Weet je de halte waar is?'], answer: 1, explanation: 'In een indirecte vraag staat de persoonsvorm aan het einde van de bijzin.', audio: 'Weet je waar de halte is?' },
  { id: 'q7', topic: 'personen-en-zaken', level: 'B1', prompt: 'Je vraagt naar een persoon.', options: ['Waarmee werk je samen?', 'Met wie werk je samen?', 'Ermee wie werk je samen?'], answer: 1, explanation: 'Bij een persoon is met wie de duidelijke vorm.', audio: 'Met wie werk je samen?' },
  { id: 'q8', topic: 'waar-daar-er-hier', level: 'B1', prompt: 'Vervang “op de uitslag” door een neutrale verwijzing.', options: ['Ik wacht daarop de uitslag.', 'Ik wacht erop.', 'Ik wacht op er.'], answer: 1, explanation: 'Op de uitslag wordt erop.', audio: 'Ik wacht erop.' },
  { id: 'q9', topic: 'vragen-nuanceren', level: 'B2', prompt: 'Kies de professioneel genuanceerde vraag.', options: ['Waarom is dit zo?', 'Kun je toelichten waarop deze keuze is gebaseerd?', 'Zeg waarop dit is gebaseerd.'], answer: 1, explanation: 'De vraag is beleefd, precies en gebruikt de juiste indirecte structuur.', audio: 'Kun je toelichten waarop deze keuze is gebaseerd?' },
  { id: 'q10', topic: 'relatieve-waarvormen', level: 'B2', prompt: 'Kies de correcte relatieve vorm.', options: ['De pen met wat ik schrijf.', 'De pen waarmee ik schrijf.', 'De pen ermee ik schrijf.'], answer: 1, explanation: 'Waarmee verbindt de bijzin met de genoemde zaak: de pen.', audio: 'De pen waarmee ik schrijf ligt hier.' },
];
