export const supplementaryWordGroups = {
  "hallo": [
    "formeel aanspreken",
    "informeel aanspreken",
    "zich identificeren",
    "persoonlijke informatie geven",
    "een gesprek beginnen",
    "een gesprek afsluiten",
    "iemand welkom heten",
    "iemand feliciteren",
    "iemand bedanken",
    "excuses aanbieden",
    "om herhaling vragen",
    "langzamer laten spreken",
    "een woord laten spellen",
    "een misverstand uitleggen",
    "een naam verkeerd uitspreken",
    "een telefoonnummer doorgeven",
    "een bericht achterlaten",
    "beschikbaar zijn",
    "bereikbaar zijn",
    "contact houden met",
    "elkaar leren kennen",
    "uit hetzelfde land komen",
    "een taal vloeiend spreken",
    "een beetje Nederlands spreken",
    "iets niet verstaan"
  ],
  "school": [
    "de leerdoelen",
    "de studiewijzer",
    "de aanwezigheidsplicht",
    "de groepsopdracht",
    "de individuele opdracht",
    "de mondelinge toets",
    "de schriftelijke toets",
    "de luisteroefening",
    "de spreekopdracht",
    "de schrijfvaardigheid",
    "de leesvaardigheid",
    "de woordenschat",
    "de grammatica",
    "de uitspraak",
    "de spelling",
    "een planning maken",
    "de stof herhalen",
    "aantekeningen maken",
    "feedback verwerken",
    "een presentatie houden",
    "een bron gebruiken",
    "een deadline missen",
    "een vraag toelichten",
    "zelfstandig studeren",
    "voor een toets leren"
  ],
  "wonen": [
    "de koopwoning",
    "de huurwoning",
    "het rijtjeshuis",
    "de tussenwoning",
    "de hoekwoning",
    "het appartement",
    "de studio",
    "de nieuwbouw",
    "de verbouwing",
    "het bouwjaar",
    "de oppervlakte",
    "de slaapkamer",
    "de badkamer",
    "de keuken",
    "het toilet",
    "een bezichtiging plannen",
    "een bod doen",
    "de huur verhogen",
    "de woning inspecteren",
    "een gebrek doorgeven",
    "geluidsoverlast ervaren",
    "de buren waarschuwen",
    "afval scheiden",
    "de tuin onderhouden",
    "energie besparen"
  ],
  "eten": [
    "het ontbijt",
    "de lunch",
    "het avondeten",
    "het tussendoortje",
    "het voorgerecht",
    "het hoofdgerecht",
    "het nagerecht",
    "de portie",
    "het recept",
    "het ingrediënt",
    "de houdbaarheidsdatum",
    "de voedingswaarde",
    "de allergenen",
    "de verpakkingseenheid",
    "de boodschappenlijst",
    "een maaltijd overslaan",
    "een recept volgen",
    "iets aan de kook brengen",
    "op laag vuur koken",
    "de oven voorverwarmen",
    "iets in stukjes snijden",
    "op smaak brengen",
    "eten bewaren",
    "de restjes invriezen",
    "een dieet volgen"
  ],
  "gezondheid": [
    "de bloeddruk",
    "de hartslag",
    "de ademhaling",
    "de diagnose",
    "de verwijzing",
    "de bijwerking",
    "de dosering",
    "de bijsluiter",
    "de operatie",
    "de spoedeisende hulp",
    "de huisartsenpost",
    "de zorgverzekeraar",
    "het eigen risico",
    "de vergoeding",
    "de controleafspraak",
    "een klacht onderzoeken",
    "een diagnose stellen",
    "een behandeling starten",
    "een specialist raadplegen",
    "een verwijsbrief krijgen",
    "een medicijn voorschrijven",
    "een dosis overslaan",
    "een wond verzorgen",
    "een herstelperiode nodig hebben",
    "een gezonde leefstijl hebben"
  ],
  "kleding": [
    "de onderbroek",
    "de bh",
    "het overhemd",
    "de joggingbroek",
    "de regenjas",
    "de winterjas",
    "de handschoen",
    "de riem",
    "de pet",
    "de tas",
    "de hak",
    "de zool",
    "de kraag",
    "de pasvorm",
    "het label",
    "een outfit kiezen",
    "een broek inkorten",
    "een rits vervangen",
    "een knoop aannaaien",
    "kleding wassen",
    "kleding strijken",
    "een vlek verwijderen",
    "de was ophangen",
    "online kleding bestellen",
    "een maatadvies vragen"
  ],
  "reizen": [
    "de spits",
    "de file",
    "de omleiding",
    "de wegwerkzaamheden",
    "de verkeersregel",
    "het stoplicht",
    "het zebrapad",
    "de rotonde",
    "de snelweg",
    "de afrit",
    "de invoegstrook",
    "de fietsenstalling",
    "de parkeerautomaat",
    "de zone",
    "de maximumsnelheid",
    "een reis plannen",
    "de vertrektijd controleren",
    "een vertraging omroepen",
    "een alternatieve route nemen",
    "een stoel zoeken",
    "een overstap missen",
    "reiskosten declareren",
    "een abonnement verlengen",
    "een boete krijgen",
    "veilig oversteken"
  ],
  "vrije-tijd": [
    "de wandelroute",
    "het natuurgebied",
    "de speeltuin",
    "de sportschool",
    "het zwembad",
    "de vereniging",
    "het abonnement",
    "de repetitie",
    "de training",
    "de competitie",
    "de vrijwilliger",
    "het evenement",
    "de entreeprijs",
    "de openingstijd",
    "de reservering",
    "een activiteit organiseren",
    "zich vervelen",
    "een vrije dag nemen",
    "een weekend weggaan",
    "een evenement bezoeken",
    "een sport beoefenen",
    "een cursus volgen",
    "een instrument bespelen",
    "foto’s delen",
    "een uitnodiging accepteren"
  ],
  "verhuizen": [
    "de tijdelijke opslag",
    "het verhuisbedrijf",
    "de boedel",
    "het meubelstuk",
    "het gereedschap",
    "de boormachine",
    "de ladder",
    "de plattegrond",
    "de aansluiting",
    "de nutsvoorziening",
    "de postcodewijziging",
    "de gemeentelijke registratie",
    "de eindinspectie",
    "de opleverstaat",
    "de verhuisvergoeding",
    "een verhuisdatum kiezen",
    "een verhuisofferte aanvragen",
    "breekbare spullen beschermen",
    "dozen labelen",
    "meubels uit elkaar halen",
    "een busje huren",
    "een lift reserveren",
    "de oude woning leegmaken",
    "de nieuwe woning schoon opleveren",
    "post laten doorsturen"
  ],
  "nederland": [
    "de grondwet",
    "de overheid",
    "de Eerste Kamer",
    "de Tweede Kamer",
    "de politieke partij",
    "het stembureau",
    "het waterschap",
    "de verzorgingsstaat",
    "de vrijheid van meningsuiting",
    "de gelijkheid",
    "de tolerantie",
    "de integratie",
    "de inburgering",
    "de regionale taal",
    "het dialect",
    "een verkiezing houden",
    "een stem uitbrengen",
    "een traditie behouden",
    "een nationale feestdag vieren",
    "zich aanpassen aan",
    "een culturele gewoonte begrijpen",
    "een verschil respecteren",
    "direct communiceren",
    "een compromis sluiten",
    "vrijwilligerswerk doen"
  ],
  "kinderen": [
    "de peuterspeelzaal",
    "de ouderbijdrage",
    "de schoolvakantie",
    "het schoolreisje",
    "de gymles",
    "het leerlingvolgsysteem",
    "de leerprestaties",
    "de thuistaal",
    "de taalachterstand",
    "de ontwikkelingsfase",
    "de slaaproutine",
    "de eetgewoonte",
    "de schermtijd",
    "de speelafspraak",
    "de noodcontactpersoon",
    "een kind troosten",
    "positief gedrag stimuleren",
    "duidelijke grenzen aangeven",
    "een afspraak met de mentor maken",
    "een rapport bespreken",
    "huiswerk begeleiden",
    "een kind ziek melden",
    "een opvangdag ruilen",
    "een allergie doorgeven",
    "een veilige omgeving creëren"
  ],
  "winkels": [
    "de productbeschrijving",
    "de beoordeling",
    "de vergelijking",
    "de betaalmethode",
    "de factuur",
    "de kortingscode",
    "de klantenkaart",
    "de spaarkaart",
    "de bezorgdatum",
    "de bezorgpoging",
    "de retourtermijn",
    "het retourlabel",
    "de reparatietermijn",
    "de gebruiksaanwijzing",
    "de geschillencommissie",
    "prijzen vergelijken",
    "een review lezen",
    "een kortingscode invoeren",
    "een bestelling annuleren",
    "een afleveradres wijzigen",
    "een pakket weigeren",
    "een defect aantonen",
    "een vervangend product ontvangen",
    "een betalingsbewijs bewaren",
    "een klacht schriftelijk bevestigen"
  ],
  "opleidingen": [
    "het collegegeld",
    "de studiefinanciering",
    "de toelatingseis",
    "de vooropleiding",
    "de diplomawaardering",
    "de inschrijfdeadline",
    "de studielast",
    "het studieadvies",
    "de afstudeeropdracht",
    "de scriptie",
    "het onderzoek",
    "de bronvermelding",
    "de plagiaatcontrole",
    "het praktijkexamen",
    "de beroepsopleiding",
    "een studiekeuze maken",
    "een intakegesprek voeren",
    "een leerdoel formuleren",
    "een onderzoeksvraag opstellen",
    "bronnen beoordelen",
    "een planning bewaken",
    "een presentatie beoordelen",
    "een stageplek vinden",
    "een studie onderbreken",
    "een opleiding hervatten"
  ],
  "werk-zoeken": [
    "de arbeidsmarkt",
    "het uitzendbureau",
    "de vacaturebank",
    "het netwerk",
    "de recruiter",
    "de werving",
    "de selectie",
    "de sollicitatieprocedure",
    "de competentie",
    "de salarisindicatie",
    "de arbeidsduur",
    "de contractvorm",
    "de opzegtermijn",
    "de secundaire arbeidsvoorwaarden",
    "de loopbaan",
    "een profiel bijwerken",
    "een netwerk uitbreiden",
    "een open sollicitatie sturen",
    "een motivatie toelichten",
    "een praktijkvoorbeeld geven",
    "over salaris onderhandelen",
    "een referentie laten controleren",
    "een vervolggesprek krijgen",
    "een arbeidsvoorwaarde bespreken",
    "een baan aangeboden krijgen"
  ],
  "werken": [
    "het functioneringsgesprek",
    "het beoordelingsgesprek",
    "de werkdruk",
    "de werksfeer",
    "de veiligheid",
    "het protocol",
    "de procedure",
    "de kwaliteitsnorm",
    "de doelstelling",
    "de prestatie",
    "de samenwerking",
    "de communicatie",
    "de escalatie",
    "de vertrouwenspersoon",
    "de ondernemingsraad",
    "een vergadering voorbereiden",
    "notulen maken",
    "een actiepunt opvolgen",
    "een risico melden",
    "een incident registreren",
    "een proces verbeteren",
    "kennis overdragen",
    "een collega inwerken",
    "een conflict oplossen",
    "een resultaat presenteren"
  ],
  "gemeente": [
    "de basisregistratie personen",
    "de burgerlijke stand",
    "de naturalisatie",
    "de optieprocedure",
    "de omgevingsvergunning",
    "het bestemmingsplan",
    "de WOZ-waarde",
    "de gemeentelijke heffing",
    "de afvalstoffenheffing",
    "de rioolheffing",
    "de kwijtschelding",
    "de bezwaarprocedure",
    "de bezwaartermijn",
    "de beschikking",
    "het dossiernummer",
    "een afspraak verzetten",
    "een machtiging afgeven",
    "een bewijsstuk uploaden",
    "een aanvraag aanvullen",
    "de status controleren",
    "een besluit ontvangen",
    "binnen de termijn reageren",
    "een bezwaar motiveren",
    "een hoorzitting bijwonen",
    "een wijziging doorgeven"
  ]
};
