export const physicsCategories = [
  ['alle', 'Alle domeinen'],
  ['basis', 'Basisfysica'],
  ['mechanica', 'Mechanica'],
  ['elektromagnetisme', 'Elektromagnetisme'],
  ['velden-relativiteit', 'Velden & relativiteit'],
  ['kwantum', 'Kwantummechanica'],
  ['astronomie', 'Astronomie'],
  ['golven-thermo', 'Golven & thermodynamica'],
];

export const physicsConcepts = [
  { id: 'grootheid', category: 'basis', term: 'de grootheid', definition: 'Een meetbare eigenschap, zoals lengte, tijd, massa of temperatuur.' },
  { id: 'eenheid', category: 'basis', term: 'de eenheid', definition: 'Een afgesproken maat waarin een grootheid wordt uitgedrukt, zoals meter of seconde.' },
  { id: 'dimensie', category: 'basis', term: 'de dimensie', definition: 'Het fundamentele type van een grootheid, bijvoorbeeld lengte, tijd of massa.' },
  { id: 'scalair', category: 'basis', term: 'de scalair', definition: 'Een grootheid met alleen een waarde en geen richting.' },
  { id: 'vector', category: 'basis', term: 'de vector', definition: 'Een grootheid met zowel een grootte als een richting.' },
  { id: 'referentiestelsel', category: 'basis', term: 'het referentiestelsel', definition: 'Het gekozen kader waarbinnen positie, tijd en beweging worden beschreven.' },
  { id: 'systeem', category: 'basis', term: 'het systeem', definition: 'Het afgebakende deel van de werkelijkheid dat wordt onderzocht.' },
  { id: 'model', category: 'basis', term: 'het model', definition: 'Een vereenvoudigde voorstelling waarmee een fysisch verschijnsel wordt beschreven.' },
  { id: 'meting', category: 'basis', term: 'de meting', definition: 'Het bepalen van een waarde met een instrument of een afgesproken methode.' },
  { id: 'meetonzekerheid', category: 'basis', term: 'de meetonzekerheid', definition: 'De bandbreedte waarbinnen de werkelijke waarde waarschijnlijk ligt.' },
  { id: 'nauwkeurigheid', category: 'basis', term: 'de nauwkeurigheid', definition: 'De mate waarin een gemeten waarde dicht bij de werkelijke waarde ligt.' },
  { id: 'precisie', category: 'basis', term: 'de precisie', definition: 'De mate waarin herhaalde metingen dicht bij elkaar liggen.' },
  { id: 'natuurwet', category: 'basis', term: 'de natuurwet', definition: 'Een algemene relatie die een regelmatig fysisch patroon beschrijft.' },
  { id: 'theorie', category: 'basis', term: 'de theorie', definition: 'Een samenhangend verklaringsmodel dat door waarnemingen en experimenten wordt ondersteund.' },
  { id: 'natuurconstante', category: 'basis', term: 'de natuurconstante', definition: 'Een vaste waarde die in fundamentele natuurkundige relaties voorkomt.' },

  { id: 'positie', category: 'mechanica', term: 'de positie', definition: 'De plaats van een object ten opzichte van een gekozen referentiestelsel.' },
  { id: 'verplaatsing', category: 'mechanica', term: 'de verplaatsing', definition: 'De gerichte verandering van de beginpositie naar de eindpositie.' },
  { id: 'afstand', category: 'mechanica', term: 'de afstand', definition: 'De totale lengte van het afgelegde pad.' },
  { id: 'snelheid', category: 'mechanica', term: 'de snelheid', definition: 'De verandering van positie per tijdseenheid.' },
  { id: 'versnelling', category: 'mechanica', term: 'de versnelling', definition: 'De verandering van snelheid per tijdseenheid.' },
  { id: 'massa', category: 'mechanica', term: 'de massa', definition: 'Een maat voor de hoeveelheid materie en de traagheid van een object.' },
  { id: 'kracht', category: 'mechanica', term: 'de kracht', definition: 'Een wisselwerking die de beweging of vorm van een object kan veranderen.' },
  { id: 'gewichtskracht', category: 'mechanica', term: 'de gewichtskracht', definition: 'De zwaartekracht die op een massa werkt.' },
  { id: 'traagheid', category: 'mechanica', term: 'de traagheid', definition: 'De neiging van een object om zijn bewegingstoestand te behouden.' },
  { id: 'impuls', category: 'mechanica', term: 'de impuls', definition: 'Een bewegingsgrootheid die gelijk is aan massa maal snelheid.' },
  { id: 'arbeid', category: 'mechanica', term: 'de arbeid', definition: 'De energieoverdracht wanneer een kracht een object over een afstand verplaatst.' },
  { id: 'energie', category: 'mechanica', term: 'de energie', definition: 'Het vermogen van een systeem om arbeid te verrichten of verandering te veroorzaken.' },
  { id: 'vermogen', category: 'mechanica', term: 'het vermogen', definition: 'De hoeveelheid omgezette of overgedragen energie per tijdseenheid.' },
  { id: 'koppel', category: 'mechanica', term: 'het koppel', definition: 'Het draaiende effect van een kracht rond een as of draaipunt.' },
  { id: 'evenwicht', category: 'mechanica', term: 'het evenwicht', definition: 'Een toestand waarin de resulterende kracht en het resulterende koppel nul zijn.' },

  { id: 'elektrische-lading', category: 'elektromagnetisme', term: 'de elektrische lading', definition: 'Een eigenschap van materie die elektrische aantrekking en afstoting veroorzaakt.' },
  { id: 'elektrische-stroom', category: 'elektromagnetisme', term: 'de elektrische stroom', definition: 'De verplaatsing van elektrische lading per tijdseenheid.' },
  { id: 'spanning', category: 'elektromagnetisme', term: 'de spanning', definition: 'Het verschil in elektrische potentiaal tussen twee punten.' },
  { id: 'weerstand', category: 'elektromagnetisme', term: 'de weerstand', definition: 'De mate waarin een materiaal of component elektrische stroom tegenwerkt.' },
  { id: 'geleider', category: 'elektromagnetisme', term: 'de geleider', definition: 'Een materiaal waarin elektrische lading zich relatief gemakkelijk kan verplaatsen.' },
  { id: 'isolator', category: 'elektromagnetisme', term: 'de isolator', definition: 'Een materiaal dat de beweging van elektrische lading sterk beperkt.' },
  { id: 'elektrisch-veld', category: 'elektromagnetisme', term: 'het elektrische veld', definition: 'Een veld dat aangeeft welke elektrische kracht een lading op elke plaats zou ondervinden.' },
  { id: 'elektrische-potentiaal', category: 'elektromagnetisme', term: 'de elektrische potentiaal', definition: 'De elektrische potentiële energie per eenheid lading.' },
  { id: 'capaciteit', category: 'elektromagnetisme', term: 'de capaciteit', definition: 'De mate waarin een systeem elektrische lading kan opslaan bij een gegeven spanning.' },
  { id: 'condensator', category: 'elektromagnetisme', term: 'de condensator', definition: 'Een component die elektrische lading en energie in een elektrisch veld opslaat.' },
  { id: 'magnetisch-veld', category: 'elektromagnetisme', term: 'het magnetische veld', definition: 'Een veld dat magnetische krachten op bewegende ladingen en magneten beschrijft.' },
  { id: 'magnetische-flux', category: 'elektromagnetisme', term: 'de magnetische flux', definition: 'Een maat voor de hoeveelheid magnetisch veld door een oppervlak.' },
  { id: 'elektromagnetische-inductie', category: 'elektromagnetisme', term: 'de elektromagnetische inductie', definition: 'Het ontstaan van een spanning door een veranderende magnetische flux.' },
  { id: 'elektromagnetische-golf', category: 'elektromagnetisme', term: 'de elektromagnetische golf', definition: 'Een voortplantende combinatie van veranderende elektrische en magnetische velden.' },
  { id: 'schakeling', category: 'elektromagnetisme', term: 'de schakeling', definition: 'Een verbonden geheel van elektrische componenten waar stroom door kan lopen.' },

  { id: 'veld', category: 'velden-relativiteit', term: 'het veld', definition: 'Een grootheid die aan elk punt in ruimte en tijd een waarde toekent.' },
  { id: 'scalair-veld', category: 'velden-relativiteit', term: 'het scalaire veld', definition: 'Een veld dat op elk punt één getalswaarde heeft.' },
  { id: 'vectorveld', category: 'velden-relativiteit', term: 'het vectorveld', definition: 'Een veld dat op elk punt een vector met grootte en richting heeft.' },
  { id: 'gradient', category: 'velden-relativiteit', term: 'de gradiënt', definition: 'Een vector die de richting en snelheid van de sterkste toename van een scalair veld aangeeft.' },
  { id: 'divergentie', category: 'velden-relativiteit', term: 'de divergentie', definition: 'Een maat voor de lokale bron- of putsterkte van een vectorveld.' },
  { id: 'rotatie', category: 'velden-relativiteit', term: 'de rotatie', definition: 'Een maat voor de lokale draaiing van een vectorveld.' },
  { id: 'flux', category: 'velden-relativiteit', term: 'de flux', definition: 'De hoeveelheid van een veld die door een oppervlak gaat.' },
  { id: 'potentiaal', category: 'velden-relativiteit', term: 'de potentiaal', definition: 'Een scalaire functie waaruit in veel gevallen een krachtveld kan worden afgeleid.' },
  { id: 'veldlijn', category: 'velden-relativiteit', term: 'de veldlijn', definition: 'Een denkbeeldige lijn die op elk punt de richting van een vectorveld volgt.' },
  { id: 'symmetrie', category: 'velden-relativiteit', term: 'de symmetrie', definition: 'Een eigenschap die onveranderd blijft onder een bepaalde transformatie.' },
  { id: 'ruimtetijd', category: 'velden-relativiteit', term: 'de ruimtetijd', definition: 'De gezamenlijke beschrijving van drie ruimtedimensies en één tijdsdimensie.' },
  { id: 'inertiaalstelsel', category: 'velden-relativiteit', term: 'het inertiaalstelsel', definition: 'Een referentiestelsel waarin een krachtvrij object met constante snelheid beweegt.' },
  { id: 'relativiteit', category: 'velden-relativiteit', term: 'de relativiteit', definition: 'Het principe dat metingen van ruimte en tijd afhangen van de beweging en zwaartekracht van de waarnemer.' },
  { id: 'tijddilatatie', category: 'velden-relativiteit', term: 'de tijddilatatie', definition: 'Het verschijnsel dat verschillende waarnemers verschillende tijdsintervallen meten.' },
  { id: 'zwaartekrachtsveld', category: 'velden-relativiteit', term: 'het zwaartekrachtsveld', definition: 'Een veld dat de zwaartekracht op massa en energie beschrijft.' },

  { id: 'kwantum', category: 'kwantum', term: 'het kwantum', definition: 'Een kleinste afzonderlijke hoeveelheid van een bepaalde fysische grootheid.' },
  { id: 'golffunctie', category: 'kwantum', term: 'de golffunctie', definition: 'Een wiskundige beschrijving van de kwantumtoestand van een systeem.' },
  { id: 'waarschijnlijkheidsamplitude', category: 'kwantum', term: 'de waarschijnlijkheidsamplitude', definition: 'Een complexe grootheid waarvan het kwadraat de kans op een meetuitkomst bepaalt.' },
  { id: 'superpositie', category: 'kwantum', term: 'de superpositie', definition: 'Een toestand waarin meerdere mogelijke kwantumtoestanden tegelijk bijdragen.' },
  { id: 'waarneming', category: 'kwantum', term: 'de waarneming', definition: 'Het verkrijgen van informatie over een fysisch systeem door interactie of meting.' },
  { id: 'kwantummeting', category: 'kwantum', term: 'de kwantummeting', definition: 'Een meting die een mogelijke uitkomst van een kwantumtoestand registreert.' },
  { id: 'operator', category: 'kwantum', term: 'de operator', definition: 'Een wiskundige bewerking die een meetbare grootheid of transformatie voorstelt.' },
  { id: 'eigenwaarde', category: 'kwantum', term: 'de eigenwaarde', definition: 'Een mogelijke meetwaarde die bij een operator en een eigenstaat hoort.' },
  { id: 'eigenstaat', category: 'kwantum', term: 'de eigenstaat', definition: 'Een toestand waarin een bepaalde meting een vaste eigenwaarde oplevert.' },
  { id: 'onzekerheidsprincipe', category: 'kwantum', term: 'het onzekerheidsprincipe', definition: 'Het principe dat bepaalde paren grootheden niet tegelijk onbeperkt nauwkeurig bepaald kunnen worden.' },
  { id: 'spin', category: 'kwantum', term: 'de spin', definition: 'Een intrinsieke kwantumeigenschap die zich gedraagt als een vorm van impulsmoment.' },
  { id: 'kwantisatie', category: 'kwantum', term: 'de kwantisatie', definition: 'Het beperken van een grootheid tot afzonderlijke toegestane waarden.' },
  { id: 'verstrengeling', category: 'kwantum', term: 'de verstrengeling', definition: 'Een gedeelde kwantumtoestand waarbij delen van een systeem sterke correlaties vertonen.' },
  { id: 'tunneleffect', category: 'kwantum', term: 'het tunneleffect', definition: 'Het verschijnsel dat een deeltje een barrière kan passeren die klassiek ondoordringbaar is.' },
  { id: 'golf-deeltje-dualiteit', category: 'kwantum', term: 'de golf-deeltjedualiteit', definition: 'Het principe dat kwantumobjecten zowel golf- als deeltjeseigenschappen kunnen tonen.' },

  { id: 'hemellichaam', category: 'astronomie', term: 'het hemellichaam', definition: 'Een natuurlijk object in de ruimte, zoals een planeet, ster of maan.' },
  { id: 'planeet', category: 'astronomie', term: 'de planeet', definition: 'Een groot hemellichaam dat om een ster draait en zelf geen kernfusie onderhoudt.' },
  { id: 'exoplaneet', category: 'astronomie', term: 'de exoplaneet', definition: 'Een planeet die om een andere ster dan de zon draait.' },
  { id: 'maan', category: 'astronomie', term: 'de maan', definition: 'Een natuurlijk hemellichaam dat om een planeet of ander klein lichaam draait.' },
  { id: 'ster', category: 'astronomie', term: 'de ster', definition: 'Een heet hemellichaam dat energie produceert door kernfusie.' },
  { id: 'sterrenbeeld', category: 'astronomie', term: 'het sterrenbeeld', definition: 'Een herkenbaar patroon of officieel gebied aan de hemel.' },
  { id: 'nevel', category: 'astronomie', term: 'de nevel', definition: 'Een wolk van gas en stof in de interstellaire ruimte.' },
  { id: 'sterrenstelsel', category: 'astronomie', term: 'het sterrenstelsel', definition: 'Een groot systeem van sterren, gas, stof en donkere materie dat door zwaartekracht bijeenblijft.' },
  { id: 'zwart-gat', category: 'astronomie', term: 'het zwarte gat', definition: 'Een gebied waaruit door de sterke zwaartekracht zelfs licht niet kan ontsnappen.' },
  { id: 'waarnemingshorizon', category: 'astronomie', term: 'de waarnemingshorizon', definition: 'De grens rond een zwart gat waarbinnen ontsnappen niet meer mogelijk is.' },
  { id: 'supernova', category: 'astronomie', term: 'de supernova', definition: 'Een zeer krachtige explosie aan het einde van de evolutie van bepaalde sterren.' },
  { id: 'neutronenster', category: 'astronomie', term: 'de neutronenster', definition: 'Een extreem compacte sterrest die grotendeels uit neutronen bestaat.' },
  { id: 'roodverschuiving', category: 'astronomie', term: 'de roodverschuiving', definition: 'De verschuiving van licht naar langere golflengten, vaak door beweging of uitdijing.' },
  { id: 'heelal', category: 'astronomie', term: 'het heelal', definition: 'Het geheel van ruimte, tijd, materie en energie.' },
  { id: 'kosmologie', category: 'astronomie', term: 'de kosmologie', definition: 'De studie van de oorsprong, structuur en ontwikkeling van het heelal.' },

  { id: 'temperatuur', category: 'golven-thermo', term: 'de temperatuur', definition: 'Een maat voor de thermische toestand en gemiddelde microscopische beweging in een systeem.' },
  { id: 'warmte', category: 'golven-thermo', term: 'de warmte', definition: 'Energie die door een temperatuurverschil wordt overgedragen.' },
  { id: 'entropie', category: 'golven-thermo', term: 'de entropie', definition: 'Een toestandsfunctie die samenhangt met het aantal mogelijke microscopische configuraties.' },
  { id: 'druk', category: 'golven-thermo', term: 'de druk', definition: 'De kracht per oppervlakte-eenheid.' },
  { id: 'faseovergang', category: 'golven-thermo', term: 'de faseovergang', definition: 'De overgang van materie tussen toestanden zoals vast, vloeibaar en gasvormig.' },
  { id: 'golf', category: 'golven-thermo', term: 'de golf', definition: 'Een voortplantende verstoring die energie en informatie kan overbrengen.' },
  { id: 'frequentie', category: 'golven-thermo', term: 'de frequentie', definition: 'Het aantal herhalingen of trillingen per tijdseenheid.' },
  { id: 'golflengte', category: 'golven-thermo', term: 'de golflengte', definition: 'De afstand tussen twee opeenvolgende punten met dezelfde fase in een golf.' },
  { id: 'amplitude', category: 'golven-thermo', term: 'de amplitude', definition: 'De maximale uitwijking van een trilling of golf ten opzichte van het evenwicht.' },
  { id: 'resonantie', category: 'golven-thermo', term: 'de resonantie', definition: 'Een sterke respons wanneer een systeem wordt aangedreven nabij zijn eigen frequentie.' },
  { id: 'geluid', category: 'golven-thermo', term: 'het geluid', definition: 'Een mechanische golf die zich door een medium voortplant en hoorbaar kan zijn.' },
  { id: 'licht', category: 'golven-thermo', term: 'het licht', definition: 'Elektromagnetische straling die zich als golf en als kwantum kan gedragen.' },
  { id: 'spectrum', category: 'golven-thermo', term: 'het spectrum', definition: 'De verdeling van een signaal over frequenties, golflengten of energieën.' },
  { id: 'interferentie', category: 'golven-thermo', term: 'de interferentie', definition: 'Het versterken of verzwakken dat ontstaat wanneer golven elkaar overlappen.' },
  { id: 'diffractie', category: 'golven-thermo', term: 'de diffractie', definition: 'Het buigen en verspreiden van golven rond randen of door openingen.' },
];

export const softwareCategories = [
  ['alle', 'Alle domeinen'],
  ['programmeren', 'Programmeren'],
  ['datastructuren', 'Datastructuren'],
  ['architectuur', 'Softwarearchitectuur'],
  ['data', 'Data & databases'],
  ['cloud-devops', 'Cloud & DevOps'],
  ['beveiliging', 'Beveiliging'],
  ['kwaliteit', 'Kwaliteit & observability'],
  ['ai', 'AI & machine learning'],
];

export const softwareConcepts = [
  { id: 'software', category: 'programmeren', term: 'de software', definition: 'Het geheel van programma’s, gegevens en instructies die door computers worden uitgevoerd.' },
  { id: 'programma', category: 'programmeren', term: 'het programma', definition: 'Een samenhangende reeks instructies die een computer een taak laat uitvoeren.' },
  { id: 'broncode', category: 'programmeren', term: 'de broncode', definition: 'De voor mensen leesbare tekst waarin software is geschreven.' },
  { id: 'algoritme', category: 'programmeren', term: 'het algoritme', definition: 'Een eindige en geordende reeks stappen om een probleem op te lossen.' },
  { id: 'variabele', category: 'programmeren', term: 'de variabele', definition: 'Een benoemde plaats waarin een veranderbare waarde wordt bewaard.' },
  { id: 'constante', category: 'programmeren', term: 'de constante', definition: 'Een benoemde waarde die tijdens de uitvoering niet verandert.' },
  { id: 'datatype', category: 'programmeren', term: 'het datatype', definition: 'De categorie die bepaalt welke waarden en bewerkingen zijn toegestaan.' },
  { id: 'functie', category: 'programmeren', term: 'de functie', definition: 'Een herbruikbaar blok code dat een specifieke taak uitvoert.' },
  { id: 'parameter', category: 'programmeren', term: 'de parameter', definition: 'Een benoemde invoer die een functie of procedure ontvangt.' },
  { id: 'retourwaarde', category: 'programmeren', term: 'de retourwaarde', definition: 'De waarde die een functie na uitvoering teruggeeft.' },
  { id: 'voorwaarde', category: 'programmeren', term: 'de voorwaarde', definition: 'Een logische test die bepaalt welke code wordt uitgevoerd.' },
  { id: 'lus', category: 'programmeren', term: 'de lus', definition: 'Een constructie die code herhaaldelijk uitvoert.' },
  { id: 'uitzondering', category: 'programmeren', term: 'de uitzondering', definition: 'Een signaal dat tijdens de uitvoering een bijzondere of foutieve situatie is ontstaan.' },
  { id: 'compiler', category: 'programmeren', term: 'de compiler', definition: 'Een programma dat broncode vertaalt naar een andere uitvoerbare vorm.' },
  { id: 'interpreter', category: 'programmeren', term: 'de interpreter', definition: 'Een programma dat instructies tijdens de uitvoering leest en uitvoert.' },

  { id: 'array', category: 'datastructuren', term: 'de array', definition: 'Een geordende verzameling elementen die meestal via een index wordt benaderd.' },
  { id: 'lijst', category: 'datastructuren', term: 'de lijst', definition: 'Een geordende verzameling waarin elementen kunnen worden toegevoegd of verwijderd.' },
  { id: 'stapel', category: 'datastructuren', term: 'de stapel', definition: 'Een structuur waarin het laatst toegevoegde element als eerste wordt verwijderd.' },
  { id: 'wachtrij', category: 'datastructuren', term: 'de wachtrij', definition: 'Een structuur waarin het eerst toegevoegde element als eerste wordt verwijderd.' },
  { id: 'verzameling-data', category: 'datastructuren', term: 'de verzameling', definition: 'Een collectie waarin elk element hoogstens één keer voorkomt.' },
  { id: 'woordenboek', category: 'datastructuren', term: 'het woordenboek', definition: 'Een structuur die sleutels aan waarden koppelt.' },
  { id: 'boom', category: 'datastructuren', term: 'de boom', definition: 'Een hiërarchische structuur van knopen met ouder-kindrelaties.' },
  { id: 'graaf', category: 'datastructuren', term: 'de graaf', definition: 'Een structuur van knopen en verbindingen die relaties modelleert.' },
  { id: 'knoop', category: 'datastructuren', term: 'de knoop', definition: 'Een afzonderlijk element in een boom of graaf.' },
  { id: 'verbinding', category: 'datastructuren', term: 'de verbinding', definition: 'Een relatie tussen twee knopen in een graaf.' },
  { id: 'hashfunctie', category: 'datastructuren', term: 'de hashfunctie', definition: 'Een functie die invoer omzet in een vaste of begrensde numerieke representatie.' },
  { id: 'recursie', category: 'datastructuren', term: 'de recursie', definition: 'Een techniek waarbij een functie zichzelf aanroept op een kleiner deelprobleem.' },
  { id: 'iterator', category: 'datastructuren', term: 'de iterator', definition: 'Een object of mechanisme dat elementen één voor één doorloopt.' },
  { id: 'complexiteit', category: 'datastructuren', term: 'de complexiteit', definition: 'Een maat voor de benodigde tijd of het geheugen van een algoritme.' },
  { id: 'geheugen', category: 'datastructuren', term: 'het geheugen', definition: 'De opslagruimte die een programma tijdens de uitvoering gebruikt.' },

  { id: 'softwarearchitectuur', category: 'architectuur', term: 'de softwarearchitectuur', definition: 'De hoofdstructuur van een softwaresysteem en de principes achter de onderdelen en relaties.' },
  { id: 'component', category: 'architectuur', term: 'de component', definition: 'Een zelfstandig onderdeel met een duidelijke verantwoordelijkheid en grens.' },
  { id: 'module', category: 'architectuur', term: 'de module', definition: 'Een logisch gegroepeerd deel van code of functionaliteit.' },
  { id: 'interface', category: 'architectuur', term: 'de interface', definition: 'Een afgesproken grens waarlangs onderdelen met elkaar communiceren.' },
  { id: 'afhankelijkheid', category: 'architectuur', term: 'de afhankelijkheid', definition: 'Een relatie waarbij een onderdeel een ander onderdeel nodig heeft.' },
  { id: 'cohesie', category: 'architectuur', term: 'de cohesie', definition: 'De mate waarin verantwoordelijkheden binnen één onderdeel inhoudelijk bij elkaar horen.' },
  { id: 'koppeling', category: 'architectuur', term: 'de koppeling', definition: 'De mate waarin onderdelen van elkaar afhankelijk zijn.' },
  { id: 'laag', category: 'architectuur', term: 'de laag', definition: 'Een horizontale groepering van verantwoordelijkheden binnen een architectuur.' },
  { id: 'monoliet', category: 'architectuur', term: 'de monoliet', definition: 'Een applicatie die als één samenhangend geheel wordt gebouwd en uitgerold.' },
  { id: 'microservice', category: 'architectuur', term: 'de microservice', definition: 'Een kleine zelfstandig inzetbare service rond een afgebakende verantwoordelijkheid.' },
  { id: 'api', category: 'architectuur', term: 'de API', definition: 'Een formele interface waarmee softwareonderdelen functies of gegevens aanbieden.' },
  { id: 'gebeurtenis', category: 'architectuur', term: 'de gebeurtenis', definition: 'Een vastgelegd feit dat aangeeft dat iets in een systeem is gebeurd.' },
  { id: 'bericht', category: 'architectuur', term: 'het bericht', definition: 'Een gegevenspakket dat tussen processen, services of systemen wordt uitgewisseld.' },
  { id: 'domein', category: 'architectuur', term: 'het domein', definition: 'Het kennis- en probleemgebied waarvoor software wordt ontwikkeld.' },
  { id: 'begrensde-context', category: 'architectuur', term: 'de begrensde context', definition: 'Een expliciete grens waarbinnen termen en modellen één consistente betekenis hebben.' },

  { id: 'database', category: 'data', term: 'de database', definition: 'Een georganiseerd systeem voor het opslaan, beheren en opvragen van gegevens.' },
  { id: 'tabel', category: 'data', term: 'de tabel', definition: 'Een structuur van rijen en kolommen waarin relationele gegevens worden opgeslagen.' },
  { id: 'schema', category: 'data', term: 'het schema', definition: 'De formele beschrijving van de structuur en relaties van gegevens.' },
  { id: 'sleutel', category: 'data', term: 'de sleutel', definition: 'Een waarde of combinatie van waarden waarmee een record wordt geïdentificeerd of gekoppeld.' },
  { id: 'index', category: 'data', term: 'de index', definition: 'Een aanvullende structuur die het zoeken naar gegevens versnelt.' },
  { id: 'query', category: 'data', term: 'de query', definition: 'Een formele opdracht om gegevens op te vragen of te wijzigen.' },
  { id: 'transactie', category: 'data', term: 'de transactie', definition: 'Een groep databewerkingen die als één logische eenheid wordt uitgevoerd.' },
  { id: 'consistentie', category: 'data', term: 'de consistentie', definition: 'De eigenschap dat gegevens voldoen aan afgesproken regels en onderlinge verbanden.' },
  { id: 'datawarehouse', category: 'data', term: 'het datawarehouse', definition: 'Een geïntegreerde gegevensomgeving voor analyse en rapportage.' },
  { id: 'datalake', category: 'data', term: 'het datalake', definition: 'Een opslagomgeving voor grote hoeveelheden ruwe en uiteenlopende gegevens.' },
  { id: 'lakehouse', category: 'data', term: 'het lakehouse', definition: 'Een architectuur die eigenschappen van een datalake en datawarehouse combineert.' },
  { id: 'etl', category: 'data', term: 'ETL', definition: 'Het proces van gegevens extraheren, transformeren en laden.' },
  { id: 'batchverwerking', category: 'data', term: 'de batchverwerking', definition: 'Het verwerken van een verzameling gegevens in geplande of afgebakende groepen.' },
  { id: 'stroomverwerking', category: 'data', term: 'de stroomverwerking', definition: 'Het continu verwerken van gegevens terwijl ze binnenkomen.' },
  { id: 'dataherkomst', category: 'data', term: 'de dataherkomst', definition: 'De vastgelegde oorsprong, verplaatsing en transformatie van gegevens.' },

  { id: 'cloudcomputing', category: 'cloud-devops', term: 'cloudcomputing', definition: 'Het leveren van rekencapaciteit, opslag en diensten via een netwerk op aanvraag.' },
  { id: 'virtuele-machine', category: 'cloud-devops', term: 'de virtuele machine', definition: 'Een softwarematig nagebootste computer met een eigen besturingssysteem.' },
  { id: 'container', category: 'cloud-devops', term: 'de container', definition: 'Een geïsoleerde uitvoeromgeving die applicatiecode en afhankelijkheden bundelt.' },
  { id: 'containerimage', category: 'cloud-devops', term: 'de containerimage', definition: 'Een onveranderlijk pakket waaruit containers worden gestart.' },
  { id: 'cluster', category: 'cloud-devops', term: 'het cluster', definition: 'Een groep computers of knopen die als één platform samenwerken.' },
  { id: 'orkestratie', category: 'cloud-devops', term: 'de orkestratie', definition: 'Het geautomatiseerd plannen, starten, schalen en herstellen van workloads.' },
  { id: 'uitrol', category: 'cloud-devops', term: 'de uitrol', definition: 'Het beschikbaar maken van een nieuwe softwareversie in een omgeving.' },
  { id: 'schalen', category: 'cloud-devops', term: 'het schalen', definition: 'Het aanpassen van capaciteit aan veranderende belasting.' },
  { id: 'loadbalancer', category: 'cloud-devops', term: 'de loadbalancer', definition: 'Een component die netwerkverkeer over meerdere doelen verdeelt.' },
  { id: 'regio', category: 'cloud-devops', term: 'de regio', definition: 'Een geografisch gebied waarin een cloudprovider infrastructuur aanbiedt.' },
  { id: 'beschikbaarheidszone', category: 'cloud-devops', term: 'de beschikbaarheidszone', definition: 'Een afzonderlijke infrastructuurlocatie binnen een cloudregio.' },
  { id: 'continue-integratie', category: 'cloud-devops', term: 'continue integratie', definition: 'Het vaak samenvoegen en automatisch testen van codewijzigingen.' },
  { id: 'continue-levering', category: 'cloud-devops', term: 'continue levering', definition: 'Het geautomatiseerd gereedmaken van software voor veilige en herhaalbare uitrol.' },
  { id: 'infrastructuur-als-code', category: 'cloud-devops', term: 'infrastructuur als code', definition: 'Het declaratief beheren van infrastructuur via versiebeheerbare bestanden.' },
  { id: 'pipeline', category: 'cloud-devops', term: 'de pipeline', definition: 'Een geautomatiseerde keten van bouw-, test- en uitrolstappen.' },

  { id: 'identiteit', category: 'beveiliging', term: 'de identiteit', definition: 'De digitale representatie van een gebruiker, dienst of apparaat.' },
  { id: 'authenticatie', category: 'beveiliging', term: 'de authenticatie', definition: 'Het verifiëren dat een identiteit werkelijk is wie of wat zij beweert te zijn.' },
  { id: 'autorisatie', category: 'beveiliging', term: 'de autorisatie', definition: 'Het bepalen welke handelingen een geverifieerde identiteit mag uitvoeren.' },
  { id: 'rol', category: 'beveiliging', term: 'de rol', definition: 'Een benoemde verzameling verantwoordelijkheden of toegangsrechten.' },
  { id: 'toestemming', category: 'beveiliging', term: 'de toestemming', definition: 'Een specifiek recht om een actie op een bron uit te voeren.' },
  { id: 'versleuteling', category: 'beveiliging', term: 'de versleuteling', definition: 'Het omzetten van gegevens naar een vorm die zonder sleutel niet leesbaar is.' },
  { id: 'cryptografische-sleutel', category: 'beveiliging', term: 'de cryptografische sleutel', definition: 'Een waarde die een cryptografische bewerking bestuurt.' },
  { id: 'certificaat', category: 'beveiliging', term: 'het certificaat', definition: 'Een digitaal document dat een publieke sleutel aan een identiteit koppelt.' },
  { id: 'geheim', category: 'beveiliging', term: 'het geheim', definition: 'Vertrouwelijke informatie zoals een wachtwoord, token of sleutel.' },
  { id: 'hash', category: 'beveiliging', term: 'de hash', definition: 'Een vaste representatie die door een eenrichtingsfunctie uit invoergegevens wordt berekend.' },
  { id: 'kwetsbaarheid', category: 'beveiliging', term: 'de kwetsbaarheid', definition: 'Een zwakke plek die misbruikt kan worden om beveiliging te omzeilen.' },
  { id: 'dreiging', category: 'beveiliging', term: 'de dreiging', definition: 'Een mogelijke oorzaak van schade aan systemen, gegevens of gebruikers.' },
  { id: 'beveiligingspatch', category: 'beveiliging', term: 'de beveiligingspatch', definition: 'Een softwarewijziging die een bekend beveiligingsprobleem oplost.' },
  { id: 'zero-trust', category: 'beveiliging', term: 'zero trust', definition: 'Een beveiligingsmodel waarin geen verzoek automatisch wordt vertrouwd.' },
  { id: 'minimale-rechten', category: 'beveiliging', term: 'het principe van minimale rechten', definition: 'Het principe dat een identiteit alleen de strikt noodzakelijke toegang krijgt.' },

  { id: 'logboekregel', category: 'kwaliteit', term: 'de logregel', definition: 'Een vastgelegde tekstuele gebeurtenis uit de uitvoering van een systeem.' },
  { id: 'metriek', category: 'kwaliteit', term: 'de metriek', definition: 'Een numerieke meting die gedrag of prestaties door de tijd beschrijft.' },
  { id: 'trace', category: 'kwaliteit', term: 'de trace', definition: 'Een volledige keten van bewerkingen die samen één verzoek of transactie vormen.' },
  { id: 'span', category: 'kwaliteit', term: 'de span', definition: 'Een afzonderlijke tijdgebonden bewerking binnen een trace.' },
  { id: 'telemetrie', category: 'kwaliteit', term: 'de telemetrie', definition: 'Automatisch verzamelde gegevens over de werking van een systeem.' },
  { id: 'monitoring', category: 'kwaliteit', term: 'de monitoring', definition: 'Het voortdurend volgen van de toestand en prestaties van systemen.' },
  { id: 'waarschuwing', category: 'kwaliteit', term: 'de waarschuwing', definition: 'Een melding die wordt geactiveerd wanneer een afgesproken conditie optreedt.' },
  { id: 'dashboard', category: 'kwaliteit', term: 'het dashboard', definition: 'Een visueel overzicht van relevante metingen en toestanden.' },
  { id: 'sli', category: 'kwaliteit', term: 'de service level indicator', definition: 'Een meetbare indicator van de kwaliteit van een dienst.' },
  { id: 'slo', category: 'kwaliteit', term: 'de service level objective', definition: 'Een intern doel voor een service level indicator.' },
  { id: 'sla', category: 'kwaliteit', term: 'de service level agreement', definition: 'Een formele afspraak over het te leveren dienstverleningsniveau.' },
  { id: 'foutbudget', category: 'kwaliteit', term: 'het foutbudget', definition: 'De toegestane hoeveelheid onbetrouwbaarheid binnen een afgesproken doel.' },
  { id: 'unittest', category: 'kwaliteit', term: 'de unittest', definition: 'Een test van één kleine geïsoleerde eenheid code.' },
  { id: 'integratietest', category: 'kwaliteit', term: 'de integratietest', definition: 'Een test die controleert of meerdere onderdelen correct samenwerken.' },
  { id: 'regressietest', category: 'kwaliteit', term: 'de regressietest', definition: 'Een test die controleert of bestaande functionaliteit na wijzigingen blijft werken.' },

  { id: 'ai-model', category: 'ai', term: 'het model', definition: 'Een geleerd of ontworpen systeem dat invoer omzet in voorspellingen of gegenereerde uitvoer.' },
  { id: 'training', category: 'ai', term: 'de training', definition: 'Het proces waarin een model zijn parameters aanpast op basis van voorbeelden.' },
  { id: 'inferentie', category: 'ai', term: 'de inferentie', definition: 'Het gebruiken van een getraind model om uitvoer voor nieuwe invoer te berekenen.' },
  { id: 'kenmerk', category: 'ai', term: 'het kenmerk', definition: 'Een meetbare invoervariabele die door een model wordt gebruikt.' },
  { id: 'label', category: 'ai', term: 'het label', definition: 'De bekende doelwaarde of categorie die bij een trainingsvoorbeeld hoort.' },
  { id: 'dataset', category: 'ai', term: 'de dataset', definition: 'Een georganiseerde verzameling voorbeelden en bijbehorende gegevens.' },
  { id: 'neuraal-netwerk', category: 'ai', term: 'het neurale netwerk', definition: 'Een model van verbonden lagen dat patronen uit gegevens kan leren.' },
  { id: 'embedding', category: 'ai', term: 'de embedding', definition: 'Een vectorrepresentatie waarin betekenisvolle overeenkomsten als afstanden worden vastgelegd.' },
  { id: 'token', category: 'ai', term: 'het token', definition: 'Een klein tekst- of data-element dat door een model als invoereenheid wordt verwerkt.' },
  { id: 'prompt', category: 'ai', term: 'de prompt', definition: 'De instructie of context die aan een generatief model wordt gegeven.' },
  { id: 'hallucinatie', category: 'ai', term: 'de hallucinatie', definition: 'Een overtuigend klinkende modeluitvoer die niet door betrouwbare gegevens wordt ondersteund.' },
  { id: 'overfitting', category: 'ai', term: 'de overfitting', definition: 'De situatie waarin een model trainingsgegevens te specifiek leert en slecht generaliseert.' },
  { id: 'classificatie', category: 'ai', term: 'de classificatie', definition: 'Het toewijzen van invoer aan één of meer categorieën.' },
  { id: 'regressie', category: 'ai', term: 'de regressie', definition: 'Het voorspellen van een continue numerieke waarde.' },
  { id: 'generatieve-ai', category: 'ai', term: 'generatieve AI', definition: 'AI die nieuwe tekst, beelden, audio, code of andere inhoud kan produceren.' },
];

export const technicalStats = {
  physics: physicsConcepts.length,
  software: softwareConcepts.length,
};
