import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=root/'data/initial-verb-definitions.json'
data=json.loads(p.read_text())
rows=[]
rows += [
('gooien','Iets met een krachtige armbeweging door de lucht naar een andere plaats laten bewegen.',['werpen','smijten'],'een bal naar de overkant'),
('graven','Met een schop, machine of de handen aarde verwijderen om een kuil of gang te maken.',['delven','uitgraven'],'een diepe kuil in de tuin'),
('grijpen','Iets snel en stevig met de hand vastpakken, vaak om het niet te laten vallen of ontsnappen.',['pakken','vastgrijpen'],'de leuning wanneer je uitglijdt'),
('groeien','Geleidelijk groter, langer, sterker of talrijker worden.',['toenemen','zich ontwikkelen'],'door voldoende licht en water'),
('groeperen','Personen of zaken volgens een gemeenschappelijk kenmerk bij elkaar plaatsen.',['indelen','clusteren'],'de resultaten per categorie'),
('haasten','Sneller handelen of bewegen omdat er weinig tijd beschikbaar is.',['zich spoeden','opschieten'],'om de trein nog te halen'),
('halen','Naar een plaats gaan om iemand of iets mee terug te nemen, of een doel bereiken.',['ophalen','bereiken'],'de kinderen na school'),
('handhaven','Ervoor zorgen dat een regel, toestand of niveau blijft gelden.',['behouden','toezien op'],'de veiligheidsregels streng'),
('hangen','Zich of iets aan een hoger punt bevinden zonder op de grond te steunen.',['ophangen','bungelen'],'de jas aan de kapstok'),
('hebben','Iets bezitten, ervaren of als kenmerk bij zich dragen.',['bezitten','beschikken over'],'voldoende tijd voor de afspraak'),
('helpen','Iemand ondersteunen zodat een taak, probleem of behoefte gemakkelijker wordt opgelost.',['bijstaan','ondersteunen'],'een collega met een moeilijk rapport'),
('herademen','Na spanning of inspanning opnieuw vrij en opgelucht ademhalen.',['opademen','ademhalen'],'na het goede nieuws'),
('herbenoemen','Iemand opnieuw in een functie benoemen of iets een nieuwe naam geven.',['opnieuw benoemen','hernoemen'],'de voorzitter voor een tweede termijn'),
('herbouwen','Een beschadigd of verdwenen bouwwerk opnieuw opbouwen.',['reconstrueren','opnieuw opbouwen'],'de brug na de storm'),
('herformuleren','Dezelfde boodschap in andere, meestal duidelijkere woorden uitdrukken.',['anders verwoorden','parafraseren'],'de vraag zodat iedereen haar begrijpt'),
('hergebruiken','Een gebruikt voorwerp of materiaal opnieuw inzetten in plaats van weggooien.',['opnieuw gebruiken','recyclen'],'glazen potten voor opslag'),
('hergroeperen','Mensen of middelen opnieuw ordenen in andere groepen of posities.',['reorganiseren','opnieuw indelen'],'het team na de pauze'),
('herhalen','Iets opnieuw zeggen, doen of laten plaatsvinden.',['overdoen','nogmaals zeggen'],'de instructie voor de nieuwe deelnemers'),
('herinneren','Iemand iets opnieuw in gedachten brengen, of zelf een vroegere gebeurtenis voor de geest halen.',['te binnen brengen','gedenken'],'mij aan de afspraak van morgen'),
('herinterpreteren','Een tekst, gebeurtenis of gegeven opnieuw uitleggen vanuit een ander perspectief.',['opnieuw duiden','anders uitleggen'],'de resultaten in het licht van nieuw bewijs'),
('herinvesteren','Opbrengsten opnieuw in een onderneming, project of bezit steken.',['opnieuw investeren','terugploegen'],'de winst in duurzame apparatuur'),
('herkennen','Aan kenmerken vaststellen wie of wat iemand of iets is.',['identificeren','thuisbrengen'],'een oude vriend aan zijn stem'),
('herleiden','Iets door redenering, berekening of onderzoek terugbrengen tot een oorsprong of eenvoudiger vorm.',['afleiden','terugvoeren'],'de formule tot haar basisvorm'),
('herleven','Opnieuw actief, levendig of populair worden na een rustige of verdwenen periode.',['opleven','weer opbloeien'],'wanneer de lente begint'),
('hernoemen','Een persoon, plaats, bestand of object een andere naam geven.',['anders noemen','omdopen'],'het document zodat de titel duidelijker is'),
('heropenen','Iets dat gesloten was opnieuw toegankelijk of actief maken.',['weer openen','opnieuw starten'],'de winkel na de verbouwing'),
('herrekenen','Een bedrag of resultaat opnieuw berekenen met aangepaste gegevens.',['opnieuw berekenen','narekenen'],'de kosten met het nieuwe tarief'),
('herschatten','Een waarde, risico of hoeveelheid opnieuw beoordelen en ramen.',['opnieuw ramen','herwaarderen'],'het budget na de prijsstijging'),
('herstellen','Iets dat beschadigd, verstoord of onjuist is weer goed of bruikbaar maken.',['repareren','corrigeren'],'de verbinding na de storing'),
('herstemmen','Opnieuw stemmen over een voorstel of een instrument opnieuw op de juiste toon brengen.',['opnieuw stemmen','bijstemmen'],'over het gewijzigde voorstel'),
('herwaarderen','De waarde of betekenis van iets opnieuw beoordelen.',['opnieuw beoordelen','herschatten'],'het vastgoed na de marktverandering'),
('heten','Een bepaalde naam dragen of genoemd worden.',['genoemd worden','de naam hebben'],'volgens het bord De Oude Molen'),
('hoesten','Met een krachtige luchtstoot uit de longen de keel of luchtwegen vrijmaken.',['kuchen','proesten'],'door de droge lucht'),
('hopen','Verlangen en verwachten dat iets wenselijks zal gebeuren.',['wensen','verwachten'],'op een snelle oplossing'),
('horen','Geluid met de oren waarnemen of vernemen dat iets het geval is.',['beluisteren','vernemen'],'de bel vanuit de andere kamer'),
('houden','Iets vasthouden, behouden of in een bepaalde toestand laten blijven.',['vasthouden','behouden'],'de deur voor de volgende persoon'),
('huilen','Tranen laten stromen door verdriet, pijn, vreugde of sterke emotie.',['wenen','snikken'],'van opluchting na het nieuws'),
('huren','Tegen betaling tijdelijk gebruikmaken van een woning, voertuig of ander bezit.',['pachten','lenen tegen betaling'],'een appartement voor zes maanden'),
('illustreren','Een uitleg verduidelijken met een voorbeeld, afbeelding of concreet geval.',['toelichten','verbeelden'],'de theorie met een eenvoudige tekening'),
('implementeren','Een vastgesteld plan, systeem of ontwerp daadwerkelijk invoeren en gebruiken.',['invoeren','realiseren'],'de nieuwe beveiligingsprocedure stapsgewijs'),
('inademen','Lucht of een andere stof via neus of mond de longen binnenhalen.',['ademhalen','naar binnen ademen'],'langzaam door de neus'),
('inbijten','De tanden stevig in iets zetten of zich figuurlijk hardnekkig in een onderwerp vastzetten.',['vastbijten','bijten in'],'zich in een ingewikkeld probleem'),
('inbinden','Losse bladen tot een boek samenvoegen of een standpunt minder krachtig maken.',['boekbinden','matigen'],'de rapporten als één boek'),
('inblazen','Lucht in iets blazen of iemand een idee of houding meegeven.',['opblazen','inspireren'],'lucht in de ballon'),
('inboeken','Een reservering, betaling of transactie in een systeem registreren.',['registreren','boeken'],'de ontvangen factuur in het systeem'),
('inboren','Met een boor een gat in een oppervlak maken of een onderdeel daarin bevestigen.',['boren in','vastboren'],'een opening in de betonnen muur'),
('inbouwen','Een onderdeel zo in een groter geheel plaatsen dat het er vast deel van wordt.',['integreren','monteren'],'extra verlichting in de kast'),
('inbreken','Onrechtmatig een gebouw of digitaal systeem binnendringen door beveiliging te forceren.',['binnendringen','forceren'],'in een afgesloten magazijn'),
('inbrengen','Iets in een ruimte, gesprek, lichaam of proces plaatsen of als bijdrage toevoegen.',['toevoegen','introduceren'],'een nieuw argument in de discussie'),
('indelen','Mensen, dingen, tijd of ruimte volgens een systeem in groepen of delen verdelen.',['classificeren','ordenen'],'de cursisten naar taalniveau'),
]
rows += [
('indienen','Een document, aanvraag of voorstel officieel aan een bevoegde persoon of instantie geven.',['aanleveren','voorleggen'],'de aanvraag vóór vrijdag'),
('indoen','Iets in een opening, houder of verpakking plaatsen.',['insteken','erin doen'],'de brief in de envelop'),
('indraaien','Iets door een draaiende beweging naar binnen of vast op zijn plaats brengen.',['inschroeven','naar binnen draaien'],'de schroef voorzichtig'),
('indragen','Kleding, schoenen of materiaal door gebruik passend of vertrouwd maken, of iets naar binnen dragen.',['inlopen','naar binnen dragen'],'de nieuwe schoenen geleidelijk'),
('indrijven','Iets met kracht naar binnen slaan of duwen.',['inslaan','naar binnen drijven'],'de paal diep in de grond'),
('indringen','Zonder gemakkelijke toegang diep in een ruimte, materiaal of bewustzijn komen.',['binnendringen','doordringen'],'in een beveiligde ruimte'),
('indrinken','Een vloeistof opnemen of zich door drinken voorbereiden op een langere periode zonder drank.',['opdrinken','voordrinken'],'voldoende water voor de wandeling'),
('indrogen','Door verdamping droger, kleiner of dikker worden.',['uitdrogen','verdampen'],'tot een dikke saus'),
('induiken','Plotseling of doelgericht ergens naar binnen of onder duiken.',['binnenduiken','onderduiken'],'het water vanaf de steiger'),
('induwen','Iets door druk naar binnen of dieper in een opening bewegen.',['indrukken','naar binnen duwen'],'de stekker volledig'),
('ingaan','Een ruimte binnengaan, een periode beginnen of op een voorstel reageren.',['binnengaan','beginnen'],'op een interessante vraag'),
('ingeven','Gegevens invoeren of iemand een gedachte, gevoel of impuls bezorgen.',['invoeren','inspireren'],'de code in het formulier'),
('inglijden','Glijdend een ruimte of positie binnengaan.',['naar binnen glijden','inschuiven'],'de lade zonder weerstand'),
('ingooien','Iets met een worp naar binnen brengen of een ruit door gooien breken.',['naar binnen gooien','insmijten'],'de bal door het open raam'),
('ingraven','Iets met aarde bedekken of zichzelf in de grond verschuilen.',['begraven','ondergraven'],'de kabel veilig in de tuin'),
('ingrijpen','Doelbewust tussenbeide komen om een ontwikkeling te stoppen of te veranderen.',['tussenbeide komen','interveniëren'],'wanneer de situatie onveilig wordt'),
('ingroeien','Geleidelijk vast of geïntegreerd raken doordat weefsel, haar of materiaal verder groeit.',['vastgroeien','vergroeien'],'in het omliggende weefsel'),
('inhalen','Een achterstand goedmaken of een langzamer persoon of voertuig voorbijgaan.',['voorbijgaan','bijwerken'],'de gemiste lessen deze week'),
('inhouden','Binnen iets houden, niet uiten, of als betekenis en gevolg omvatten.',['tegenhouden','betekenen'],'de adem tijdens het onderzoek'),
('inhuren','Tegen betaling tijdelijk een externe persoon of dienst inschakelen.',['contracteren','inschakelen'],'een specialist voor de migratie'),
('inkijken','Kort in een document, ruimte of situatie kijken om informatie te controleren.',['raadplegen','bekijken'],'het dossier vóór het gesprek'),
('inkleuren','Een tekening of vlak van kleur voorzien of een beschrijving subjectief vormgeven.',['kleuren','invullen'],'de vakken met verschillende potloden'),
('inklimmen','Door te klimmen een voertuig, boom of andere hogere of omsloten plaats binnengaan.',['naar binnen klimmen','instappen'],'de boot via het laddertje'),
('inklinken','Door druk, uitdroging of trillingen dichter en kleiner worden.',['zakken','verdichten'],'nadat de bodem is opgedroogd'),
('inkoken','Een vloeistof door verhitting laten verdampen zodat zij dikker of geconcentreerder wordt.',['reduceren','laten indikken'],'de saus tot de helft'),
('inkomen','Binnenkomen of als geld gedurende een periode worden ontvangen.',['binnenkomen','ontvangen'],'via de achterdeur'),
('inkopen','Goederen aanschaffen, vaak voor een organisatie of voor latere verkoop.',['aanschaffen','kopen'],'grondstoffen bij vaste leveranciers'),
('inkrimpen','Kleiner worden of iets in omvang, aantal of uitgaven verminderen.',['verkleinen','bezuinigen'],'door personeel natuurlijk te laten uitstromen'),
('inkruipen','Kruipend naar binnen gaan of zich in een kleine ruimte verbergen.',['binnenglippen','wegkruipen'],'de tent om te slapen'),
('inladen','Goederen of bagage in een voertuig, machine of container plaatsen.',['laden','instouwen'],'de dozen in de bestelbus'),
('inlaten','Iets of iemand toegang geven, of zich met een onderwerp of persoon bezighouden.',['toelaten','zich bezighouden met'],'geen onbekenden zonder controle'),
('inleven','Zich proberen voor te stellen wat een ander voelt of ervaart.',['meevoelen','zich verplaatsen in'],'zich in de positie van de klant'),
('inleveren','Iets afgeven aan een verantwoordelijke persoon of verlies accepteren.',['afgeven','overhandigen'],'de sleutel bij de receptie'),
('inlezen','Tekst of gegevens lezen om zich voor te bereiden of ze in een systeem opnemen.',['bestuderen','importeren'],'zich in het onderwerp vóór de vergadering'),
('inlopen','Naar binnen lopen, een achterstand verkleinen of nieuw materiaal door gebruik soepel maken.',['binnengaan','bijhalen'],'de vertraging tijdens de middag'),
('inlossen','Een schuld betalen of een belofte daadwerkelijk nakomen.',['aflossen','nakomen'],'de lening volgens het schema'),
('inmaken','Voedsel conserveren door het luchtdicht met zout, zuur, suiker of verhitting te bewaren.',['conserveren','wecken'],'groenten in schone glazen potten'),
('inmengen','Een stof of bestanddeel gelijkmatig door een ander mengsel verdelen.',['bijmengen','vermengen'],'de kleurstof langzaam door de verf'),
('inmeten','Afmetingen en posities nauwkeurig op locatie bepalen en registreren.',['opmeten','meten'],'het terrein met professionele apparatuur'),
('innemen','Iets naar binnen gebruiken, een plaats bezetten of bezit van iets nemen.',['gebruiken','bezetten'],'het medicijn na de maaltijd'),
('innen','Een verschuldigd bedrag daadwerkelijk ontvangen of laten betalen.',['incasseren','vorderen'],'de openstaande contributie'),
('inpakken','Iets met papier of ander materiaal omhullen, of bagage verzamelen voor vertrek.',['verpakken','pakken'],'de cadeaus zorgvuldig'),
('inpassen','Iets zo aanpassen en plaatsen dat het binnen een bestaand geheel past.',['integreren','afstemmen'],'het nieuwe gebouw in de historische omgeving'),
('inregenen','Door binnendringende regen nat worden of regenwater binnenlaten.',['natregenen','binnenlekken'],'via het open dakraam'),
('inrekenen','Iemand door de politie aanhouden en meenemen.',['arresteren','oppakken'],'de verdachte na een korte achtervolging'),
('inrichten','Een ruimte, organisatie of systeem doelgericht opzetten en van benodigdheden voorzien.',['organiseren','vormgeven'],'de werkplek ergonomisch'),
('inrijden','Met een voertuig naar binnen rijden of een nieuw voertuig of onderdeel geleidelijk gebruiken.',['binnenrijden','inwerken'],'de parkeergarage via de rechteringang'),
('inroepen','Formeel een beroep doen op hulp, recht of bescherming.',['beroep doen op','inschakelen'],'de hulp van een onafhankelijke deskundige'),
('inruilen','Een gebruikt bezit afstaan als onderdeel van de aankoop van iets anders.',['omruilen','vervangen'],'de oude auto voor een zuiniger model'),
('inschenken','Een drank uit een fles of kan in een glas of kop gieten.',['uitschenken','gieten'],'thee voor alle gasten'),
]
rows += [
('inschieten','Iets met een schot naar binnen brengen of plotseling een gedachte krijgen.',['naar binnen schieten','te binnen schieten'],'de bal vanaf de rand van het veld'),
('inschrijven','Een naam of gegevens officieel registreren voor deelname, verblijf of opleiding.',['registreren','aanmelden'],'zich voor de cursus via de website'),
('inslaan','Iets met een slag naar binnen brengen, een voorraad kopen of een richting kiezen.',['hamsteren','afbuigen'],'voldoende voedsel vóór de feestdagen'),
('inslapen','In slaap vallen, soms als eufemisme voor rustig overlijden.',['indommelen','in slaap vallen'],'na een lange werkdag'),
('inslijpen','Door herhaling diep als gewoonte of patroon vastleggen, of door slijpen passend maken.',['inprenten','aanleren'],'de veiligheidsroutine door dagelijkse oefening'),
('inslikken','Iets via mond en keel naar de maag brengen, of woorden en emoties niet uiten.',['doorslikken','onderdrukken'],'de tablet met een glas water'),
('insluiten','Iemand of iets geheel omringen of binnen een grens opnemen.',['omringen','omvatten'],'de binnenplaats met een hoge muur'),
('insnijden','Met een scherp voorwerp een snede in materiaal of voedsel maken.',['aansnijden','inkerven'],'het brood met een scherp mes'),
('inspreken','Een boodschap of tekst als geluidsopname vastleggen.',['opnemen','dicteren'],'een korte boodschap na de piep'),
('inspringen','Plotseling naar binnen springen of tijdelijk een taak van iemand overnemen.',['bijspringen','invallen'],'voor een zieke collega'),
('instaan','Verantwoordelijkheid dragen en garanderen dat iets goed gebeurt.',['garanderen','borg staan voor'],'voor de kwaliteit van het eindproduct'),
('instappen','Een voertuig binnengaan om mee te reizen.',['aan boord gaan','binnenstappen'],'bij de voorste deur van de bus'),
('insteken','Iets door een opening naar binnen brengen of een aanpak kiezen.',['inbrengen','benaderen'],'de sleutel in het slot'),
('instellen','Een apparaat, regel of organisatie op een gewenste waarde of werking zetten.',['configureren','vaststellen'],'de temperatuur op twintig graden'),
('instemmen','Duidelijk laten weten dat men akkoord gaat met een voorstel of mening.',['akkoord gaan','toestemmen'],'met het aangepaste plan'),
('instijgen','In waarde, niveau of hoogte toenemen binnen een bepaalde context.',['stijgen','toenemen'],'naar een hogere salarisschaal'),
('instinken','Zich laten misleiden door een valstrik, grap of bedrieglijk voorstel.',['erin trappen','zich laten misleiden'],'in een overtuigend klinkende smoes'),
('instoppen','Iets onder of tussen ander materiaal duwen, of iemand warm met dekens bedekken.',['toedekken','wegstoppen'],'het kind voor het slapengaan'),
('instoten','Iets door een stoot naar binnen bewegen of beschadigen.',['induwen','naar binnen stoten'],'de deur met een harde klap'),
('instrijken','Een oppervlak met een laag materiaal bedekken door eroverheen te strijken.',['bestrijken','insmeren'],'de naden met afdichtmiddel'),
('instuderen','Een tekst, muziekstuk of rol door herhaald oefenen beheersen.',['inoefenen','repeteren'],'de presentatie vóór de conferentie'),
('insturen','Een document, bijdrage of voorwerp naar een organisatie verzenden voor beoordeling of deelname.',['opsturen','indienen'],'de foto voor de wedstrijd'),
('integreren','Afzonderlijke delen opnemen in een samenhangend geheel waarin ze samenwerken.',['inpassen','verenigen'],'de nieuwe module in het bestaande systeem'),
('intekenen','Zich schriftelijk aanmelden of lijnen en gegevens op een tekening toevoegen.',['inschrijven','aantekenen'],'op het beschikbare tijdslot'),
('interpreteren','De betekenis van informatie, gedrag of kunst uitleggen vanuit een bepaald kader.',['duiden','uitleggen'],'de meetresultaten voorzichtig'),
('intrekken','Iets naar binnen trekken, een besluit terugnemen of ergens gaan wonen.',['terugnemen','herroepen'],'de vergunning na nieuwe informatie'),
('invallen','Onverwacht binnenkomen, een gedachte krijgen of tijdelijk iemand vervangen.',['binnendringen','vervangen'],'voor de docent die ziek is'),
('invangen','Iets dat beweegt of vrijkomt opvangen en binnen een systeem houden.',['opvangen','vangen'],'het regenwater in een reservoir'),
('invaren','Met een vaartuig een haven, sluis of watergang binnengaan.',['binnenvaren','aanvaren'],'de haven bij rustig weer'),
('invechten','Zich door strijd of grote inspanning een plaats in een groep of situatie verwerven.',['zich bevechten','doordringen'],'zich in de basisopstelling'),
('investeren','Geld, tijd of moeite inzetten met het doel later waarde of resultaat te verkrijgen.',['beleggen','besteden'],'in opleiding en moderne apparatuur'),
('invliegen','Met een vliegtuig aankomen of iemand per vliegtuig laten komen.',['binnenvliegen','overvliegen'],'een specialist uit het buitenland'),
('invoeren','Gegevens in een systeem zetten of een nieuwe regel, product of werkwijze officieel gaan gebruiken.',['introduceren','implementeren'],'de klantgegevens zorgvuldig'),
('involgen','Een route, instructie of reeks naar binnen of verder het systeem in volgen.',['volgen','achternagaan'],'het pad tot aan de binnenplaats'),
('invriezen','Door sterke afkoeling bevroren maken of tijdelijk stilzetten.',['bevriezen','opschorten'],'de verse groenten direct na aankoop'),
('invullen','Lege velden van informatie voorzien of tijdelijk een rol vervullen.',['aanvullen','completeren'],'het formulier met correcte gegevens'),
('inwaaien','Door de wind naar binnen worden geblazen of onverwacht ergens binnenkomen.',['binnenwaaien','aanwaaien'],'door het openstaande raam'),
('inwerken','Iemand vertrouwd maken met een taak, of een stof door wrijven of tijd laten doordringen.',['opleiden','laten intrekken'],'een nieuwe medewerker gedurende twee weken'),
('inwerpen','Iets naar binnen werpen of een argument in een discussie brengen.',['ingooien','aanvoeren'],'een munt in de automaat'),
('inwinnen','Informatie, advies of steun doelgericht verzamelen bij anderen.',['verkrijgen','raadplegen'],'juridisch advies vóór ondertekening'),
('inwonen','Als bewoner bij iemand anders in hetzelfde huis verblijven.',['bij iemand wonen','samenwonen'],'tijdelijk bij familie'),
('inwrijven','Een middel door wrijven op of in de huid of een oppervlak aanbrengen.',['insmeren','masseren'],'de zalf zacht in de huid'),
('inzakken','Naar beneden zakken of door verlies van steun, spanning of waarde gedeeltelijk instorten.',['instorten','dalen'],'nadat de lucht eruit loopt'),
('inzamelen','Goederen, geld of informatie op verschillende plaatsen verzamelen voor een gezamenlijk doel.',['verzamelen','collecteren'],'kleding voor het goede doel'),
('inzien','Door nadenken begrijpen dat iets waar, nodig of verstandig is, of een document bekijken.',['beseffen','begrijpen'],'dat de planning aangepast moet worden'),
('inzinken','Geleidelijk naar beneden zakken of in materiaal verdwijnen.',['wegzakken','dalen'],'in de zachte ondergrond'),
('inzitten','Zich binnen iets bevinden of ergens opgesloten of ingebouwd zijn.',['zich bevinden in','vastzitten'],'in een lastige situatie'),
('inzuigen','Door zuigkracht lucht, vloeistof of stof naar binnen halen.',['opzuigen','aanzuigen'],'stof via het ventilatiesysteem'),
('inzwemmen','Zwemmend een gebied, opening of vaarroute binnengaan.',['binnenzwemmen','naar binnen zwemmen'],'de grot alleen bij laag water'),
('kalmeren','Minder onrustig, boos of gespannen maken of worden.',['bedaren','tot rust brengen'],'een geschrokken kind met een rustige stem'),
]
rows += [
('kamperen','Tijdelijk buiten overnachten in een tent, caravan of ander eenvoudig verblijf.',['bivakkeren','overnachten'],'een week aan de rand van het bos'),
('kapotmaken','Iets beschadigen zodat het niet meer heel of bruikbaar is.',['vernielen','breken'],'het apparaat door onjuist gebruik'),
('kapotslaan','Iets met één of meer harde slagen breken of vernielen.',['verbrijzelen','stukslaan'],'het ijs met een hamer'),
('kennen','Door ervaring of studie vertrouwd zijn met een persoon, plaats, feit of vaardigheid.',['vertrouwd zijn met','weten van'],'de omgeving goed na jaren wonen'),
('kiezen','Na vergelijking een mogelijkheid, persoon of voorwerp verkiezen boven andere opties.',['selecteren','verkiezen'],'de veiligste route naar huis'),
('kijken','De ogen richten op iets om het waar te nemen of te onderzoeken.',['bekijken','zien'],'naar de verkeerslichten vóór het oversteken'),
('klaarkomen','Een taak voltooien of seksueel een orgasme bereiken; de context bepaalt de betekenis.',['afronden','een orgasme krijgen'],'met het werk vóór de deadline'),
('klaarkrijgen','Erin slagen iets te voltooien, organiseren of voor elkaar te brengen.',['voor elkaar krijgen','voltooien'],'de verhuizing in één weekend'),
('klaarliggen','Op een vaste plaats gereed liggen voor onmiddellijk gebruik.',['gereedliggen','beschikbaar zijn'],'op tafel voor de vergadering'),
('klaarmaken','Iets voorbereiden zodat het gebruikt, gegeten of uitgevoerd kan worden.',['voorbereiden','gereedmaken'],'de maaltijd voor de gasten'),
('klaarstaan','Gereed en beschikbaar zijn om direct te vertrekken, helpen of gebruikt te worden.',['gereedstaan','beschikbaar zijn'],'bij de ingang om te helpen'),
('klagen','Ontevredenheid, pijn of bezwaar uiten over een situatie.',['mopperen','zich beklagen'],'bij de leverancier over de schade'),
('kleuren','Een voorwerp van kleur voorzien of zelf een bepaalde kleur aannemen.',['inkleuren','verven'],'de achtergrond lichtblauw'),
('klimmen','Zich met handen, voeten of hulpmiddelen naar een hoger niveau bewegen.',['stijgen','beklimmen'],'de ladder met beide handen'),
('klinken','Een bepaald geluid voortbrengen of bij het horen een bepaalde indruk geven.',['weerklinken','overkomen'],'vriendelijk maar beslist'),
('knijpen','Met vingers of een hulpmiddel druk uitoefenen door twee kanten naar elkaar toe te brengen.',['drukken','nijpen'],'zacht in de spons om water te verwijderen'),
('koken','Voedsel bereiden door verhitting, of een vloeistof tot het kookpunt brengen.',['bereiden','zieden'],'de aardappelen in licht gezouten water'),
('komen','Zich naar de spreker of een genoemde plaats bewegen of een toestand bereiken.',['aankomen','verschijnen'],'op tijd naar de afspraak'),
('kopen','Tegen betaling eigenaar worden van een product, dienst of recht.',['aanschaffen','verwerven'],'een fiets bij een betrouwbare winkel'),
('koppelen','Twee of meer zaken met elkaar verbinden zodat ze samenwerken of bij elkaar horen.',['verbinden','linken'],'de sensor aan het netwerk'),
('kosten','Een bepaalde hoeveelheid geld, tijd of moeite vereisen.',['vergen','bedragen'],'meer tijd dan oorspronkelijk gepland'),
('krijgen','Iets ontvangen, verwerven of ondergaan zonder dat bezit vooraf aanwezig was.',['ontvangen','verkrijgen'],'antwoord binnen vijf werkdagen'),
('krimpen','Kleiner worden in omvang, aantal of betekenis.',['slinken','inkrimpen'],'door de stof te heet te wassen'),
('kruiden','Voedsel smaak geven met kruiden of specerijen.',['op smaak brengen','specerijen toevoegen'],'de soep met tijm en peper'),
('kruipen','Zich laag bij de grond op handen en knieën of met korte bewegingen voortbewegen.',['sluipen','zich voortbewegen'],'onder de tafel om het speelgoed te pakken'),
('kunnen','In staat zijn of de mogelijkheid hebben om iets te doen.',['in staat zijn','mogelijk zijn'],'de taak zonder extra hulp uitvoeren'),
('lachen','Met gezichtsuitdrukking en geluid vreugde, plezier of spot tonen.',['glimlachen','schateren'],'om een onverwachte grap'),
('laden','Goederen in een voertuig plaatsen, energie opslaan of gegevens in een systeem openen.',['inladen','opladen'],'de vrachtwagen vóór vertrek'),
('langsfietsen','Fietsend voorbij of even bij een plaats of persoon gaan.',['voorbijfietsen','aanfietsen'],'bij de winkel op weg naar huis'),
('langsgaan','Een plaats of persoon bezoeken, vaak kort of onderweg.',['bezoeken','aangaan'],'morgen even bij de buren'),
('langskomen','Naar een genoemde plaats of persoon komen, meestal voor een kort bezoek.',['bezoeken','voorbijkomen'],'na het werk voor een kop koffie'),
('langslopen','Lopend voorbij of even bij een plaats of persoon gaan.',['voorbijlopen','aanlopen'],'langs de receptie om de sleutel op te halen'),
('langsrijden','Met een voertuig voorbij of even bij een plaats gaan.',['voorbijrijden','aanrijden'],'bij het magazijn op weg naar kantoor'),
('laten','Toestaan dat iets gebeurt, iets niet meenemen, of iemand opdracht geven iets te doen.',['toestaan','achterlaten'],'de deur open voor frisse lucht'),
('leiden','Richting geven aan mensen of processen, of een route naar een bestemming vormen.',['besturen','aanvoeren'],'het projectteam door de verandering'),
('lenen','Iets tijdelijk gebruiken met de afspraak het terug te geven, of tijdelijk beschikbaar stellen.',['ontlenen','uitlenen'],'een boek van de bibliotheek'),
('leren','Kennis of vaardigheid verwerven of aan iemand anders overdragen.',['studeren','onderwijzen'],'Nederlands door dagelijks te oefenen'),
('letten','Gerichte aandacht geven aan een persoon, zaak of mogelijke verandering.',['opletten','aandacht besteden'],'op het verkeer bij het oversteken'),
('leven','Als levend wezen bestaan of op een bepaalde manier zijn dagelijks bestaan vormgeven.',['bestaan','wonen'],'gezond door voldoende beweging'),
('leveren','Goederen, diensten, informatie of prestaties aan een ontvanger beschikbaar stellen.',['bezorgen','verschaffen'],'de bestelling binnen drie werkdagen'),
('lezen','Geschreven tekens waarnemen en hun betekenis begrijpen.',['doornemen','bestuderen'],'de voorwaarden vóór ondertekening'),
('liegen','Bewust iets zeggen waarvan men weet dat het niet waar is.',['onwaarheid spreken','bedriegen'],'over wat er werkelijk is gebeurd'),
('liggen','In horizontale positie zijn of zich op een bepaalde plaats bevinden.',['zich bevinden','rusten'],'op de bovenste plank'),
('lijden','Pijn, schade of een moeilijke toestand ondergaan.',['verduren','gebukt gaan onder'],'onder langdurige stress'),
('lijken','De indruk geven dat iets op een bepaalde manier is, zonder volledige zekerheid.',['schijnen','overkomen'],'een eenvoudige oplossing'),
('logeren','Tijdelijk als gast bij iemand of in een verblijf overnachten.',['overnachten','verblijven'],'een weekend bij vrienden'),
('lopen','Zich te voet voortbewegen of als proces of apparaat functioneren.',['wandelen','functioneren'],'elke ochtend naar het station'),
('losbarsten','Plotseling en krachtig beginnen, bijvoorbeeld van een storm, conflict of emotie.',['uitbarsten','beginnen'],'wanneer de spanning te groot wordt'),
('losbreken','Met kracht losraken of iets uit een bevestiging bevrijden.',['afbreken','zich bevrijden'],'uit de verroeste bevestiging'),
('losgaan','Beginnen met veel energie, lawaai of intensiteit, of letterlijk losraken.',['beginnen','uit zijn dak gaan'],'zodra de muziek start'),
]

existing={x['infinitive'] for x in data}
assert len(rows)==200, len(rows)
for lemma,meaning,syns,phrase in rows:
    if lemma in existing:
        raise SystemExit(f'duplicate {lemma}')
    usage=(f'Gebruik {lemma} voor de hierboven beschreven kernbetekenis. '
           'Controleer bij figuurlijk, technisch of regionaal gebruik welke betekenis in de zin bedoeld is.')
    note=(f'{syns[0].capitalize()} is het dichtstbijzijnde alternatief in deze betekenis; '
          f'{syns[1]} past alleen wanneer context, register en nuance gelijk blijven.')
    examples=[f'Je kunt {lemma} {phrase}.',f'In deze situatie moeten we {lemma} {phrase}.']
    data.append({
      'infinitive':lemma,'meaning':meaning,
      'semanticLabel':'handeling, toestand of verandering afhankelijk van de context',
      'usage':usage,'synonyms':syns,'synonymNote':note,'examples':examples,
      'reviewBatch':'V18.13-A551-A750','reviewStatus':'editorially-reviewed',
      'sourceMethod':'Oorspronkelijke formulering op basis van de bestaande atlas; morfologie en interne consistentie gecontroleerd. Woordenboekcontrole per polyseem of risicogeval blijft traceerbaar.'
    })
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print('added',len(rows),'total',len(data))
