import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
source=root/'js/verb-atlas.js'
s=source.read_text()
atlas=json.loads(s[s.index('['):s.rindex(']')+1])
p=root/'data/initial-verb-definitions.json'
data=json.loads(p.read_text())
existing={x['infinitive'] for x in data}
core=json.loads((root/'data/core-verb-definitions.json').read_text())
reviewed=existing|{x['infinitive'] for x in core}
# Keep the exact next 200 atlas lemmas not represented in the two review datasets.
batch=[v['infinitive'] for v in atlas if v['infinitive'] not in reviewed and v['infinitive'] not in {'aandoen','aannemen'}][:200]
assert batch[0]=='onderlopen' and batch[-1]=='overvallen', (batch[0],batch[-1],len(batch))

SPECIAL={
'aandoen':('Kleding of een accessoire aantrekken; daarnaast iemand emotioneel raken of een plaats kort bezoeken.',['aantrekken','raken'],'een jas aantrekken of iemand emotioneel raken'),
'aannemen':('Iets ontvangen, accepteren of voor waar houden; ook iemand in dienst nemen.',['accepteren','veronderstellen'],'een aanbod accepteren of een medewerker in dienst nemen'),
'lukken':('Met succes gebeuren of het gewenste resultaat opleveren.',['slagen','gelukken'],'een gewenst resultaat bereiken'),
'lunchen':('Rond het midden van de dag een maaltijd gebruiken.',['middageten','de lunch gebruiken'],'een middagmaaltijd gebruiken'),
'mailen':('Een bericht via e-mail verzenden of per e-mail contact opnemen.',['e-mailen','schrijven'],'een digitaal bericht verzenden'),
'markeren':('Iets zichtbaar aanduiden, kenmerken of als belangrijk aangeven.',['aanduiden','accentueren'],'een belangrijk onderdeel zichtbaar aanduiden'),
'matigen':('Iets minder sterk, hevig of omvangrijk maken, of zichzelf beperken.',['verminderen','temperen'],'de intensiteit of hoeveelheid beperken'),
'melden':('Informatie officieel of duidelijk doorgeven, of zich ergens aanmelden.',['rapporteren','berichten'],'informatie aan de juiste persoon doorgeven'),
'mengen':('Twee of meer stoffen, groepen of elementen door elkaar brengen.',['vermengen','combineren'],'verschillende bestanddelen door elkaar brengen'),
'meten':('Met een instrument of methode de grootte, hoeveelheid of waarde van iets bepalen.',['opmeten','bepalen'],'een lengte, hoeveelheid of waarde bepalen'),
'miauwen':('Het kenmerkende geluid van een kat voortbrengen.',['mauwen','roepen'],'het geluid van een kat maken'),
'migreren':('Van woonplaats, land, systeem of omgeving naar een andere overgaan.',['verhuizen','overzetten'],'naar een andere plaats of technisch systeem overgaan'),
'misleiden':('Iemand bewust een onjuiste indruk geven zodat die een verkeerde conclusie trekt.',['bedriegen','misinformeren'],'iemand bewust op het verkeerde spoor zetten'),
'mislukken':('Niet het beoogde resultaat bereiken of verkeerd aflopen.',['falen','niet slagen'],'zonder het gewenste resultaat eindigen'),
'missen':('Niet aanwezig hebben, niet raken of het ontbreken van iemand of iets voelen.',['ontberen','voorbijschieten'],'iets niet hebben, niet raken of sterk voelen ontbreken'),
'mitigeren':('De ernst, impact of waarschijnlijkheid van een risico of probleem verminderen.',['beperken','verzachten'],'de gevolgen van een risico verminderen'),
'moeten':('Door noodzaak, verplichting of sterke verwachting gehouden zijn iets te doen.',['verplicht zijn','nodig zijn'],'een noodzakelijke of verplichte handeling uitdrukken'),
'mogen':('Toestemming hebben of krijgen om iets te doen; soms ook een mogelijkheid uitdrukken.',['toestemming hebben','kunnen'],'toestemming of een voorzichtige mogelijkheid uitdrukken'),
'monitoren':('Een proces, systeem of situatie gedurende een periode systematisch volgen en controleren.',['bewaken','volgen'],'ontwikkelingen systematisch volgen'),
'monteren':('Onderdelen volgens een ontwerp samenvoegen of een apparaat op een plaats bevestigen.',['assembleren','bevestigen'],'onderdelen samenvoegen of bevestigen'),
'naaien':('Stof of ander materiaal met draad en naald verbinden; informeel ook bedriegen of seksueel handelen.',['stikken','hechten'],'stof met draad verbinden'),
'niezen':('Plotseling lucht krachtig door neus en mond uitstoten door prikkeling van het neusslijmvlies.',['proesten','een nies geven'],'door een prikkel krachtig lucht uitstoten'),
'noemen':('Een naam geven, bij naam vermelden of als voorbeeld of kenmerk aangeven.',['benoemen','vermelden'],'een naam of aanduiding geven'),
'normaliseren':('Iets volgens een norm, standaard of gewone toestand brengen.',['standaardiseren','regulariseren'],'iets aan een norm of normale toestand aanpassen'),
'noteren':('Informatie kort opschrijven of registreren zodat zij bewaard blijft.',['opschrijven','vastleggen'],'informatie schriftelijk vastleggen'),
'nuanceren':('Een uitspraak of beeld preciezer maken door verschillen, beperkingen of uitzonderingen toe te voegen.',['verfijnen','relativeren'],'een uitspraak preciezer en minder absoluut maken'),
'oefenen':('Een handeling herhaald uitvoeren om vaardigheid, kennis of conditie te verbeteren.',['trainen','praktiseren'],'door herhaling beter worden'),
}

ROOT_GLOSS={
'gooien':'werpen','komen':'zich verplaatsen en aankomen','laten':'toestaan of achterlaten','lopen':'zich te voet bewegen','maken':'vervaardigen of in een toestand brengen','schieten':'snel bewegen of met een projectiel treffen','lossen':'vrijmaken, uitladen of oplossen','slaan':'met kracht raken','springen':'een sprong maken','trekken':'door kracht naar zich toe of in een richting bewegen','brengen':'naar een plaats vervoeren','delen':'informatie of bezit met anderen verdelen','denken':'gedachten vormen','doen':'handelen of deelnemen','draaien':'roteren of functioneren','dragen':'ondersteunen of vervoeren','drijven':'op water bewegen of voortgestuwd worden','drinken':'vloeistof innemen','gaan':'zich verplaatsen of deelnemen','geven':'overhandigen of verschaffen','helpen':'ondersteunen','kijken':'met de ogen waarnemen','krijgen':'ontvangen','kunnen':'in staat zijn','leven':'emotioneel betrokken zijn','lezen':'geschreven tekst begrijpen','luisteren':'aandachtig geluid waarnemen','regeren':'besturen','reizen':'een verplaatsing over afstand maken','rekenen':'berekenen','rijden':'zich met een voertuig verplaatsen','schrijven':'tekst maken','spreken':'mondeling communiceren','strijden':'vechten of zich inzetten','tellen':'aantallen bepalen of meetellen','vallen':'naar beneden bewegen of uitpakken','varen':'zich per vaartuig verplaatsen','vechten':'fysiek of figuurlijk strijden','voelen':'een lichamelijke of emotionele gewaarwording hebben','voeren':'meenemen, leiden of transporteren','vragen':'om informatie of deelname verzoeken','wandelen':'te voet ontspannen bewegen','wegen':'gewicht of belang bepalen','werken':'arbeid verrichten of functioneren','willen':'een wens of bereidheid hebben','zingen':'muzikale tonen met de stem maken','zitten':'zich in zittende houding bevinden of gunstig verlopen','bestellen':'een product aanvragen','blijven':'op dezelfde plaats of in dezelfde toestand zijn','fluiten':'een hoge toon maken','houden':'bewaren of vasthouden','leven':'volgens regels handelen','schilderen':'met verf afbeelden','synchroniseren':'in tijd gelijk laten lopen','tekenen':'lijnen of een afbeelding maken','vertellen':'mondeling verslag doen','volgen':'achter iemand of iets gaan of zich eraan houden','zien':'waarnemen','zoeken':'proberen te vinden','buigen':'krommen of van richting veranderen','dalen':'naar beneden gaan','duwen':'met druk verplaatsen','halen':'naar beneden brengen of verwijderen','hangen':'zonder steun naar beneden hangen','liggen':'horizontaal zijn','steken':'met een puntig voorwerp prikken of plaatsen','strijken':'zacht landen of over een oppervlak bewegen','werpen':'gooien','zakken':'naar beneden bewegen','bouwen':'construeren','brengen':'vervoeren','roepen':'luid spreken of uitzenden','roeren':'door een vloeistof bewegen','ruilen':'het ene voor het andere geven','smelten':'door warmte vloeibaar worden','spelen':'een spel uitvoeren','spellen':'letters afzonderlijk noemen','stoten':'met een korte krachtige beweging raken','varen':'met een vaartuig reizen','vliegen':'door de lucht bewegen','waaien':'door wind bewegen','werken':'bewerken of aanpassen','zetten':'plaatsen of omvormen','betalen':'geld geven','binden':'vastmaken','drukken':'kracht uitoefenen of onder controle houden','duiken':'onder water of uit zicht gaan','graven':'grond verwijderen','handelen':'overleggen om overeenstemming te bereiken','huren':'tegen betaling tijdelijk gebruiken'
}

# Explicit nuances for prefixed verbs where a generic compositional reading is unsafe.
EX={
'losgooien':('Door te gooien of een bevestiging los te maken vrij laten komen.',['losmaken','vrijgooien']),
'loskomen':('Niet langer vastzitten of zich van een plaats, persoon of situatie bevrijden.',['vrijkomen','losraken']),
'loslaten':('Niet langer vasthouden, toestaan weg te gaan of mentaal afstand nemen.',['vrijlaten','laten gaan']),
'loslopen':('Niet vastgebonden rondlopen of tijdens het bewegen losraken.',['vrij rondlopen','losraken']),
'losmaken':('Een verbinding of bevestiging openen zodat iets niet langer vastzit.',['ontkoppelen','vrijmaken']),
'losschieten':('Plotseling losraken of snel wegschieten vanuit een bevestiging.',['losraken','wegschieten']),
'lossen':('Een lading uitladen, een schot afvuren of een verplichting/inlossing uitvoeren.',['uitladen','aflossen']),
'losslaan':('Door slaan losmaken of zelf door kracht losraken.',['losmaken','afbreken']),
'losspringen':('Door een sprong of plotselinge beweging uit een bevestiging loskomen.',['loskomen','wegspringen']),
'lostrekken':('Iets met trekkracht uit een bevestiging of samenhang losmaken.',['uittrekken','losrukken']),
'meebrengen':('Iemand of iets bij vertrek meenemen naar de plaats waar men naartoe gaat.',['meenemen','aanvoeren']),
'meedelen':('Informatie aan iemand bekendmaken; daarnaast iets samen met anderen verdelen.',['berichten','bekendmaken']),
'meedenken':('Actief samen met anderen nadenken over een probleem of oplossing.',['overleggen','bijdragen']),
'meedoen':('Samen met anderen aan een activiteit deelnemen.',['deelnemen','participeren']),
'meedraaien':('Samen met een team of systeem functioneren en aan het gewone werk deelnemen.',['meewerken','participeren']),
'meedragen':('Samen een last dragen of verantwoordelijkheid helpen dragen.',['ondersteunen','bijdragen']),
'meedrijven':('Met dezelfde stroming of beweging als iets anders voortbewegen.',['afdrijven','meevoeren']),
'meedrinken':('Samen met anderen drinken of deelnemen aan een drinkmoment.',['drinken','deelnemen']),
'meegaan':('Samen met iemand vertrekken of instemmen met een voorstel of redenering.',['vergezellen','instemmen']),
'meegeven':('Iets aan iemand geven om mee te nemen, of een boodschap/kwaliteit overdragen.',['overhandigen','bijbrengen']),
'meehelpen':('Samen met anderen hulp bieden bij een taak.',['bijstaan','assisteren']),
'meekijken':('Samen kijken of iemands handelingen observeren om te volgen of leren.',['observeren','toekijken']),
'meekomen':('Samen met iemand naar dezelfde bestemming komen.',['vergezellen','meegaan']),
'meekrijgen':('Iets ontvangen om mee te nemen, of iemand overtuigen mee te doen.',['ontvangen','overtuigen']),
'meekunnen':('In staat of toegestaan zijn om samen met anderen mee te gaan of deel te nemen.',['kunnen deelnemen','mee mogen']),
'meeleven':('Emotioneel betrokken zijn bij wat iemand anders ervaart.',['meeleven met','sympathiseren']),
'meelezen':('Tegelijk met iemand anders een tekst lezen of inzage hebben in berichten.',['volgen','inzien']),
'meelopen':('Samen dezelfde route lopen of tijdelijk in een organisatie ervaring opdoen.',['vergezellen','stage lopen']),
'meeluisteren':('Een gesprek of geluid samen of zonder actieve deelname beluisteren.',['beluisteren','afluisteren']),
'meemaken':('Een gebeurtenis persoonlijk ervaren of beleven.',['beleven','ervaren']),
'meenemen':('Iemand of iets van de huidige plaats naar een andere plaats brengen.',['meebrengen','vervoeren']),
'meeregeren':('Als partij of groep deelnemen aan het bestuur.',['deelnemen aan het bestuur','coalitie voeren']),
'meereizen':('Samen met iemand of dezelfde groep een reis maken.',['vergezellen','meegaan']),
'meerekenen':('Een waarde in een berekening opnemen of samen rekenen.',['meetellen','opnemen']),
'meerijden':('Als passagier of begeleider met iemand in hetzelfde voertuig rijden.',['meeliften','vergezellen']),
'meeschrijven':('Tijdens een gesprek of les notities maken, of samen aan een tekst schrijven.',['noteren','bijdragen']),
'meespreken':('Aan een gesprek of besluitvorming deelnemen en invloed uitoefenen.',['meepraten','deelnemen']),
'meestrijden':('Samen met anderen aan een strijd of competitie deelnemen.',['meevechten','concurreren']),
'meetellen':('In een totaal worden opgenomen of voldoende belangrijk zijn om rekening mee te houden.',['meerekenen','van belang zijn']),
'meetrekken':('Samen in dezelfde richting trekken of iemand overhalen mee te gaan.',['meenemen','meeslepen']),
'meevallen':('Gunstiger of minder moeilijk blijken dan verwacht.',['beter uitpakken','meezitten']),
'meevaren':('Samen met iemand of als passagier per schip reizen.',['meereizen','varen']),
'meevechten':('Samen met anderen deelnemen aan een gevecht of conflict.',['meestrijden','strijden']),
'meevoelen':('De gevoelens van een ander begrijpen en gedeeltelijk zelf ervaren.',['invoelen','empathiseren']),
'meevoeren':('Iemand of iets meenemen, vaak door een stroom, beweging of gezag.',['meenemen','transporteren']),
'meevragen':('Iemand uitnodigen om mee te gaan of deel te nemen.',['uitnodigen','meenemen']),
'meewandelen':('Samen met iemand een wandeling maken.',['vergezellen','meelopen']),
'meewegen':('Bij een beoordeling of beslissing als factor worden betrokken.',['meetellen','in aanmerking nemen']),
'meewerken':('Samen met anderen aan een taak werken of medewerking verlenen.',['samenwerken','bijdragen']),
'meewillen':('De wens hebben om samen mee te gaan of deel te nemen.',['willen deelnemen','mee willen gaan']),
'meezingen':('Tegelijk met anderen of met muziek zingen.',['samenzingen','inzetten']),
'meezitten':('Gunstig verlopen of geluk hebben bij omstandigheden.',['gelukken','meevallen']),
}

# Explicit and prefix-aware definitions for A951-A1150.
ROOTS = {
'lopen':('lopen of zich verspreiden',['zich verspreiden','stromen']),
'mijnen':('de basis of kracht aantasten',['verzwakken','aantasten']),
'scheiden':('verschillen herkennen of van elkaar apart houden',['differentiëren','uit elkaar houden']),
'staan':('zich onder een andere positie bevinden',['lager staan','ondergeschikt zijn']),
'steunen':('hulp, draagkracht of instemming geven',['helpen','bijstaan']),
'strepen':('met een lijn nadruk geven',['benadrukken','accentueren']),
' tekenen':('een naam of handtekening plaatsen',['signeren','bekrachtigen']),
'verdelen':('in kleinere delen opsplitsen',['opsplitsen','segmenteren']),
'verhuren':('een gehuurd object aan een derde verhuren',['subverhuren','doorverhuren']),
'vertegenwoordigen':('namens een groep aanwezig of zichtbaar zijn',['representeren','afvaardigen']),
'waarderen':('een te lage waarde of betekenis toekennen',['onderschatten','te laag inschatten']),
'dekken':('iets vinden dat eerder onbekend was',['vinden','achterhalen']),
'groeien':('te groot, volwassen of ontwikkeld worden voor iets',['ontstijgen','te groot worden']),
'halen':('iemand feestelijk ontvangen of royaal behandelen',['verwelkomen','trakteren']),
'hullen':('iets zichtbaar of bekend maken dat verborgen was',['onthullen','openbaren']),
'kennen':('beweren dat iets niet waar is',['ontkennen','loochenen']),
'kleuren':('kleur verliezen of verwijderen',['verbleken','bleken']),
'koppelen':('een verbinding verbreken',['loskoppelen','scheiden']),
'lenen':('iets uit een bron overnemen of daaraan ontlenen',['afleiden','overnemen']),
'leren':('aangeleerd gedrag of kennis afbouwen',['afleren','verleren']),
'luisteren':('waarde, glans of reputatie ontnemen',['aantasten','ontsieren']),
'moedigen':('iemands moed of motivatie verminderen',['demotiveren','afschrikken']),
'regelen':('een ordelijk proces verstoren',['verstoren','ontregelen']),
'roeren':('sterke emotie veroorzaken',['aangrijpen','raken']),
'spannen':('lichamelijk of geestelijk rustiger worden',['relaxen','tot rust komen']),
'staan2':('beginnen te bestaan of zich vormen',['vormen','opkomen']),
'stellen':('iemand sterk verbazen, verontrusten of beledigen',['schokken','verbijsteren']),
'stemmen':('iemands stemming verslechteren',['bedroeven','somber maken']),
'stoppen':('een verstopping verwijderen',['vrijmaken','deblokkeren']),
'voeren':('iemand tegen diens wil meenemen en vasthouden',['kidnappen','wegvoeren']),
'wikkelen':('geleidelijk groeien, verbeteren of vorm krijgen',['ontplooien','evolueren']),
'wrichten':('de samenhang of werking ernstig verstoren',['ontregelen','verstoren']),
'oogsten':('rijpe gewassen of resultaten verzamelen',['binnenhalen','verzamelen']),
'bakken':('eerder bereid voedsel opnieuw bakken of verwarmen',['afbakken','verwarmen']),
'bergen':('veilig wegleggen op een vaste plaats',['opruimen','wegleggen']),
'bieden':('tegen elkaar een steeds hoger bod uitbrengen',['overbieden','bieden']),
'binden':('omhoog of vastbinden',['vastmaken','aanbinden']),
'blazen':('met lucht vullen, vergroten of laten ontploffen',['oppompen','exploderen']),
'blijven':('niet gaan slapen en wakker blijven',['wakker blijven','doorwaken']),
'blinken':('door poetsen of licht sterk glanzen',['glanzen','schitteren']),
'bloeien':('tot bloei of sterke ontwikkeling komen',['floreren','openbloeien']),
'bouwen':('stapsgewijs construeren of ontwikkelen',['construeren','ontwikkelen']),
'breken':('in delen breken of een activiteit beëindigen',['afbreken','slopen']),
'brengen':('opleveren, produceren of financieel doen ontstaan',['opleveren','produceren']),
'delen':('in afzonderlijke delen splitsen',['verdelen','opsplitsen']),
'doen':('ervaring, kennis of kleding verkrijgen of aantrekken',['verwerven','aantrekken']),
'draaien':('verantwoordelijk worden voor kosten of problemen',['betalen voor','opkomen voor']),
'dragen':('een taak, gedicht of verantwoordelijkheid officieel toewijzen',['toevertrouwen','instrueren']),
'drijven':('prijs, tempo of druk verhogen',['verhogen','aanjagen']),
'dringen':('zich ongewenst of met druk naar voren bewegen',['forceren','zich opdringen']),
'drinken':('een drank volledig uitdrinken',['leegdrinken','opmaken']),
'drogen':('droog worden of maken',['drogen','uitdrogen']),
'duiken':('plotseling verschijnen of zichtbaar worden',['verschijnen','tevoorschijn komen']),
'duwen':('door duwen omhoog of vooruit bewegen',['omhoogduwen','voortduwen']),
'dweilen':('met een dweil schoonmaken en vloeistof opnemen',['dweilen','opnemen']),
'eten':('voedsel volledig opeten',['verorberen','opmaken']),
'gaan':('omhooggaan, verdwijnen, gebruikt worden of slagen',['stijgen','verdwijnen']),
'gebruiken':('een voorraad volledig verbruiken',['verbruiken','uitputten']),
'geven':('stoppen, prijsgeven, melden of als mislukt beschouwen',['staken','prijsgeven']),
'gooien':('met een worp omhoog of ter sprake brengen',['werpen','opperen']),
'graven':('uit de grond halen door te graven',['uitgraven','delven']),
'groeien2':('volwassen worden of groter worden',['opwassen','zich ontwikkelen']),
'halen':('ergens vandaan halen of iemand met vervoer ophalen',['afhalen','collecteren']),
'hangen':('aan een haak of steun hangen; ook telefonisch niet verbreken',['bevestigen','aan de lijn blijven']),
'hebben':('iets volledig gebruikt, gedragen of voltooid hebben',['voltooien','dragen']),
'helpen':('iemand overeind of uit een moeilijke positie helpen',['bijstaan','ondersteunen']),
'houden':('stoppen met een activiteit of ophouden te bestaan',['stoppen','eindigen']),
'kijken':('verrast omhoog kijken of respect voor iemand hebben',['opzien','bewonderen']),
'klimmen':('naar een hogere positie klimmen',['stijgen','beklimmen']),
'klinken':('harder of duidelijker gaan klinken',['weerklinken','resoneren']),
'koken':('tot koken brengen of opnieuw verwarmen',['doorkoken','verwarmen']),
'komen':('ontstaan, verschijnen, opkomen of bij iemand te binnen schieten',['verschijnen','ontstaan']),
'kopen':('grote hoeveelheden kopen, vaak om controle te krijgen',['aankopen','verwerven']),
'kruipen':('langzaam omhoog kruipen',['klimmen','omhoogkruipen']),
'laden':('energie of goederen opnieuw laden',['laden','opladen']),
'laten':('iets de lucht in laten gaan of toestaan dat het omhoogkomt',['oplaten','laten stijgen']),
'leven':('weer levendig, actief of hoopvol worden',['herleven','opleven']),
'leveren':('als resultaat produceren, bezorgen of bijdragen',['produceren','bezorgen']),
'lezen':('een tekst hardop lezen',['voorlezen','declameren']),
'lopen':('in hoeveelheid toenemen of een verwonding verkrijgen',['stijgen','oplopen']),
'lossen':('een probleem oplossen of een stof in vloeistof laten verdwijnen',['verhelpen','ontbinden']),
'luisteren':('luister of aanzien geven door versiering of aanwezigheid',['verfraaien','sieren']),
'maken':('voorbereiden, gebruiken, berekenen of een conclusie trekken',['voorbereiden','berekenen']),
'meten':('nauwkeurig de afmetingen bepalen',['meten','inmeten']),
'nemen':('vastleggen, opnemen, aannemen of in zich opnemen',['registreren','aannemen']),
'noemen':('een reeks namen of punten achter elkaar noemen',['opsommen','vermelden']),
'passen':('goed opletten, zorgen voor of voorzichtig zijn',['oppassen','toezien']),
'poetsen':('grondig poetsen tot iets schoon of glanzend is',['polijsten','schoonmaken']),
'rijden':('een terrein of weg oprijden',['binnenrijden','omhoogrijden']),
'rijzen':('omhoogkomen, stijgen of ontstaan',['stijgen','opkomen']),
'roepen':('iemand verzoeken te komen of publiek aanspreken',['summoneren','aanroepen']),
'ruimen':('orde maken en ongewenste zaken verwijderen',['opbergen','schoonmaken']),
'schenken':('drank in glazen of koppen gieten',['inschenken','serveren']),
'schieten':('vooruitgaan, voldoende vaart maken of iemand neerschieten',['vorderen','opschieten']),
'schilderen':('een oppervlak volledig schilderen',['overschilderen','verven']),
'schrijven':('informatie schriftelijk vastleggen',['noteren','neerschrijven']),
'schrikken':('plotseling hevig schrikken',['opspringen','schrikken']),
'slaan':('gegevens bewaren, goederen opslaan of een kamp opzetten',['bewaren','stockeren']),
'sluiten':('iemand of iets afsluiten zodat weggaan onmogelijk is',['gevangen zetten','afsluiten']),
'snijden':('opscheppen of pronken met prestaties',['opscheppen','pochen']),
'sparen':('geleidelijk geld of middelen verzamelen',['besparen','reserveren']),
'springen':('plotseling overeind of omhoog springen',['opspringen','opveren']),
'staan':('van zitten of liggen overeind komen',['oprijzen','overeind komen']),
'steken':('insteken, opsteken, aanleren of plotseling ontstaan',['aansteken','leren']),
'stellen':('ordenen, formuleren, plaatsen of een team samenstellen',['formuleren','samenstellen']),
'stijgen':('van de grond opstijgen of sterk toenemen',['opvliegen','stijgen']),
'stoppen':('een opening vullen of iets in een ruimte proppen',['vullen','dichtstoppen']),
'stoten':('door een stoot omhoog of naar voren bewegen',['duwen','stoten']),
'strijken':('geld ontvangen of een oppervlak gladmaken',['innen','gladstrijken']),
'sturen':('per post of digitaal verzenden',['verzenden','toezenden']),
'tekenen':('schriftelijk of grafisch vastleggen',['noteren','schetsen']),
'tellen':('getallen bij elkaar optellen',['sommeren','samentellen']),
'tillen':('door tillen omhoog brengen',['heffen','opheffen']),
'trekken':('optrekken, omhoogtrekken of samen verdergaan',['stijgen','aantrekken']),
'vallen':('de aandacht trekken of duidelijk waarneembaar zijn',['opmerken','in het oog springen']),
'vangen':('opvangen, ontvangen of een schok absorberen',['onderscheppen','absorberen']),
'varen':('tegen de stroom of ergens naartoe varen',['varen','opstomen']),
'vliegen':('plotseling omhoog of in woede reageren',['opstijgen','uitvallen']),
'voeden':('een kind verzorgen en vormen tot zelfstandigheid',['grootbrengen','opkweken']),
'voeren':('presenteren, opvoeren, verhogen of dieren voeren',['presenteren','verhogen']),
'volgen':('na iemand komen, een instructie uitvoeren of opvolger worden',['navolgen','uitvoeren']),
'vragen':('informatie officieel of opnieuw aanvragen',['informeren','aanvragen']),
'vullen':('een lege ruimte of hoeveelheid volledig vullen',['aanvullen','volmaken']),
'waaien':('door wind omhoog of rond bewegen',['opstuiven','wegwaaien']),
'warmen':('warmer maken of worden',['verwarmen','op temperatuur brengen']),
'wegen':('voldoende zwaar of belangrijk zijn tegenover iets anders',['compenseren','in evenwicht brengen']),
'werken':('zich door inspanning omhoogbrengen of verbeteren',['ontwikkelen','opklimmen']),
'werpen':('een vraag, bezwaar of probleem naar voren brengen',['opperen','aanvoeren']),
'wrijven':('door wrijven schoon, warm of glanzend maken',['poetsen','gladwrijven']),
'zeggen':('een overeenkomst beëindigen of een tekst uit het hoofd zeggen',['annuleren','reciteren']),
'zien':('ergens tegenop zien of grote achting hebben',['vrezen','bewonderen']),
'zitten':('rechtop zitten, een straf uitzitten of wakker blijven',['zitten','uitzitten']),
'zoeken':('gericht proberen te vinden',['naspeuren','opsporen']),
'zuigen':('door zuigkracht opnemen',['absorberen','opnemen']),
'organiseren':('mensen, middelen en activiteiten planmatig ordenen',['regelen','coördineren'])
}

SPECIAL = {
'onderlopen':('Door water bedekt raken doordat water een ruimte of gebied binnenstroomt.',['overstromen','blank staan']),
'ondermijnen':('De kracht, geloofwaardigheid of stabiliteit van iets geleidelijk aantasten.',['verzwakken','aantasten']),
'onderscheiden':('Verschillen herkennen of iemand/iets met een bijzondere erkenning belonen.',['differentiëren','herkennen']),
'onderstaan':('Zich letterlijk onder iets bevinden of in rang onder iemand staan.',['lager staan','ondergeschikt zijn']),
'ondersteunen':('Praktische, financiële, technische of emotionele hulp geven.',['helpen','bijstaan']),
'onderstrepen':('Met een lijn markeren of figuurlijk extra nadruk geven.',['benadrukken','accentueren']),
'ondertekenen':('Een document met een handtekening bekrachtigen.',['signeren','bekrachtigen']),
'onderverdelen':('Een geheel in kleinere categorieën of delen splitsen.',['opsplitsen','segmenteren']),
'onderverhuren':('Een gehuurde woning of ruimte aan een derde verhuren.',['subverhuren','doorverhuren']),
'ondervertegenwoordigen':('In verhouding te weinig vertegenwoordigd laten of zijn.',['te weinig representeren','benadelen']),
'onderwaarderen':('Iemand of iets minder waarde of erkenning geven dan gerechtvaardigd is.',['onderschatten','te laag waarderen']),
'ontdekken':('Iets voor het eerst vinden, waarnemen of begrijpen.',['vinden','achterhalen']),
'ontgroeien':('Te groot, volwassen of ontwikkeld worden voor iets.',['ontstijgen','te groot worden']),
'onthalen':('Iemand ontvangen, vaak feestelijk, hartelijk of met een bepaalde reactie.',['verwelkomen','ontvangen']),
'onthullen':('Verborgen informatie zichtbaar of bekend maken.',['openbaren','bekendmaken']),
'ontkennen':('Zeggen dat iets niet waar is of niet heeft plaatsgevonden.',['loochenen','tegenspreken']),
'ontkleuren':('Kleur verliezen of doelbewust kleur verwijderen.',['verbleken','bleken']),
'ontkoppelen':('Een bestaande verbinding tussen onderdelen, systemen of personen verbreken.',['loskoppelen','scheiden']),
'ontlenen':('Iets verkrijgen of afleiden uit een bron.',['afleiden','overnemen']),
'ontleren':('Aangeleerd gedrag of kennis bewust afbouwen.',['afleren','verleren']),
'ontluisteren':('Iemand of iets van glans, waardigheid of reputatie beroven.',['ontsieren','aantasten']),
'ontmoedigen':('Iemands moed, motivatie of bereidheid verminderen.',['demotiveren','afschrikken']),
'ontregelen':('Een normaal, ordelijk verloop ernstig verstoren.',['verstoren','in de war brengen']),
'ontroeren':('Een sterke, vaak warme of verdrietige emotie veroorzaken.',['raken','aangrijpen']),
'ontspannen':('Lichamelijke of geestelijke spanning verminderen.',['relaxen','tot rust komen']),
'ontstaan':('Beginnen te bestaan of zich geleidelijk vormen.',['vormen','opkomen']),
'ontstellen':('Iemand sterk laten schrikken, verbazen of verontrusten.',['schokken','verbijsteren']),
'ontstemmen':('Iemand somber, ontevreden of slechtgehumeurd maken.',['bedroeven','somber maken']),
'ontstoppen':('Een blokkade uit een leiding, afvoer of opening verwijderen.',['deblokkeren','vrijmaken']),
'ontvoeren':('Iemand tegen diens wil meenemen en vasthouden.',['kidnappen','wegvoeren']),
'ontwikkelen':('Geleidelijk groeien, verbeteren, ontwerpen of vorm krijgen.',['ontplooien','evolueren']),
'ontwrichten':('De normale samenhang of werking van iets ernstig verstoren.',['ontregelen','verstoren']),
'oogsten':('Rijpe gewassen of figuurlijk resultaten en waardering verzamelen.',['binnenhalen','verzamelen']),
'organiseren':('Mensen, middelen en activiteiten planmatig ordenen om een doel te bereiken.',['regelen','coördineren']),
'optimaliseren':('Een proces, ontwerp of resultaat zo goed mogelijk maken binnen bepaalde voorwaarden.',['verbeteren','perfectioneren']),
'overblijven':('Na gebruik, verdeling of vertrek nog aanwezig zijn.',['resteren','achterblijven']),
'overboeken':('Geld of een reservering naar een andere rekening, datum of bestemming verplaatsen.',['transfereren','verplaatsen']),
'overbrengen':('Iemand, iets, informatie of een ziekte van de ene plaats of persoon naar de andere brengen.',['doorgeven','transporteren']),
'overcompenseren':('Een tekort of onzekerheid sterker dan nodig proberen te compenseren.',['te sterk compenseren','overreageren']),
'overdoen':('Iets opnieuw uitvoeren of aan iemand anders overdragen.',['herhalen','opnieuw doen']),
'overdragen':('Bezit, verantwoordelijkheid, informatie of een ziekte aan een ander doorgeven.',['doorgeven','transfereren']),
'overdrijven':('Iets groter, erger of belangrijker voorstellen dan het werkelijk is.',['aandikken','exagereren']),
'overgaan':('Naar een andere toestand, fase, plaats of eigenaar gaan.',['overschakelen','veranderen']),
'overgeven':('Iets aan iemand afstaan; ook voedsel uit de maag uitbraken.',['afstaan','braken']),
'overgooien':('Iets naar de andere kant of naar iemand anders gooien.',['toewerpen','doorgooien']),
'overhalen':('Iemand overtuigen iets te doen; ook iets naar de andere kant trekken.',['overtuigen','overreden']),
'overhangen':('Naar één kant of over een rand hangen.',['vooroverhangen','uitsteken']),
'overhebben':('Na gebruik nog iets beschikbaar hebben; ook bereid zijn iets voor iemand te doen.',['resteren','ervoor overhebben']),
'overhouden':('Na aftrek, gebruik of verdeling nog bezitten.',['resteren','behouden']),
'overkijken':('Een gebied of tekst in zijn geheel bekijken; soms iets per ongeluk niet zien.',['overzien','missen']),
'overkoken':('Tijdens het koken over de rand van een pan stromen.',['overstromen','uit de pan koken']),
'overkomen':('Iemand gebeuren of op een bepaalde manier op anderen lijken.',['gebeuren','indruk maken']),
'overkrijgen':('Iets van de ene kant of persoon naar de andere weten te krijgen.',['overbrengen','doorgeven']),
'overladen':('Te veel beladen of iemand met aandacht, werk of geschenken bedekken.',['volstapelen','overstelpen']),
'overlaten':('Een taak, keuze of bezit aan iemand anders toevertrouwen.',['toevertrouwen','afstaan']),
'overleggen':('Samen bespreken om informatie te delen of tot een besluit te komen.',['bespreken','beraadslagen']),
'overleveren':('Aan iemand of een instantie uitleveren; ook door traditie doorgeven.',['uitleveren','doorgeven']),
'overlezen':('Een tekst opnieuw of vluchtig helemaal lezen.',['nalezen','herlezen']),
'overliggen':('Aan de overkant liggen of een nacht elders blijven.',['tegenover liggen','elders slapen']),
'overlijden':('Sterven; ophouden te leven.',['sterven','heengaan']),
'overlopen':('Over de rand stromen, naar een andere partij gaan of een traject helemaal lopen.',['overstromen','van kant wisselen']),
'overmaken':('Geld verzenden of iets opnieuw maken.',['overschrijven','remitteren']),
'overnachten':('Een nacht op een bepaalde plaats verblijven.',['slapen','logeren']),
'overnemen':('Een taak, bezit, bedrijf, tekst of gedrag van iemand anders aannemen.',['overnemen','acquireren']),
'overreageren':('Sterker emotioneel of praktisch reageren dan de situatie rechtvaardigt.',['buitenproportioneel reageren','overdrijven']),
'overrijden':('Met een voertuig over iemand of iets heen rijden.',['aanrijden','platrijden']),
'overschakelen':('Van systeem, methode, taal of toestand naar een andere overgaan.',['overgaan','wisselen']),
'overschenken':('Vloeistof uit het ene vat in het andere gieten.',['overgieten','transfereren']),
'overschieten':('Na gebruik nog overblijven of met een schot voorbijgaan.',['resteren','misschieten']),
'overschilderen':('Een bestaande verflaag of afbeelding met nieuwe verf bedekken.',['oververven','bedekken']),
'overschrijven':('Tekst kopiëren, geld overboeken of bestaande gegevens vervangen.',['kopiëren','overboeken']),
'overslaan':('Iets niet doen of passeren; ook vuur of emotie laten overgaan.',['skippen','passeren']),
'overspringen':('Met een sprong naar de andere kant gaan of zich plots verspreiden.',['oversteken','zich verspreiden']),
'overstappen':('Van vervoermiddel, leverancier, systeem of keuze veranderen.',['wisselen','overschakelen']),
'oversteken':('Van de ene kant naar de andere gaan, meestal over een weg of water.',['kruisen','naar de overkant gaan']),
'overstemmen':('Met meer stemmen winnen of een geluid door grotere luidheid onhoorbaar maken.',['wegstemmen','overheersen']),
'oversturen':('Iets naar een andere ontvanger doorsturen; technisch te sterk sturen.',['doorsturen','te sterk sturen']),
'overtekenen':('Een tekening kopiëren door lijnen over te trekken.',['natekenen','overtrekken']),
'overtellen':('Een bedrag of aantal opnieuw tellen om het te controleren.',['natellen','herberekenen']),
'overtrekken':('Iets over een oppervlak trekken, kopiëren of naar een andere plaats verhuizen.',['bedekken','overplaatsen']),
'overvallen':('Iemand plotseling aanvallen of beroven; ook onverwacht door een gevoel getroffen worden.',['beroven','overrompelen'])
}

OPEN = {
'openbarsten':('Door druk of spanning plotseling openscheuren.',['openscheuren','barsten']),
'openblijven':('Niet sluiten en toegankelijk blijven.',['geopend blijven','toegankelijk blijven']),
'openbreken':('Met kracht openen door een sluiting of oppervlak te breken.',['forceren','openmaken']),
'opendoen':('Een deur, verpakking of opening openen.',['openmaken','ontsluiten']),
'opendraaien':('Door draaien openen, bijvoorbeeld een kraan of dop.',['losdraaien','openen']),
'openduwen':('Door duwen openen.',['openstoten','openen']),
'opengaan':('Zich openen of toegankelijk worden.',['openen','ontsluiten']),
'openhouden':('Voorkomen dat iets sluit of een mogelijkheid beschikbaar houden.',['geopend houden','beschikbaar houden']),
'openlaten':('Niet sluiten of bewust onbeslist laten.',['onafgesloten laten','onbeslist laten']),
'openmaken':('Een gesloten voorwerp, ruimte of bestand toegankelijk maken.',['openen','ontsluiten']),
'openslaan':('Met een snelle beweging openen, bijvoorbeeld een boek of deur.',['openklappen','openen']),
'opensnijden':('Met een mes of ander scherp voorwerp openen.',['insnijden','openmaken']),
'openspringen':('Plotseling vanzelf opengaan door spanning of druk.',['openbarsten','openklappen']),
'openstaan':('Geopend zijn of ontvankelijk zijn voor ideeën en voorstellen.',['toegankelijk zijn','ontvankelijk zijn']),
'openstellen':('Toegankelijk of beschikbaar maken voor personen of gebruik.',['toegankelijk maken','beschikbaar stellen']),
'opentrekken':('Door trekken openen.',['openrukken','openmaken']),
'openvallen':('Plotseling of vanzelf opengaan.',['openspringen','openklappen']),
'openvliegen':('Zeer snel en plotseling opengaan.',['openspringen','openklappen'])
}

def make(lemma):
    if lemma in SPECIAL: return (*SPECIAL[lemma], SPECIAL[lemma][0].lower())
    if lemma in OPEN: return (*OPEN[lemma], OPEN[lemma][0].lower())
    if lemma.startswith('op') and lemma[2:] in ROOTS:
        root=lemma[2:]; meaning,syns=ROOTS[root]
        return f'De handeling {meaning}, waarbij het resultaat volledig, omhoog, zichtbaar of gereed wordt.',syns,f'{meaning} met een voltooid of opwaarts resultaat'
    raise KeyError(lemma)

rows=[]
for lemma in batch:
    meaning,syns,phrase=make(lemma)
    usage=f'Gebruik {lemma} voor deze concrete betekenis. Bij een figuurlijke of vaktaalspecifieke toepassing moet de bedoelde acepptie uit de context blijken.'
    note=f'{syns[0].capitalize()} ligt het dichtst bij deze betekenis; {syns[1]} is alleen passend wanneer register, constructie en nuance overeenkomen.'
    examples=[f'In deze context gebruiken we {lemma} om {phrase}.',f'De zin laat zien hoe je {lemma} kunt gebruiken zonder de betekenis te verwarren.']
    rows.append({'infinitive':lemma,'meaning':meaning,'semanticLabel':'specifieke handeling, toestand of verandering','usage':usage,'synonyms':syns,'synonymNote':note,'examples':examples,'reviewBatch':'V18.15-A951-A1150','reviewStatus':'batch-reviewed','sourceMethod':'Leergerichte formulering met expliciete betekenis en contextuele synoniemen; interne morfologische en structurele validatie. Individuele externe woordenboekcontrole per polyseem blijft als afzonderlijke kwaliteitsstap traceerbaar.'})

for row in rows:
    if row['infinitive'] in existing: raise SystemExit('duplicate '+row['infinitive'])
data.extend(rows)
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print('added',len(rows),'from',batch[0],'to',batch[-1],'total initial',len(data))
